---
title: Multifidus Muscle
---



```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'muscle_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['multifidus']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


# Origin {#origin}
Sacrum, ilium, mamillary process of L1-L5, T1-T4 (TP and Articular process), C4-C7 @gilroyAtlasAnatomy2020

# Insertion {#insertion} 
Superomedially to SP (skipping 2-4 vertebrae) @gilroyAtlasAnatomy2020

# Innervation {#innervation}
[Spinal nn. (Posterior Rami)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

# Action {#action}

- **BIL**: Extends extends spine @gilroyAtlasAnatomy2020
- **UNIL**: I/L SB and C/L Rotation @gilroyAtlasAnatomy2020




# Therex
How to recruit multifidi instead of obliques?
One can bias the multifidi over the obliques by performing exercises that require spine extension rather than flexion.

## Single leg bridge
One can recruit the multifidus muscle by having a patient perform a single leg bridge. In this exercise, one will have a leg on the ground (stance leg) and another leg in the air. Both shoulders will remain on the ground the whole time. As an example, we will imagine an individual using their R leg as the stance leg. Since both shoulders are stationary, the weight of the pelvis and raised leg (L) will add a load d/t gravity that pulls the L hip towards the ground, resulting in relative right rotation. Thus, in order to keep the pelvis level, one must perform active left rotation using the R multifidus since the multifidi perform C/L rotation unilaterally. An easy way to remember which multifid you are recruiting during S/L bridge is that the multifidi on the same side as the stance leg is being recruited.


## Bird-Dogs