---
title: Long Plantar Ligament
---



Serves as the muscular origin for the [Flexor digiti minimi brevis]({{< var ref-flexor-digiti-minimi-brevis-foot.path >}})


```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/gt_oian.R"))

# Example usage
identifier_col <- "origin_identifier"  # or "group_identifier"
filter_patterns <- "long_plantar_ligament"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Muscular origins involving the Long Plantar Lig."

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```


```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/gt_oian.R"))

# Example usage
identifier_col <- "insertion_identifier"  # or "group_identifier"
filter_patterns <- "long_plantar_ligament"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Muscular insertions involving the Long Plantar Lig."

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```