---
title: Tibial Nerve
---

Note the [tibial nerve]({{< var ref-tibial-nerve.path >}}) as it follows a distal path through the center of the tibiofemoral joint line, but then quickly courses medially towards the *tarsal tunnel* @jonesProjectFoundations2025.
The [tibial nerve]({{< var ref-tibial-nerve.path >}}) enters the lower leg then pierces the soleus muscle @jonesProjectFoundations2025.

# Roots

# Pathway

# Branches

- Medial plantar
- Lateral plantar
- Sural (shared common fib and tibial) 

# Motor innervation

- Triceps surae @gilroyAtlasAnatomy2020
    - Gastrocnemius @gilroyAtlasAnatomy2020
    - Soleus @gilroyAtlasAnatomy2020
- Plantaris @gilroyAtlasAnatomy2020
- Popliteus @gilroyAtlasAnatomy2020
- Tibialis posterior @gilroyAtlasAnatomy2020
- Flexor digitorum longus @gilroyAtlasAnatomy2020
- Flexor hallucis longus @gilroyAtlasAnatomy2020

```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'innervation_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['tibial_nerve']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Adductor Magnus]({{< var ref-adductor-magnus.path >}}) | {{< var ref-adductor-magnus.origin >}} | {{< var ref-adductor-magnus.insertion >}} | {{< var ref-adductor-magnus.nerve >}} | {{< var ref-adductor-magnus.action >}} |
| [Biceps Femoris Long Head]({{< var ref-biceps-femoris-long-head.path >}}) | {{< var ref-biceps-femoris-long-head.origin >}} | {{< var ref-biceps-femoris-long-head.insertion >}} | {{< var ref-biceps-femoris-long-head.nerve >}} | {{< var ref-biceps-femoris-long-head.action >}} |
| [Semitendinosus]({{< var ref-semitendinosus.path >}}) | {{< var ref-semitendinosus.origin >}} | {{< var ref-semitendinosus.insertion >}} | {{< var ref-semitendinosus.nerve >}} | {{< var ref-semitendinosus.action >}} |
| [Semimembranosus]({{< var ref-semimembranosus.path >}}) | {{< var ref-semimembranosus.origin >}} | {{< var ref-semimembranosus.insertion >}} | {{< var ref-semimembranosus.nerve >}} | {{< var ref-semimembranosus.action >}} |
: Direct Innervation From Sciatic N. {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Gastrocnemius]({{< var ref-gastrocnemius.path >}}) | {{< var ref-gastrocnemius.origin >}} | {{< var ref-gastrocnemius.insertion >}} | {{< var ref-gastrocnemius.nerve >}} | {{< var ref-gastrocnemius.action >}} |
| [Soleus]({{< var ref-soleus.path >}}) | {{< var ref-soleus.origin >}} | {{< var ref-soleus.insertion >}} | {{< var ref-soleus.nerve >}} | {{< var ref-soleus.action >}} |
| [Plantaris]({{< var ref-plantaris.path >}}) | {{< var ref-plantaris.origin >}} | {{< var ref-plantaris.insertion >}} | {{< var ref-plantaris.nerve >}} | {{< var ref-plantaris.action >}} |
| [Tibialis Posterior]({{< var ref-tibialis-posterior.path >}}) | {{< var ref-tibialis-posterior.origin >}} | {{< var ref-tibialis-posterior.insertion >}} | {{< var ref-tibialis-posterior.nerve >}} | {{< var ref-tibialis-posterior.action >}} |
| [Flexor Digitorum Longus]({{< var ref-flexor-digitorum-longus.path >}}) | {{< var ref-flexor-digitorum-longus.origin >}} | {{< var ref-flexor-digitorum-longus.insertion >}} | {{< var ref-flexor-digitorum-longus.nerve >}} | {{< var ref-flexor-digitorum-longus.action >}} |
| [Flexor Hallucis Longus]({{< var ref-flexor-hallucis-longus.path >}}) | {{< var ref-flexor-hallucis-longus.origin >}} | {{< var ref-flexor-hallucis-longus.insertion >}} | {{< var ref-flexor-hallucis-longus.nerve >}} | {{< var ref-flexor-hallucis-longus.action >}} |
: {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Flexor Digitorum Brevis]({{< var ref-flexor-digitorum-brevis.path >}}) | {{< var ref-flexor-digitorum-brevis.origin >}} | {{< var ref-flexor-digitorum-brevis.insertion >}} | {{< var ref-flexor-digitorum-brevis.nerve >}} | {{< var ref-flexor-digitorum-brevis.action >}} |
| [Lumbricals (foot)]({{< var ref-foot-lumbricals.path >}}) | {{< var ref-foot-lumbricals.origin >}} | {{< var ref-foot-lumbricals.insertion >}} | {{< var ref-foot-lumbricals.nerve >}} | {{< var ref-foot-lumbricals.action >}} |
| [Flexor Hallucis Brevis]({{< var ref-flexor-hallucis-brevis.path >}}) | {{< var ref-flexor-hallucis-brevis.origin >}} | {{< var ref-flexor-hallucis-brevis.insertion >}} | {{< var ref-flexor-hallucis-brevis.nerve >}} | {{< var ref-flexor-hallucis-brevis.action >}} |
| [Adductor Hallucis]({{< var ref-adductor-hallucis.path >}}) | {{< var ref-adductor-hallucis.origin >}} | {{< var ref-adductor-hallucis.insertion >}} | {{< var ref-adductor-hallucis.nerve >}} | {{< var ref-adductor-hallucis.action >}} |
: Medial Plantar N. Innervation {.striped .hover}

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Abductor Digiti Minimi (foot)]({{< var ref-abductor-digiti-minimi-foot.path >}}) | {{< var ref-abductor-digiti-minimi-foot.origin >}} | {{< var ref-abductor-digiti-minimi-foot.insertion >}} | {{< var ref-abductor-digiti-minimi-foot.nerve >}} | {{< var ref-abductor-digiti-minimi-foot.action >}} |
| [Quadratus Plantae]({{< var ref-quadratus-plantae.path >}}) | {{< var ref-quadratus-plantae.origin >}} | {{< var ref-quadratus-plantae.insertion >}} | {{< var ref-quadratus-plantae.nerve >}} | {{< var ref-quadratus-plantae.action >}} |
| [Lumbricals (foot)]({{< var ref-foot-lumbricals.path >}}) | {{< var ref-foot-lumbricals.origin >}} | {{< var ref-foot-lumbricals.insertion >}} | {{< var ref-foot-lumbricals.nerve >}} | {{< var ref-foot-lumbricals.action >}} |
| [Flexor Hallucis Brevis]({{< var ref-flexor-hallucis-brevis.path >}}) | {{< var ref-flexor-hallucis-brevis.origin >}} | {{< var ref-flexor-hallucis-brevis.insertion >}} | {{< var ref-flexor-hallucis-brevis.nerve >}} | {{< var ref-flexor-hallucis-brevis.action >}} |
| [Adductor Hallucis]({{< var ref-adductor-hallucis.path >}}) | {{< var ref-adductor-hallucis.origin >}} | {{< var ref-adductor-hallucis.insertion >}} | {{< var ref-adductor-hallucis.nerve >}} | {{< var ref-adductor-hallucis.action >}} |
| [Flexor Digiti Minimi Brevis (Foot)]({{< var ref-flexor-digiti-minimi-brevis-foot.path >}}) | {{< var ref-flexor-digiti-minimi-brevis-foot.origin >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.insertion >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.nerve >}} | {{< var ref-flexor-digiti-minimi-brevis-foot.action >}} |
| [Opponens Digiti Minimi (Foot)]({{< var ref-opponens-digiti-minimi-foot.path >}}) | {{< var ref-opponens-digiti-minimi-foot.origin >}} | {{< var ref-opponens-digiti-minimi-foot.insertion >}} | {{< var ref-opponens-digiti-minimi-foot.nerve >}} | {{< var ref-opponens-digiti-minimi-foot.action >}} |
| [Plantar Interossei (Foot)]({{< var ref-plantar-interossei-foot.path >}}) | {{< var ref-plantar-interossei-foot.origin >}} | {{< var ref-plantar-interossei-foot.insertion >}} | {{< var ref-plantar-interossei-foot.nerve >}} | {{< var ref-plantar-interossei-foot.action >}} |
| [Dorsal Interossei (Foot)]({{< var ref-dorsal-interossei-foot.path >}}) | {{< var ref-dorsal-interossei-foot.origin >}} | {{< var ref-dorsal-interossei-foot.insertion >}} | {{< var ref-dorsal-interossei-foot.nerve >}} | {{< var ref-dorsal-interossei-foot.action >}} |
: Lateral Plantar N. Innervations {.striped .hover}

# Cutaneous Innervation

- Medial sural cutaneous n. @gilroyAtlasAnatomy2020
- Medial and lateral calcaneal brs. @gilroyAtlasAnatomy2020 
- Lateral dorsal cutaneous n. @gilroyAtlasAnatomy2020

# Plantar reflex {#plantar-reflex}

The *tibial n.* serves as the afferent aspect in the plantar reflex loop.

Plantar reflex is a superficial reflex where stroking of the lateral sole of the calcaneus to the base of 5th metatarsal results in toe plantarflexion.

An **abnormal** plantar reflex refers to when you stroke the foot and the 1st toe dorsiflexes while toes 2-5 abduct.
This abnormal plantar reflex is known as a positive "Babinski sign" and is often observed in patients with corticospinal/UMN lesions.



# Dysfunction

Entrapment sites: 

- Indirect
    - 
- Direct
    - Soleus origin
    - Tarsal tunnel 

# Palpation

- Patient positioned in prone
- Palpate [lateral head of the gastrocnemius]({{< var ref-gastrocnemius.origin >}}) at the distal joint line of the [tibiofemoral joint]({{< var ref-tibiofemoral-joint.path >}}).
- Move *medially* and you should be able to strum the tibial nerve as it runs vertically.
- Follow the tibial nerve inferiorly to palpate where it passes through the [soleus origin]({{< var ref-soleus.origin >}}).
    - This can be a place where the tibial nerve can be entrapped @jonesProjectFoundations2025.

# Treatment

- [Soleus origin release]({{< var ref-soleus.release >}})

# Notes

"The tibial nerve, the larger of the two branches of the sciatic nerve, begins its own course in the upper part of the popliteal space. It descends vertically through this space, passing between the heads of the gastrocnemius muscle to the posterior aspect of the leg, and to the posteromedial aspect of the ankle, where its terminal branches serve the foot and ankle (see Chapter 21)." @duttonDuttonOrthopaedicExamination2020 

"The tibial nerve supplies the gastrocnemius, plantaris, soleus, popliteus, tibialis posterior, flexor digitorum longus, and flexor hallucis longus muscles. Articular branches pass to the knee and ankle joints." @duttonDuttonOrthopaedicExamination2020 


# Entrapment {#entrapment}

::: {.callout title="Reading list"}

- Tibkal nerve p373 @DynamicNeurologicalStabilizationClinicalRehabilitation2014

:::