---
title: High Level Mobility Assessment Tool (HiMAT)
subtitle: Mobility and Balance outcome measure
---


# Form

1. [Walk](#form-walk)
1. [Walk Backwards](#form-backwards)
1. [Walk on Toes](#form-on-toes)
1. [Walk over Obstacle](#form-obstacle)
1. [Run](#form-run)
1. [Skip](#form-skip)
1. [Hop Forward](#form-hop-forward)
1. [Bound (Affected)](#form-bound-affected)
1. [Bound (Less affected)](#form-bound-less-affected)
1. [Dependent Stair Ascension](#form-dependent-stair-ascension)
1. [Independent Stair Ascension](#form-independent-stair-ascension)
1. [Dependent Stair Descension](#form-dependent-stair-descension)
1. [Independent Stair Descension](#form-independent-stair-descension)

## Walk {#form-walk}

## Walk Backwards {#form-backwards}

## Walk on toes {#form-on-toes}

## Walk over Obstacle {#form-over-obstacle}

## Run {#form-run}

## Skip {#form-skip}

## Hop forward {#form-forward-hop}


## Bound (Affected) {#form-bound-affected}

## Bound (Less-Affected) {#form-bound-less-affected}

## Dependent Stair Descension {#form-dependent-stair-ascension}

## Independent Stair Ascension {#form-independent-stair-ascension}

## Dependent Stair Descension {#form-dependent-stair-descension}

## Independent Stair Descension {#form-independent-stair-descension}