---
title: Rotatores Muscle
---


::: {.callout title="Reading list"}

- Ch16 rotatores Muscle @donnellyTravellSimonsSimons2019
- Thoracolumbar paraspinal muscles @donnellyTravellSimonsSimons2019
- Neuman @neumannKinesiologyMusculoskeletalSystem2017

:::


```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['rotatores_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

The rotatores muscles can be divided into 

- Rotatores cervicis
- Rotatores Thoracis
- Rotatores lumborum

Furthermore, these can be broken down into **long** and **short** muscles @jonesProjectFoundations2025.

- **Long muscles** span **2** vertebrae @jonesProjectFoundations2025.
- **Short muscles** span **1** vertebrae @jonesProjectFoundations2025.



# Rotatores Breves
## Origin {#origin}
T1-T12 TP of lower vertebrae @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
T1-T12: SP of adjacent vertebrae @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. (Posterior Rami)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}

- **BIL**: Extends T/S @gilroyAtlasAnatomy2020
- **UNIL**: C/L Rotation of T/S @gilroyAtlasAnatomy2020


# Rotatores Longi
## Origin {#origin}
T1-T12 TP of lower vertebrae @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
T1-T12: SP of vertebrae 2 above (it skips a vertebrae) @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. (Posterior Rami)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}

- **BIL**: Extends T/S @gilroyAtlasAnatomy2020
- **UNIL**: C/L Rotation of T/S @gilroyAtlasAnatomy2020