---
title: Bony Landmarks
---


- Fossae: Broad elongated depressions are called fossae @standringGraysAnatomyAnatomical2021
- Sulci or Grooves: lengthy depressions @standringGraysAnatomyAnatomical2021
- Notch is an incisura
- Hiatus: an actual gap @standringGraysAnatomyAnatomical2021
- Process: A large projection
    - Spine: Elongated, slender, and/or pointed projection 
- Hamulus/Cornu: A curved process (e.g. the pterygoid hamuli of the sphenoid bone and the cornua of the hyoid)
- Tuberosity/Tubercle: A rounded projection 
    - occasionally a trochanter
- Crests: Long elevations are crests
    - Lines: Less developed crests
    - crests are wider and present boundary edges or lips
- Epicondyle: a projection close to a condyle
    - usually a site where the common tendon of a superficial muscle group or a collateral ligament of the adjacent joint is attached.
- Protuberance, prominence, eminence and torus are occasionally applied to specific bony projections.
- Head/Caput: The expanded proximal end of a long bone
- Hole in the bone:
    - Foramen: A hole in a bone 
    - Canal a lengthy hole in a bone 
    - Aperture: Large hole in a bone
    - Fenestra: Hole covered by connective tissue 
- Fissures: Clefts in or between bones are fissures
- Lamina: a thin plate
    - Squamae: Larger lamina


<!-- Small articular surfaces are termed facets or foveae; larger, knuckle-shaped surfaces are condyles; a trochlea is grooved like a pulley. Articular surfaces are smooth and covered by articular cartilage, which means that they lack the vascular foramina typical of the surfaces of most other bones