---
title: Breathing Pattern Disorders
---
@chaitowRecognizingTreatingBreathing2014


- Hyperventilation Syndromes (HvS)
- Breathing Pattern disorderes (BPD)




- Hypoventilation: "occurs when excessively shallow respiration, resulting in poor gas exchange, leading to *increased* concentrations of CO<sub>2</sub> (hypercapnia) and respiratory or metabolic acidosis

Blood volume concentrations

- CO2 Blood volume concentrations
    - Hypocapnia
    - Hypercapnia
- O2 Blood volume concentrations
    - Hypoxia: Abnormally low (below physiologically levels) oxygen (O2) supply to tissue despite adequate perfusion of the tissue by blood @chaitowRecognizingTreatingBreathing2014
        - Anoxia: The extreme of hypoxia


# Secondary Adaptations from BPD

- Visceral stasis, pelvic floor weakness, imbalance between weak abdominal muscles and overly-tight spinal extensor muscles @chaitowRecognizingTreatingBreathing2014
- Fascia becomes restricted from the *central tendon*  from the pericardial fascia and the restriction continues to the basioocciput @chaitowRecognizingTreatingBreathing2014
- Elevated upper ribs with sensitive/hyperalgesic costal cartilages @chaitowRecognizingTreatingBreathing2014
- Thoracic spine will be dysfunctional due to rib hypomobility and increase sympathetic outflow @chaitowRecognizingTreatingBreathing2014
- Accessory respiratory muscle dysfunction (Scalenes, UT, Levator scapulae) @chaitowRecognizingTreatingBreathing2014
    - Fibrotic changes along with myofascial TrPs
- Hypomobile/rigid cervical spine with "fixed" lordosis @chaitowRecognizingTreatingBreathing2014



# Hyperventilation Syndromes (HvS)

Hyperventilation syndrome is a an extreme version of BPD

hyperventilation syndrome refers to breathing in *excess* of metabolic requirements, resulting in abnormally low blood carbon dioxide [CO<sub>2</sub>] concentrations @chaitowRecognizingTreatingBreathing2014

- AKA
    - Overbreathing
    - Soldier's Heart
    - Effort syndrome

- can result in: @chaitowRecognizingTreatingBreathing2014
    - Hyperventilation -> respiratory alkalosis
        - numbness
        - tingling
        - Dizziness
        - Muscular hypertonicity

