project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  error: true
  cache: false
  keep-ipynb: false
  python:
    executable: /Users/nathanielyomogida/miniconda3/bin/python3

lightbox: auto

author:
- id: NGY
  number: 1
  name: 
    given: Nate
    family: Yomogida
  email: "nate.yomogida.pt@gmail.com"
  url: "https://yomokerst.com/about.html#ngy"
  affiliation:
    - Doctor of Physical Therapy
    - B.S. in Kinesiology
  degrees:
    - PT, DPT
- id: CAK
  number: 2
  name: 
    given: Chloë
    family: Kerstein
  email: "Chloekerst@gmail.com"
  url: "https://yomokerst.com/about.html#cak"
  affiliation:
    - Doctor of Physical Therapy
    - B.A. in Neuroscience
  degrees:
    - PT, DPT

publisher: Yomokerst

website:
  twitter-card:
    creator: "@NateYomogida and @Chloe_Kerstein"
    site: "@yomokerst"
  favicon: "/images/brain-favicon.png"
  page-navigation: true
  search:
    keyboard-shortcut: ["?", "H"]
  # title: "YK LAB"
  site-url: https://yomokerst.com
  navbar:
    logo: "/branding/Yomokerst/yomokerst heavy condensed black.png"
    left:
      - href: index.qmd
        text: Home
      - href: The Archive/research_and_development_index.qmd
        text: "R&D"
      - href: journal_club_index.qmd
        text: Journal Club
      - href: "/Care Division/care_division.qmd"
        text: "Physical Therapy"
      - about.qmd
      - href: contact.qmd
        text: Contact

citation:
  type: post-weblog
appendix-cite-as: display


citeproc: true #j I added this to get the typst to work
bibliography: "The Archive/Bibliography/yk_lab_bibliography.bib"
csl: The Archive/Bibliography/american-medical-association.csl

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    number-sections: false
    tbl-cap-location: top
    theme:
      light: cosmo
      dark: darkly
    mainfont: helvetica
    fontsize: 16px
    css: styles.css
  # typst:
  #   toc: true
  #   section-numbering: 1.1.a
  #   columns: 1
  
