project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  error: true
  cache: false

lightbox: auto

author:
- id: NGY
  number: 1
  name: 
    given: Nathaniel
    family: Yomogida
  email: "nate.yomogida.pt@gmail.com"
  url: "https://nateyomo.github.io/Yomogida-Kerstein-Lab/about.html#ngy"
  affiliation:
    - Doctor of Physical Therapy
    - B.S. in Kinesiology
  degrees:
    - B.S.
    - SPT
- id: CAK
  number: 2
  name: 
    given: Chloë
    family: Kerstein
  email: "Chloekerst@gmail.com"
  url: "https://nateyomo.github.io/Yomogida-Kerstein-Lab/about.html#cak"
  affiliation:
    - Doctor of Physical Therapy
    - B.A. in Neuroscience
  degrees:
    - B.S.
    - SPT
publisher: Yomogida-Kerstein Laboratory

website:
  twitter-card:
    creator: "@NateYomogida and @Chloe_Kerstein"
    site: "@YomoKerstLab"
  favicon: "/images/brain-favicon.png"
  page-navigation: true
  search:
    keyboard-shortcut: ["?", "H"]
  # title: "YK LAB"
  site-url: https://nateyomo.github.io/Yomogida-Kerstein-Lab
  navbar:
    logo: "/images/square 2 lines mid.svg"
    left:
      - href: index.qmd
        text: Home
      - href: The Archive/archive_index.qmd
        text: Archive
      - href: guide.qmd
        text: Guide
      - href: journal_club_index.qmd
        text: Journal Club
      - about.qmd
      - href: contact.qmd
        text: Contact

citation:
  type: post-weblog
appendix-cite-as: display

bibliography: The Archive/Bibliography/yk_lab_bibliography.bib
csl: The Archive/Bibliography/american-medical-association.csl

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: left
    number-sections: false
    tbl-cap-location: top
    theme:
      light: cosmo
      dark: darkly
    mainfont: helvetica
    fontsize: 16px
    css: styles.css
  # pdf:
  #   pdf-engine: wkhtmltopdf  # Specify wkhtmltopdf as the PDF engine
  #   embed-resources: true  # Optionally embed images, CSS, etc.
  #   toc: true  # Table of contents in PDF
  #   number-sections: true
  #   mainfont: helvetica
  #   fontsize: 14px
  #   geometry: "0.5in"
  # html-pdf:
  #   html:
  #     toc: true
  #     toc-title: Contents
  #     toc-location: right
  #     number-sections: false
  #     tbl-cap-location: top
  #     theme:
  #       light: cosmo
  #       dark: darkly
  #     mainfont: helvetica
  #     fontsize: 14px
  #     css: styles.css
  #   pdf:
  #     toc: true
  #     number-sections: true
  #     link-citations: true
  #     link-bibliography: true
  #     error: true
  #     documentclass: article
