---
Title: Golf
---

# Golf swing

A study found that amateurs use 90% peak muscle activity whereas professionals use 80% peak muscle activity @mchardyGolfInjuriesReview2006.
This is something that should be avoided since it causes amateurs to place excessive load on the lumbar spine @mchardyGolfInjuriesReview2006.

# Injuries
[See "Golf Injuries"]({{< var ref-golf-injuries.path >}})



# Training

## Pelvic control

- Supine pelvic tilts
- Quadriped pelvic tilts (Cat-cow)
- Resisted pelvic tilts (Resisted cat-cow)


## Pelvic dissasociation

- Standing pelvic dissasociation
    - stand wit hands on a wall 
    - rotate hips/pelvis left and right while keeping head and chest pointed towards the wall
    - This blocks the upper body while the pelvis rotates
- Resisted standing pelvic dissassociation

## Rear leg training

- Lateral pull through on eversion wedge
    - Staggered stance on 
- Med ball skaters to throw
    - Standing in square stance with wall to the left
    - Laterall jump to L foot
    - Laterally jump to R foot
    - Laterally jump to L foot and throw the ball to the Left

## Swing training

- Cross arms and place your hands on your opposite shoulders.
- slightly bend knees and hip hinge so your hips touch the wall behind you
- Keep your head facing down where the ball would be

Part 1: Symmetrical swinging

- Practice rotating left and right
- As you rotate right
    - Feel the left hip leave the wall and the right hip press into the wall
- As you rotate left:
    - Right hip moves away from the wall and the left hip feels the wall
    - Loading into your R foot (pronation)
    - Pushing out of your L foot

Part 2: Asym swing practice

- 

## Rear leg training

- Cross body row step through
    - Start in staggered stance with cable pulling from ground level on ipsilateral side
    - Do not bend the knee more than 90deg at the bottom of the squat, we are looking for tension rather than full knee ROM
    - Rotate contralaterally while standing up
    - You should end with your feet next to eachother standing erect and neutral spine rotation, but you should NOT be in spine extension