---
title: Does Dietary Cholesterol cause heart disease?
---



# History

::: {.callout title="Chaffee"}


Original studies that showed correlation **not** causation between cholesterol and CVD were false and "fraudalent" since they were bought and paid for by the sugar industry

Paid for by the "sugar research foundation" which is now called the "sugar association"
:::


::: {.callout title="Chaffee"}

Chaffee states that the JAMA 2015 article @kearnsSugarIndustryCoronary2016 analyzed the internal memos and documents from the Sugar Research Foundation (SRF) and found that the SRF paid off 3 harvard professors (prof mark, prof ____, and prof ____) to falsify data and make it appear as if cholesterol caused or was correlated with heart disease and exonerating sugar and call it an "empty calorie"

:::



::: {.callout title="Chaffee"}

Prof mark, one of the 3 Harvard profs paid off by the SRF, was made *Head of the USDA*

:::



## 1977

::: {.callout title="chaffee's claim"}
USDA Dietary recommendations to eat less fat/cholesterol 

Paid for by the "sugar research foundation" which is now called the "sugar association
:::




::: {.callout title="chaffee's claim"}
Following Dietary guidelines:

Americans (and some other countries):

- &darr; cholesterol/fat intake by 30%
- &darr; red meat by 33%

- &uarr; Fruits 30%
- &uarr; vegetables 40%
- &uarr; grains x%
- &uarr; sugars x%

:::


::: {.callout title="chaffee's claim"}
X amount of time later:

- Heart disease rates tripled
- Diabetes
- Obesity
- Stroke rates
- Parkinson's disease rates
- Alzheimer's disease
- Autoimmune diseases


- All countries that followed these dietary practices had similar results


Conclusion: You cant say "cholesterol causes heart disease" if you reduce cholesterol and CVD rates increase.
If anything, it demonstrates that cholesterol is protective for heart disease.
:::

::: {.callout title="chaffee's claim"}
Framingham study

- Large 20-30 year study
- One of the cardinal studies in cardiology

The results of the study were **misrepresented** by the *American Heart Assocation (AHA)*.

Original study found that if you decrease your cholesterol by 1mg/deciliter, you *increase* your coronary mortality and total mortality by 11% @framingham.



2 years later, the American Heart Association *fraudulently* claimed "a 1% drop in total cholesterol = 2% drop in CHD risk" citing the *Framingham study*
:::

## 2015

Journal of American Medical Association (JAMA) published a report from UCSF showing that 


# Ancel Keys


::: {.callout title="chaffee's claim"}

- researcher who came up with the recommended daily analyses

:::

::: {.callout title="chaffee's claim"}

Ancel keys was paid off by the sugar industry

:::


::: {.callout title="chaffee's claim"}

**7 nation study**

- Found 7 nations and as you increase amoubnt of cholesterol in the population, you see a parabolic increase in heart disease
- Attempoted to use to show that cholesterol causes heart disease
    - Correlation not causation

Ancel Keys had full data from 23 countries, not just 7.
When looking at all the data, there is **no correlation**.

:::

## Minnesota coronary experiment

- Previously unpublished
- "Every 30 pt dec in cholesterol led to a 22% inc in death rate"

# Correlation studies

::: {.callout title="chaffee's claim"}

In recent studies, involving 100s of thousands of people, half of people with heart attacks have low cholesterol and half have high cholesterol.


Another study 

- similar findings
- Researchers said "you should still "
- 3 years follow-up
    - Study showed that those with low cholesterol had 2x death rate of those with high cholesterol ("bad cholesterol")






:::


# Healthy user bias



