---
title: Diastasis Recti Abdominis (DRA)
---

DRA refers to a split between the left and right rectus abdominis muscles @duttonDuttonOrthopaedicExamination2020.


A DRA, a split  between the two rectus abdominis (RA) muscles to the extent that the linea alba may split under the strain, is common in pre- and postpartum women. 

# Demographics
This is common in pre and postpartem women @duttonDuttonOrthopaedicExamination2020.


<h1>Risk Factors</h1>

Predisposing factors for a DRA in women include obesity, a narrow pelvis, multipara, multiple births, excess uterine fluid, large babies, and weak abdominals prior to pregnancy.131 The separation may develop during the second and third trimesters of pregnancy, during second stage labor and during the postpartum period.131
@duttonDuttonOrthopaedicExamination2020

# Presentation

The DRA can vary from 2-20cm @duttonDuttonOrthopaedicExamination2020 in width and up to the entire length of the recti muscles in length @duttonDuttonOrthopaedicExamination2020.

<h1>Functional limitations</h1>

A DRA can have functional limitations in:

<ol>
    <li>Posture @duttonDuttonOrthopaedicExamination2020</li>
    <li>Trunk stability @duttonDuttonOrthopaedicExamination2020</li>
    <li>Trunk strength @duttonDuttonOrthopaedicExamination2020</li>
    <li></li>
    <li></li>
</ol>

<!-- It is believed that a DRA may hinder the abdominal wall function related to posture, trunk stability and strength, respiration, visceral support, diminished pelvic floor facilitation, and delivery of the fetus. An umbilical hernia may result as well. The DRA is believed to contribute to chronic pelvic and LBP.132 -->


<h1>Examination</h1>


- Precautions
    - Are there surgical precautions?
- Subjective
    - Aggs
    - Eases
    - Activity/participation limitations
- Torso ROM
    - Trunk ext 
    - Flex 
    - Rotation 
    - SB 
- MMTs
    - Ab MMT
- Hip region: Examining the hip region could be relevant since there is a lot of overlapping function between the hips and torso
    - 
- Exercises
    - HF stretch
    - 
    

<h1>Conservative Treatment</h1>

<!-- With regard to conservative treatment, particularly exercises to prevent or reduce DRA, the verdict is inconclusive. A 2018 randomized controlled trial133 that examined the effect of a postpartum training program on the prevalence of DRA in postpartum primiparous women concluded that a weekly, postpartum, supervised exercise program, including strength training of the pelvic floor and abdominal muscles, in addition to daily home training of the PFMs, did not reduce the prevalence of diastasis. In contrast, another 2018 study135 that compared trunk muscle function between women with and without DRA at 1 year postpartum found that women with DRA demonstrated significantly lower trunk muscle rotation torque, and scored lower on the sit-up test than those without DRA @duttonDuttonOrthopaedicExamination2020 -->


<h1>Surgical treatment</h1>