---
title: Muscles of the Back
---
# OIAN
## Suboccipitals

```{python tbl-suboccipital-oian}
#| label: tbl-suboccipital-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Suboccipital Muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['suboccipital_muscle_group']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

## Prevertebral Muscles

- [Longus capitis]({{< var ref-longus-capitis.path >}})
- [Longus Colli Cervicis]({{< var ref-longus-colli-cervicis.path >}})
- [Rectus Capitis anterior]({{< var ref-rectus-capitis-anterior.path >}})
- [Rectus Capitis Lateralis]({{< var ref-rectus-capitis-lateralis.path >}})

```{python tbl-prevertebral-oian}
#| label: tbl-prevertebral-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Prevertebral Muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['prevertebral_muscle_group']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```



## Superficial intrinsic back Muscles

- [Serratus posterior superior]({{< var ref-serratus-posterior-superior.path >}})
- [Serratus posterior inferior]({{< var ref-serratus-posterior-inferior.path >}})
- [Splenius capitis]({{< var ref-splenius-capitis.path >}})
- [Splenius cervicis]({{< var ref-splenius-cervicis.path >}})


```{python tbl-superficial-intrinsic-back-oian}
#| label: tbl-superficial-intrinsic-back-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Superficial Intrinsic Back Muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['intrinsic_back_muscles_superficial']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

## Intermediate intrinsic back muscles (Erector Spinae)

::: {.columns}
::: {.column}
Iliocostalis

- [Iliocostalis Cervicis]({{< var ref-iliocostalis-cervicis.path >}})
- [Iliocostalis Thoracis]({{< var ref-iliocostalis-thoracis.path >}})
- [Iliocostalis lumborum]({{< var ref-iliocostalis-lumborum.path >}})

:::
::: {.column}

[**Longissimus**]({{< var ref-longissimus-muscles.path >}})

- [Longissimus Capitis]({{< var ref-longissimus-capitis.path >}})
- [Longissimus Cervicis]({{< var ref-longissimus-cervicis.path >}})
- [Longissimus Thoracis]({{< var ref-longissimus-thoracis.path >}})

:::
::: {.column}

**Spinalis**

- [Spinalis Cervicis]({{< var ref-spinalis-cervicis.path >}})
- [Spinalis Thoracis]({{< var ref-spinalis-thoracis.path >}})

:::
:::




```{python tbl-erector-spinae-oian}
#| label: tbl-erector-spinae-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Intermediate intrinsic back muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['erector_spinae_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


## Transversospinalis Muscles 

- [Rotatores Breves]({{< var ref-rotatores-breves.path >}})
- [Rotatores Longi]({{< var ref-rotatores-longi.path >}})
- [Multifidi]({{< var ref-multifidi.path >}})
- [Semispinalis Capitis]({{< var ref-semispinalis-capitis.path >}})
- [Semispinalis Cervicis]({{< var ref-semispinalis-cervicis.path >}})
- [Semispinalis Thoracis]({{< var ref-semispinalis-thoracis.path >}})

```{python tbl-transversospinalis-oian}
#| label: tbl-transversospinalis-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Transversospinalis muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['transversospinalis_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


## Deep Segmental Back Muscles 

- [Interspinales Cervicis]({{< var ref-interspinales-cervicis.path >}})
- [Interspinales Lumbora]({{< var ref-interspinales-lumbora.path >}})

```{python tbl-deep-segmental-back-oian}
#| label: tbl-deep-segmental-back-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Transversospinalis muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'functional_group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['deep_segmental_back_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


# Lumbar spine muscles


For the lumbar spine, we will organize the muscles based on depth (superficial &rarr; deep) as well as location from midline (medial &rarr; lateral).


## Palpation

### Prone

- vertebra
    - SPs
    - spacing
    - rotation
    - Depth
- 