---
title: 3D Calf Stretch
---


The *3dimensional calf stretch* is an exercise inspired by the Gray Institute @grayinstituteFunctionalTechniques.

Start in a split stance facing a wall with heels on the ground.
The rear leg  is considered "ipsilateral" since this side will experience the calf stretch and its knee should stay more extended.
The lead leg will be the contralateral leg and the knee will be slightly bent.

Internally rotate the ipsilateral leg so the toes are pointing medially.

Next we will perform 3 sets of movements to stretch the calf in the sagittal, frontal, and transverse planes.

# Sagittal plane

The calf can be stretched in the sagittal plane by stepping forwards and backwards with the contralateral leg.
Stepping forward will result in hip extension of the ipsilateral side and dorsiflexion (if the heel stays on the ground).


Stepping backwards with the contralateral leg will move the ipsilateral hip into flexion and move the ipsilateral foot into more plantarflexion.


# Frontal plane

Start with the contralateral leg forward.
Step medially with the contralateral leg, to create ipsilateral hip adduction and ipsilateral ankle eversion.
Step laterally with the contralateral leg to create ipsilateral hip abduction and ipsilateral ankle inversion.

::: {.callout-note}
Since the contralateral leg is in the "lead" or anterior, this will cause the ipsilateral (rear) lower extremity to remain in dorsiflexion throughout the movement.
:::


# Transverse plane

Move the contralateral leg forward, medial, and rotate the foot medially to create ipsilateral hip internal rotation and therefore relative TFJ IR.
Move the contralateral leg posterior, lateral, and rotate the foot laterally to create relative ipsilateral hip ER and relative ipsilateral TFJ ER.

# Progressions

You can use the ipsilateral knee as a driver to start, but can progress to using the contralateral leg as a driver to make it more difficult.