---
title: 3D Hip Flexor Stretch
---


The 3dimensional hip flexor stretch is an exercise inspired by the Gray Institute @grayinstituteFunctionalTechniques.

Start in a split stance with the lead (contralateral) leg elevated on a box.
The rear leg is considered "ipsilateral" since this is the set of hip flexors we are targeting with this stretch.
Internally rotate the ipsilateral leg so the toes are pointing medially.


Next we will perform 3 sets of movements to stretch the hip flexors in the sagittal, frontal, and transverse planes.


# Sagittal plane

To stretch the hip flexors in the sagittal plane, we will use momentum and swing the arms into extension, the core into flexion, and the hips into flexion.


Then we will move in the opposite direction with the arms leading.
This will end with the arms in full flexion, the trunk in extension, and the hips in extension which will place a stretch on the hip flexors in the sagittal plane.

# Frontal Plane

To stretch the hip flexors in the frontal plane, we will start with our arms raised above our heads.
We will swing our arms towards the ipsilateral side, resultibng in ipsilateral sidebend, and hip abduction.

Then we will move the opposite way and swing our arms to the contralateral side, resulting in contralateral sidebend, and hip adduction of the ipsilateral hip.


# Transverse plane

Start with your arms flexed to 90&deg; in front of you.
Use your arms as a driver to rotate contralaterally.
A chain reaction will occur that results in trunk contralateral rotation and external rotation of the ipsilateral hip.

Move the opposite way, to create trunk ipsilateral rotation and internal rotation of the ipsilateral hip.