---
title: Tinel's Sign
subtitle: Special test of neuropathy
---

# Carpal Tunnel {#carpal-tunnel}

"The Tinel test is used to assist in the diagnosis of CTS. The area over the median nerve is tapped gently at the anterior (palmar) surface of the wrist (Fig. 18-62). If this produces tingling in the median nerve distribution, then the test is positive. Variations exist among studies on the location and number of taps necessary to elicit a positive response, and in some studies the test is performed by tapping the median nerve in 20 degrees of wrist extension, while others tap along the path of the median nerve up to where the median nerve enters the carpal tunnel." @duttonDuttonOrthopaedicExamination2020

# Cubital tunnel syndrome

# Radial nerve entrapment

# Tarsal tunnel syndrome

# Superficial peroneal neuropathy

# Brachial Plexus Version {#brachial-plexus}

- AKA: Supraclavicular pressure test
- Tests if the brachial plexus is compromised in the [interscalene triangle]({{< var ref-interscalene-triangle.path >}}) @hooperPart1ThoracicOutletSyndrome2010

## Technique
- Patient is seated @duttonDuttonOrthopaedicExamination2020
- Ask the pt to to SB neck contralaterally (to uninvolved side) @duttonDuttonOrthopaedicExamination2020
- Clinician taps or squeezes trunks of brachial plexus using fingers

## Interpretation

- Local pain @duttonDuttonOrthopaedicExamination2020
    - Indicates cervical plexus lesion @duttonDuttonOrthopaedicExamination2020
- Tingling along one of the trunks: @duttonDuttonOrthopaedicExamination2020
    Indicates: Compression/neuroma of one or more trunks of brachial plexus @duttonDuttonOrthopaedicExamination2020



