---
title: Scapula (Bone)
---



# Osteologic features {#osteologic-features}

- Angles
    - [Superior angle](#superior-angle)
    - [Lateral angle](#lateral-angle)
    - [Inferior angle](#inferior-angle)
- Borders
    - [Superior border](#superior-border)
    - [Medial (vertebral) border](#medial-border)
    - [Lateral (axillary) border](#lateral-border)
- [Supraspinous fossa](#supraspinous-fossa)
- [Infraspinous fossa](#infraspinous-fossa)
- [Spine of scapula](#spine-of-scapula)
- [Root of the spine](#root-of-spine)
- [Acromion](#acromion)
- [Clavicular facet](#clavicular-facet)
- [Glenoid fossa](#glenoid)
- Supraglenoid tubercle
- [Infraglenoid tubercles](#infraglenoid-tubercle)
- [Coracoid process](#coracoid-process)
- [Subscapular fossa](#subscapular-fossa)

## Superior angle {#superior-angle}

## Lateral angle {#lateral-angle}

## Inferior angle {#inferior-angle}

## Superior border {#superior-border}

One of the borders of the [thoracic outlet]({{< var ref-thoracic-outlet.path >}}) @duttonDuttonOrthopaedicExamination2020

## Medial (vertebral) border {#medial-border}

## Lateral (axillary) border {#lateral-border}

## Supraspinous fossa {#supraspinous-fossa}


## Infraspinous fossa {#infraspinous-fossa}

## Spine of Scapula {#spine-of-scapula}

"The spine of the scapula provides a continuous line of attachments for the supporting trapezius muscle along its upper border, whereas the deltoid muscle, which suspends the humerus, gains origin from its lower border." @duttonDuttonOrthopaedicExamination2020 

## Root of the Spine of the Scapula {#root-of-spine}

## Acromion {#acromion}

- Part of the [Acromioclavicular joint]({{< var ref-acromioclavicular-joint.path >}})

"A prominent feature of the scapula is the large overhanging acromion (see Fig. 16-3), which, along with the coracoacromial ligament and the previously mentioned labrum, functionally enlarges the G-H socket. The position of the acromion also places the deltoid muscle in a dominant position to provide muscular support during elevation of the arm. The morphology of the acromion is variable with three types having been described—(1) a relatively flat undersurface (Type I), (2) a slightly convex undersurface (Type II), and (3) a hooked shape (Type III), with a 2018 study finding that individuals with a type III acromion had almost three times greater odds for an RTC tear as compared to those with a type I or II, concluding that a larger acromial index is associated with a greater likelihood of an RTC tear.9 This despite an earlier study in 2011 that concluded that the type of acromion was not found to have an important role in the etiology of chronic impingement syndrome.10" @duttonDuttonOrthopaedicExamination2020 

## Clavicular facet {#clavicular-facet}

## Glenoid fossa {#glenoid-fossa}

## Supraglenoid tubercle {#supraglenoid-tubercle}

## Infraglenoid tubercle {#infraglenoid-tubercle}


## Coracoid process {#coracoid-process}

"The coracoid process (see Fig. 16-3) projects forward like a crow’s beak, for which it is named. This forward position provides an efficient lever whereby the small pectoralis muscle can help to stabilize the scapula. In addition, the process serves as a point of origin for the coracobrachialis and the short head of the biceps muscle" @duttonDuttonOrthopaedicExamination2020

## Subscapular fossa of scapula {#subscapular-fossa}