---
title: Long Sit Exercise
---

<!-- p107 @jonesProjectPhysicalTherapy2025 -->

We define a "Wall sit" differently from what you would think of at a commercial gym @jonesProjectPhysicalTherapy2025.
The movement most people think of where you are on your feet and holding a squat position against a wall, we refer to as a "wall squat."


# Wall sit 

- Sitting on a stool with back supported against the wall

- Regression
    - Standing (&darr; requisite hip flexion mobility) 
- LE Progression
    - Sagittal progression
        - Forward reach
        - Sit (&uarr; stability)
        - Long wall sit (&uarr; mobility)
        - Long sit (&uarr; mobility, &uarr; stability)
    - Transverse progression: Rotation (&uarr; dynamic)
    - Frontal progression: Sidebend
- UE Progression
    - Shoulder T/W/WER

# Sit


Statically sitting on a bench/stool with knees bent.


- Regression
    - Wall sit 
- LE Progression
    - Sagittal progression
        - Forward reach
        - Long wall sit (&uarr; mobility, &darr; stability)
        - Long sit (&uarr; mobility, &uarr; stability)
    - Transverse progression: Rotation (&uarr; dynamic)
    - Frontal progression: Sidebend
- UE Progression
    - Shoulder T/W/WER


# Long Wall sit
## Purpose

"Wall sitting is a supportive hip hinging positional challenge between the trunk, pelvis, and lower extremity active range of motion. Using the wall and floor as feedback provides groundwork for postural progression" @jonesProjectPhysicalTherapy2025

## Position

- The pelvis aligns vertically with the trunk and the hips completely fill the crease between the wall and floor @jonesProjectPhysicalTherapy2025
- Legs 
    - Create a "V" by abducting each leg so the feet are shoulder width apart @jonesProjectFoundations2025.
    - Straighten the knees against the floor *without* hyperextension
    - Dorsiflex the toes: Draw the toes towards you
- Trunk: Activate the abdominals by drawing your naval towards your spine *without* losing the anterior pelvic tilt
- Shoulders: Retract and depress the shoulders
- Neck: Look forward and chin tuck so your head is against the wall

## Keys and Focus

"Proper leg position is typically a challenge on active range. Quadriceps activation is a good marker for full leg contact. The opposite to leg range limits is excessive range and/or the ability to do the splits in the sitting support position. Remember the goal of leg position is a standard "V" leg position, **not** "wider the better". the 2nd goal is getting the trunk flat against the wall. Activating the trunk includes squeezing the abdomen and shoulder blades to create as much contact with the wall throughout the trunk and not letting one region compensate for the other. Abdomen setting for stabilization is not mimicking a crunch, but a combination squeezing the entire abdominal wall into an active lower trunk, while maintaining a vertical pelvis. Using chin tucks to level out the head position and center the head over the torso will assist in achiving postural goals. Mastery of wall sit technique is not a single session goal but a process over time and requires assessment and proper cueing for success. @jonesProjectPhysicalTherapy2025

::: {.callout-tip title="Translation"}
"Although wall sitting is a great warm-up tool and assessment for hip hinge alignment, it is not typically a functional position, but does provide sitting posture cueing. Any feedback to the individual for finding recruitment and working on postural adjustments is a benefit. Use each verbal cue and adjustment as alignment between you and the client. Understand pelvic adjustments without the floor or wall will be harder to feel spatially, any previous discussions or adjustments might come in handy" @jonesProjectPhysicalTherapy2025
:::