---
title: Squat Foundational Exercise
---


# Assessment


- Bar path
- Arch control
- Knee and hip timing

## Bar Path

*Bar path* refers to the line that the bar moves when viewed in the sagittal plane.
The bar should move *perpendicular* to the floor.


## Timing

The knee and hip should start their descent at the same time and reach the end at the same time @jonesProjectPhysicalTherapy2025.




# Knee

The knee is considered a *reactive joint*: it becomes malaligned as a reaction of improper hip or foot/ankle mechanics @jonesProjectPhysicalTherapy2025.
However, the knee can control its own *sequencing speed*, thus can change how quickly it moves through its range relative to the other joints.

Individuals with knee pain generally ease their symptoms by keeping the knees directly above the ankles to minimize knee extensor torque.
In order to keep the knees in this position, the body compensate for the lack of dorsiflexion and knee flexion ROM @jonesProjectPhysicalTherapy2025.
This will result in a high thigh angle and the trunk moving towards parallel @jonesProjectPhysicalTherapy2025.

# Hips

The hips are "reluctant team members" and if they are not performing their job as shock absorbers, this responsibility can be pushed onto the knees and low back @jonesProjectPhysicalTherapy2025.





# Compensations

Individuals will attempt to compensate in order to find stability @jonesProjectPhysicalTherapy2025.
Leaning on instability is *not* stability @jonesProjectPhysicalTherapy2025.

For example, a common compensation while squating is toeing out (hip ER) and flattening the arch (pronation) @jonesProjectPhysicalTherapy2025.
This creates a stable surface, but at the cost of alignment of the lower leg, knee, and upper leg since these must counter the foot position @jonesProjectPhysicalTherapy2025.
Malalignment can result in excessive torsion through these regions.

## Back Pain

