---
title: Interspinales Muscle
---


```{python tbl-interspinales-muscles-oian}
#| label: tbl-interspinales-muscles-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['interspinales_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

# Overview

The *interspinales muscle* exists throughout the spine, but is separated into two sections: [*interspinalis cervicis*](#interspinales-cervicis) and [*interspinalis lumbora*](#interspinales-lumbora) since these two regions are where the muscle is most defined @jonesProjectFoundations2025.


# Interspinales Cervicis
## Origin {#origin}
C1-C7: SP of inferiorly adjacent vertebrae @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
C1-C7: SP of superiorly adjacent vertebrae @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. (Posterior Rami)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}
Extends cervical and Lumbar spines @gilroyAtlasAnatomy2020

# Interspinales Lumbora
## Origin {#origin}
L1-L5: SP of inferiorly adjacent vertebrae @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
L1-L5: SP of superiorly adjacent vertebrae @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. (Posterior Rami)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}

- **BIL**: Stabilizes and extends cervical and lumbar vertebrae @gilroyAtlasAnatomy2020
- **UNIL**: I/L SB cervical and lumbar spines @gilroyAtlasAnatomy2020

# Practical function

Since these muscles can act to extend each vertebrae individually and how close they run to the intervertebral joint, these muscles play a role in segmental stabilization of the spine @jonesProjectFoundations2025.