---
title: Modified Ashworth Scale (MAS)
subtitle: Measure of Static Response of muscle tone
---



| Score | Criteria |
|-|-|
| 0 | No increase in muscle tone |
| 1 | Slight increase in muscle tone manifasted by *catch and release* |
| 1+ | A slight increase in muscle tone manifested by *catch* followed by minimial resistance through remaining range |
| 2 | A more apparent increase in muscle tone during movement, but the affected body part is easily moved |
| 3 | A *considerable* increase in tone, passive movement is *difficult* |
| 4 | The affected body part is *rigid* in a certain position, full passive movement is *not attainable* |
: Modified Ashworth Scale @DynamicNeurologicalStabilizationClinicalRehabilitation2014 {.striped}



"The Ashworth Scale and the Modified Ashworth Scale consist of a subjective clinical assessment of resistance to passive stretch. For example, the evaluator passively stretches the biceps and assesses whether the resistance to stretch is normal or greater than normal. The Ashworth Scale range is 0 (no resistance to passive stretch) to 4 (the limb is rigid in flexion or extension). The Modified Ashworth Scale adds a 1+ score; the scales are otherwise the same. No direct relationship exists between changes in the Ashworth score and improvements or declines in functional activity. High scores on the Ashworth Scale are associated with contracture (structural shortening of muscle), not excess neural input eliciting muscle contraction (i.e., not hyperreflexia or excess upper motor neuron drive).13 Ashworth scores assigned by an experienced neurologist correlate poorly with electromyographic recording during passive stretching using a motor that controls the velocity of muscle stretch.14 The reliability of the Ashworth Scale and Modified Ashworth Scale are inadequate to recommend their use as a measure of spasticity.15,16 Because these scales are unreliable and because the scales cannot distinguish between contracture and excess neural input to muscles (see Chapter 14), the scales are not useful for clinical decision making.13,16" @lundy-ekmanNeuroscienceFundamentalsRehabilitation2023