---
title: Occipital Neuralgia
---






# Anatomy

- Pathway
    - Leaves the spinal column through the arch of the atlas and the axis
    - Travels toward the area of C2/3 facet joint inferolaterally and then curves around the inferior oblique capitis mm to ascend toward the occiput deep to the semispinalis capitis mm
    - Pierces either the tendon of the trap or between then trap and semispinalis to reach the occipital area
- Formed by posterior division of CN II 
- Greater  occipital nerve is the largest purely afferent nerve in the body

# Innervation {#innervation}
Innervates the post skull from suboccipital area to the vertex

# Associated pathologies

- Cervicogenic headache



# Dysfunction


During a violent forced extension, the posterior arch of the [atlas (C1)]({{< var ref-c1-bone.path >}}) can be caught between the [occipital bone]({{< var ref-occipital-bone.path >}}) and the [*posterior arch* of the axis (C2)]({{< var ref-c2-bone.path >}}) resulting in a "nutcracker" mechanism which fractures the [atlas]({{< var ref-c1-bone.path >}}) @jonesProjectFoundations2025.