---
title: Dynamic Gait Index (DGI)
---

The DGI has become outdated and replaced by its improved successor the [Functional Gait Assessment (FGA)]({{< var ref-functional-gait-assessment.path >}})




# Form

- ~15 minutes
- Scored 0-3 with a max score of 24points
- Higher score is better

## 1 Level Gait

Instructions: Walk at your normal speed from here to the next mark (20’)


| Grade | Level | Criteria |
|-|-|-|
| 3 | Normal | Walks 20' unassisted at a good speed, with a normal gait pattern, and no imbalance |
| 2 | Mild | Walks 20’, uses assistive devices, slower speed, mild gait deviations |
| 1 | Moderate | Walks 20’, slow speed, abnormal gait pattern, evidence for imbalance |
| 0 | Severe | Cannot walk 20’ without assistance, severe gait deviations or imbalance |
*Mark the lowest category that applies*

## 2 Change in Gait speed

<!-- Instructions: Begin walking at your normal pace (for 5’), when I tell you “go,” walk as fast as you can (for
5’). When I tell you “slow,” walk as slowly as you can (for 5’).
Grading: Mark the lowest category that applies.
(3) Normal: Able to smoothly change walking speed without loss of balance or gait deviation. Shows a
significant difference in walking speeds between normal, fast and slow speeds.
(2) Mild Impairment: Is able to change speed but demonstrates mild gait deviations, or not gait
deviations but unable to achieve a significant change in velocity, or uses an assistive device.
(1) Moderate Impairment: Makes only minor adjustments to walking speed, or accomplishes a change
in speed with significant gait deviations, or changes speed but has significant gait deviations, or
changes speed but loses balance but is able to recover and continue walking.
(0) Severe Impairment: Cannot change speeds, or loses balance and has to reach for wall or be caught. -->

## 3 Gait with Horizontal head turns

<!-- Instructions: Begin walking at your normal pace. When I tell you to “look right,” keep walking straight, but
turn your head to the right. Keep looking to the right until I tell you, “look left,” then keep walking straight
and turn your head to the left. Keep your head to the left until I tell you “look straight,“ then keep walking
straight, but return your head to the center.
Grading: Mark the lowest category that applies.
(3) Normal: Performs head turns smoothly with no change in gait.
(2) Mild Impairment: Performs head turns smoothly with slight change in gait velocity, i.e., minor
disruption to smooth gait path or uses walking aid.
(1) Moderate Impairment: Performs head turns with moderate change in gait velocity, slows down,
staggers but recovers, can continue to walk.
(0) Severe Impairment: Performs task with severe disruption of gait, i.e., staggers
 outside 15” path, loses balance, stops, reaches for wall. -->

## 4 Gait with Vertical Head Turns

<!-- Instructions: Begin walking at your normal pace. When I tell you to “look up,” keep walking straight, but tip
your head up. Keep looking up until I tell you, “look down,” then keep walking straight and tip your head
down. Keep your head down until I tell you “look straight,“ then keep walking straight, but return your head
to the center.
Grading: Mark the lowest category that applies.
(3) Normal: Performs head turns smoothly with no change in gait.
(2) Mild Impairment: Performs head turns smoothly with slight change in gait velocity, i.e., minor
disruption to smooth gait path or uses walking aid.
(1) Moderate Impairment: Performs head turns with moderate change in gait velocity, slows down,
staggers but recovers, can continue to walk.
(0) Severe Impairment: Performs task with severe disruption of gait, i.e., staggers
 outside 15” path, loses balance, stops, reaches for wall. -->

## 5 Gait to Pivot Turn

<!-- Instructions: Begin walking at your normal pace. When I tell you, “turn and stop,” turn as quickly as you can
to face the opposite direction and stop.
Grading: Mark the lowest category that applies.
(3) Normal: Pivot turns safely within 3 seconds and stops quickly with no loss of balance.
(2) Mild Impairment: Pivot turns safely in > 3 seconds and stops with no loss of balance.
(1) Moderate Impairment: Turns slowly, requires verbal cueing, requires several small steps to catch
balance following turn and stop.
(0) Severe Impairment: Cannot turn safely, requires assistance to turn and stop. -->

## 6 Step over obstacle

<!-- Instructions: Begin walking at your normal speed. When you come to the shoebox, step over it, not around it,
and keep walking.
Grading: Mark the lowest category that applies.
(3) Normal: Is able to step over the box without changing gait speed, no evidence of imbalance.
(2) Mild Impairment: Is able to step over box, but must slow down and adjust steps to clear box safely.
(1) Moderate Impairment: Is able to step over box but must stop, then step over. May require verbal
cueing.
(0) Severe Impairment: Cannot perform without assistance. -->

## 7 Step Around Obstacle

<!-- Instructions: Begin walking at normal speed. When you come to the first cone (about 6’ away), walk around
the right side of it. When you come to the second cone (6’ past first cone), walk around it to the left.
Grading: Mark the lowest category that applies.
(3) Normal: Is able to walk around cones safely without changing gait speed; no evidence of
imbalance.
(2) Mild Impairment: Is able to step around both cones, but must slow down and adjust steps to clear
cones.
(1) Moderate Impairment: Is able to clear cones but must significantly slow, speed to accomplish task,
or requires verbal cueing.
(0) Severe Impairment: Unable to clear cones, walks into one or both cones, or requires physical
assistance. -->

## 8 Stairs

<!-- Instructions: Walk up these stairs as you would at home, i.e., using the railing if necessary. At the top, turn
around and walk down.
Grading: Mark the lowest category that applies.
(3) Normal: Alternating feet, no rail.
(2) Mild Impairment: Alternating feet, must use rail.
(1) Moderate Impairment: Two feet to a stair, must use rail.
(0) Severe Impairment: Cannot do safely. -->

# Interpretation

- &le; 19/24 &rarr; Fall risk in elderly
- &gt; 22/24 &rarr; Safe ambulator

# Similar Tests

::: {.callout-note}
It should be noted that the DGI does *not* assess backwards walking
:::

- [FGA]({{< var ref-functional-gait-assessment.path >}}): 
    - Backwards walking
    - EC
- [Mini-Best test]({{< var ref-mini-bestest.path >}})
    - EC