---
title: "Hoehn and Yahr Scale"
---

- The Hoehn & Yahr (H&Y) system for grading severity of Parkinson’s disease (PD) symptoms uses a scale of 1 to 5 to evaluate the extent of patients’ clinical disability
- HY scale has remained the most commonly and most widely used scale to describe severity of PD worldwide @goetzMovementDisorderSociety2004.

# Scoring

::: {#tbl-standard-vs-modified}

<table class="basic-table">
  <thead>
    <tr>
      <th>Stage</th>
      <th>Hoehn and Yahr Scale</th>
      <th>Modified Hoehn and Yahr Scale</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Unilateral involvement only usually with minimal or no functional disability</td>
      <td>Unilateral involvement only</td>
    </tr>
    <tr>
      <td>1.5</td>
      <td>-</td>
      <td>Unilateral and axial involvement</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Bilateral or midline involvement without impairment of balance</td>
      <td>Bilateral involvement without impairment of balance</td>
    </tr>
    <tr>
      <td>2.5</td>
      <td>-</td>
      <td>Mild bilateral disease with recovery on pull test</td>
    </tr>
    <tr>
      <td>3</td>
      <td>Bilateral disease: mild to moderate disability with impaired postural reflexes; physically independent</td>
      <td>Mild to moderate bilateral disease; some postural instability; physically independent</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Severely disabling disease; still able to walk or stand unassisted</td>
      <td>Severe disability; still able to walk or stand unassisted</td>
    </tr>
    <tr>
      <td>5</td>
      <td>Confinement to bed or wheelchair unless aided</td>
      <td>Wheelchair bound or bedridden unless aided</td>
    </tr>
  </tbody>
</table>


:::




# Interpretation

- Higher H&Y scores have been linked with a more rapid cognitive decline in PD patients @modestinoHoehnYahrStaging2018.
- Generally, a higher H&Y scores correlates with poorer quality of life @modestinoHoehnYahrStaging2018. 

:::{layout-ncol="2"}

## Stages 1-3

- Considered "minimally disabled"
- Still able to lead independent lives

## Stage 4-5

- Considered "severely disabled"
- Motor symptom severity has been associated with various neurocognitive issues:
    - Dementia
    - Depression
    - Hallucinations
:::



# Strengths

see @goetzMovementDisorderSociety2004

# Considerations

- Dual tasking can 