---
title: Pelvis MSK
subtitle: Musculoskeletal Overview
---

::: {.callout title="Reading list"}

- Examination
    - Ch16 Screening the Sacrum, Sacroiliac, and Pelvis @heickGoodmanSnyderDifferential2023
    
:::


# Muscular considerations

- Low back stabilizers
- Glutes
- Pelvic floor



# Stabilization

## AP stabilization

### PPT

- tightens ilio-femoral lig. @jonesProjectFoundations2025

### APT

- 



# Examination

- Fortin's Test

## Provacative tests

- Gaenslen's

## ROM

- Hip ROM
    - One-Leg Standing (OLS) Test @duttonDuttonOrthopaedicExamination2020
- Lumbopelvic ROM
    - Forward Bending @duttonDuttonOrthopaedicExamination2020 
    - Backward Bending @duttonDuttonOrthopaedicExamination2020 
    - Side Bending @duttonDuttonOrthopaedicExamination2020 


## MM tests

- Thomas Test?


## Functional tests

- Forward Bending (Functional test of the pelvis) p.1430 @duttonDuttonOrthopaedicExamination2020 
- Functional Squat (Functional test of the pelvis) p.1430 @duttonDuttonOrthopaedicExamination2020 
- Alternating Unilateral Standing p.1431 @duttonDuttonOrthopaedicExamination2020 

## Form Closure

p.1431 @duttonDuttonOrthopaedicExamination2020 

## Postural Assessment

- Compare R vs L ASIS
- Compare ASIS vs PSIS
- Compare R vs L PSIS


- Stork Test


# Pain

::: {.callout title="Reading list"}

- Ch53 Clinical Considerations of Trunk and Pelvic Pain @donnellyTravellSimonsSimons2019

:::



# Examination
## Gold standard

The gold standard for diagnosing sacroiliac pathologies is a diagnostic nerve block


## Anthropometry 

- Leg length discrepency (LLD)

## Special Tests

- Laslett cluster
    - Distraction
    - Compression
    - Thigh Thrust
    - Sacral Thrust
    - Gaenslen's
- Fortin’s Finger Test

- CCF (by chloe and keegan in video)

## Psychometrics

# Manual Interventions

- SIJ HVLAT (macki arroyo)

# Rehabilitation