---
title: Thorac MSK
subtitle: A Musculoskeletal Overview
---

# Osteology

The thoracic spine consists of 12 vertebrae (T1-12) that sit between the vertebrae of the cervical spine and lumbar spine.

The thoracic vertebrae are larger than cervical but smaller than lumbar vertebrae.
As you descend the vertebral column, the thoracic vertebrae increase in size in order to support more and more BW% @jonesProjectFoundations2025.


Ribs 2-9 insert between 2 vertebrae at the superior costal facet and inferior costal facet.
Ribs 1, 10, 11, and 12 insert on a *single* vertebrae at the *complete costal facet* @jonesProjectFoundations2025.


Vertebrae T1-T10 have *transverse costal facets* which is an articulation between the transverse process and the tubercle of the adjacent rib.
T11 and T12 lack a transverse costal facet since ribs 11 and 12 do not have tubercles @jonesProjectFoundations2025.

Ribs 11-12 are floating ribs and lack cartilaginous attachment to the sternum *and* tubercles @jonesProjectFoundations2025.


At the thoracic spine, the spinous processes are angled sharply inferiorly.

Thus the SPs vary in how far the SP is compared to the vertebral body:

- T1-T3 = at the level
- T4-T6 = Half segment below
- T7-T9 = Full segment below
- T10 = Full segment below
- T11 = Half segment below
- T12 = At the level





# Kyphosis

Thoracic kyphosis can reduce the space available to the lungs, resulting in limitations in deep breathing @neumannKinesiologyMusculoskeletalSystem2017.

# Osteokinematics

T-spine can move in flexion/extension, lateral flexion, and rotation.
Assessments of each movement can be found [here](#rom).

## Flexion 

- Total: 20-45° @duttonDuttonOrthopaedicExamination2020
    - Upper T/S: 4-5° @duttonDuttonOrthopaedicExamination2020
    - Middle T/S: 6-8° @duttonDuttonOrthopaedicExamination2020
    - Lower T/S: 9-15° @duttonDuttonOrthopaedicExamination2020

## Extension 

- Total: 15-20° @duttonDuttonOrthopaedicExamination2020
- Segment: 1-2° @duttonDuttonOrthopaedicExamination2020
- *Compression @ center @duttonDuttonOrthopaedicExamination2020

:::{.callout-note collapse="true"}
# Extension Limitations
:::

## SB (Lateral flexion) @duttonDuttonOrthopaedicExamination2020

- Segment: 3-4° per
- Total: 25-45°
    - Lower segment: 7-9°

:::{.callout-note collapse="true"}
# SB Limitations
SB limited throughout d/t rib stacking @duttonDuttonOrthopaedicExamination2020
:::


## Rotation


- Total: 35-50° @duttonDuttonOrthopaedicExamination2020
- Segments: 
    - Upper: 7° @duttonDuttonOrthopaedicExamination2020
    - Middle: 5° @duttonDuttonOrthopaedicExamination2020
    - Last 2 segments: 2-3° @duttonDuttonOrthopaedicExamination2020


# Arthrokinematics

# T/S Pain
## Referred pain

- Z-joints of the C/S can refer to the thoracic spine

## Acute T/S Pain

- Fracture: 
    - Old (>50) = Minor trauma (hx of osteoporosis or steroid use)
    - Young = Major trauma in younger pop
- Infection: Fever, night sweats, risk factors of inf (wound, etc)
- Tumor: Hx of malignant dx, age > 50 , no improvement w txt, unexplained weight loss, pain at multiple sites, rest, night pain


# T/S Pathologies

- [TOS]({{< var ref-thoracic-outlet.syndrome.path >}})
- Spinal nerve root syndrome— radiculopathy 
- Osteoporosis: (10% of ppl 50 +)
- Chest wall variations
- Kyphotic variations
- Osteoarthritis
- Spinal stenosis


# Rule of 3s

::: {.callout-note}
Oakley CK, Janssen SAK, Pankratz JP, McCumber TL, Treffer KD, Olinger AB. Validity of the Rule of Threes and Anatomical Relationships in the Thoracic Spine. J Am Osteopath Assoc. 2018;118(10):645-653. doi:10.7556/jaoa.2018.143
:::

# Examination

## ROM {#rom}

- T/S spine ROM
    - Measure from T12 to acromion and compare to opposite side
    - Go into quadraped with max L/S flexion to bias T/S rotation

Thoracic ROM can be measured using the [FMS quadriped T-spine rotation](https://www.functionalmovement.com/exercises/30/quadruped_t-spine_rotation)


## TPI ROM
Greg Rose in his TPI course recommends measuring thoracic spine mobility by sitting with ankles crossed and knees together.


# AROM

Rotation

- Open books
- Resisted open books
- Chops


Extension

- Thoracic extension over FR

# Pain

::: {.callout}

- Clinical Considerations of Upper Back Shoulder and Arm Pain @donnellyTravellSimonsSimons2019

:::



# HVLAT

- Cervicothoracic Junction (C7-T3) Lateral Flexion HVLAT in Prone p95 [@dunningSMT1HighVelocityLowAmplitude2018]
- Upper Thoracic (TI-3) AP Extension High Dog' HVLAT in Supine p93 [@dunningSMT1HighVelocityLowAmplitude2018]

<!-- add the rest to the segment pages -->

- Mid-Thoracic (T4-9) AP Extension "Dog' HVLAT in Supine p94 [@dunningSMT1HighVelocityLowAmplitude2018]

- Mid-Thoracic (T4-9) AP Flexion HVLAT in Supine p96 [@dunningSMT1HighVelocityLowAmplitude2018]
- Mid-Thoracic (T2-9) PA Extension HVLAT in Prone p99 [@dunningSMT1HighVelocityLowAmplitude2018]