---
title: Brunnstrom Stages of Recovery
---



:::{#tbl-brunnstrom}

<table class="basic-table">
  <thead>
    <tr>
      <th>Stage</th>
      <th>Hallmark</th>
      <th>Description</th>
      <th>Alternate Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Flaccidity</td>
      <td>No voluntary movement, muscle tone is absent</td>
      <td>Recovery from hemiplegia occurs in a stereotyped sequence of events that begins with a period of flaccidity immediately following the acute episode. No movement of the limbs can be elicited.</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Spasticity begins</td>
      <td>Appearance of basic limb synergies as associated reactions, minimal voluntary movement, spasticity begins</td>
      <td>As recovery begins, the basic limb synergies or some of their components may appear as associated reactions, or minimal voluntary movement responses may be present. At this time, spasticity begins to develop.</td>
    </tr>
    <tr>
      <td>3</td>
      <td>Spasticity Increases</td>
      <td>Voluntary control of synergy patterns, spasticity may become severe</td>
      <td>Thereafter, the patient gains voluntary control of the movement synergies, although full range of all synergy components does not necessarily develop. Spasticity has further increased and may become severe.</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Spasticity declines</td>
      <td>Some movement outside of synergy patterns emerges</td>
      <td>Some movement combinations that do not follow the paths of either synergy are mastered, first with difficulty, then with more ease, and spasticity begins to decline.</td>
    </tr>
    <tr>
      <td>5</td>
      <td>More complex movements</td>
      <td>Synergies lose dominance, more voluntary movement control</td>
      <td>If progress continues, more difficult movement combinations are learned as the basic limb synergies lose their dominance over motor acts.</td>
    </tr>
    <tr>
      <td>6</td>
      <td>Isolated movement</td>
      <td>Spasticity disappears, coordination and movement return toward normal (not all patients reach this stage)</td>
      <td>With the disappearance of spasticity, individual joint movements become possible, and coordination approaches normal. From here on, as the last recovery step, normal motor function is restored, but this last stage is not achieved by all, for the recovery process can plateau at any stage.</td>
    </tr>
    <tr>
      <td>7</td>
      <td>Normal movement</td>
      <td>Normal motor function is restored</td>
      <td></td>
    </tr>
  </tbody>
</table>


Sequential Motor Recovery Stages Following Stroke @fulkOSullivanSchmitzsPhysical2024
:::