---
title: Scaphoid Shift test
subtitle: Carpal instability test
---


"The scaphoid shift maneuver examines the dynamic stability of the wrist, in particular, the integrity of the scapholunate ligament. The patient is positioned in sitting with their elbow in approximately 90 degrees of flexion, the forearm slightly pronated, and the wrist ulnarly deviated. The clinician grasps the wrist from the radial side and stabilizes the scaphoid tubercle with the thumb and the posterior (dorsal) aspect of the scaphoid with the index finger. The clinician uses the other hand to grasp the metacarpals. Starting in ulnar deviation and slight extension, the wrist is moved into radial deviation and slight flexion. As the wrist is brought passively into radial deviation, the normal flexion of the proximal row forces the scaphoid tubercle into an anterior (palmar) direction (into the clinician’s thumb). The clinician attempts to prevent the anterior (palmar) motion of the scaphoid. When the scaphoid is unstable, its proximal pole is forced to sublux posteriorly (dorsally).22 Pain at the posterior (dorsal) wrist or a clunk suggests instability. The results are compared with the other hand. The results from the scaphoid shift test should be used with caution, as the test can be positive in up to one-third of uninjured individuals. One study looked at the movements of the carpal bones during the scaphoid shift test radiographically in 60 wrists and found that pain associated with subluxation of the scaphoid during the shift test is a significant finding, and that radiographic analysis of the test may confirm a positive result when dynamic scaphoid instability is suspected.22" @duttonDuttonOrthopaedicExamination2020