---
title: Triceps Brachi
---

```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'functional_group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['triceps_brachii_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


# Long Head

## Origin {#origin}

Infraglenoid tubercle of scapula @gilroyAtlasAnatomy2020

## Insertion {#insertion}

Olecranon process of Ulna @gilroyAtlasAnatomy2020

## Innervation {#innervation}

[Radial N.]({{< var ref-radial-nerve.path >}}) ([C6]({{< var ref-nerve-root.c6 >}}), [C7]({{< var ref-nerve-root.c7 >}}), [C8]({{< var ref-nerve-root.c8 >}})) @gilroyAtlasAnatomy2020

## Action {#action}

- **Elbow**: Extension @gilroyAtlasAnatomy2020
- **Shoulder**: Extension, Adduction @gilroyAtlasAnatomy2020

# Medial Head

## Origin {#origin}

- Posterior surface of humerus (distal to radial groove) @gilroyAtlasAnatomy2020
- Medial intermuscular septum @gilroyAtlasAnatomy2020


## Insertion {#insertion}

Olecranon process @gilroyAtlasAnatomy2020

## Innervation {#innervation}

[Radial N.]({{< var ref-radial-nerve.path >}}) ([C6]({{< var ref-nerve-root.c6 >}}), [C7]({{< var ref-nerve-root.c7 >}}), [C8]({{< var ref-nerve-root.c8 >}})) @gilroyAtlasAnatomy2020

## Action {#action}

**Elbow**: Extension @gilroyAtlasAnatomy2020

# Lateral Head 

## Origin {#origin}

- Posterior surface of humerus (prox to radial groove) @gilroyAtlasAnatomy2020
- Lateral intermuscular septum @gilroyAtlasAnatomy2020



## Insertion {#insertion}

Olecranon process @gilroyAtlasAnatomy2020

## Innervation {#innervation}

[Radial N.]({{< var ref-radial-nerve.path >}}) ([C6]({{< var ref-nerve-root.c6 >}}), [C7]({{< var ref-nerve-root.c7 >}}), [C8]({{< var ref-nerve-root.c8 >}})) @gilroyAtlasAnatomy2020

## Action {#action}

**Elbow**: Extension @gilroyAtlasAnatomy2020


# Notes


# Triceps Reflex {#reflex}

Triceps reflex can be used to assess C7 nerve root @hongReliabilityDiagnosticAccuracy2022 

