---
title: Triangular Fibrocartilage Complex (TFcC)
---

Connects



# Dysfunction



# Clinical Presentation



## Etiology

## Subjective

- Location of pain


# Examination

:::{layout-ncol="3"}
### Palpation
Palpate at the ulnocarpal joint to palpate the TFCC

:::






# Interventions

## CKC

- Start at table (requires less ROM)
- Progress to wall (requires greater ROM)
- Plank
    - Up/down
    - Bosu
- Pushups
- Crawling

## OKC

- Start before CKC

## Bar

- Hangs
- Scap retractions
- Pull ups
- Archer Pull-ups

## Push-ups

- Wall
- Table
- Normal




# Treatment

## Phases

:::{layout-ncol="3"}
### Stabilization (4-6 weeks)

Restricting motion

### Light Treatment


### End goal (2-3 mo later)

- Pullup
- Pushup
- Dip?
- Stabilization: Performing these on rings or TRX


Table pushups → normal pushups
Wrist circles: resisted wrist circles
Rows w bar bell 
Tricep Dips 
GOOD rom and mobility needed
TRX banded exercises (general wrist strength) 
KB carry bottom up
Farmers carry
Heavy
Kettlebell swings
Crawling


:::

:::{layout-ncol="2"}

## ROM

- PROM
- CKC Stretches (table or wall)

## Mobility

- AAROM
- 

:::

## Strengthening

## Grip Strengthening

- Sand/rice bucket (Purely concentric)
- Dead Hangs (Iso to eccentric)
- Rows (Dynamic Iso)
- Pullups (Dynamic Iso)


## Stabilization

- Bottom's Up KB Carry

## Power


