---
title: Gluteus Medius
---

# Overview

```{python tbl-oian}
#| label: tbl-glute-ed-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'muscle_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['gluteus_medius']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

# Origin {#origin}

Ilium (gluteal surface below the iliac crest between the anterior and posterior gluteal line) @gilroyAtlasAnatomy2020

# Insertion {#insertion}

Greater trochanter of the femur (lateral surface) @gilroyAtlasAnatomy2020

# Innervation {#innervation}

The gluteus maximus muscle is innervated by nerve roots [L4]({{< var ref-nerve-root.l4 >}}), [L5]({{< var ref-nerve-root.l5 >}}), and [S1]({{< var ref-nerve-root.s1 >}}), via the [Superior gluteal nerve]({{< var ref-superior-gluteal-nerve.path >}})  @gilroyAtlasAnatomy2020



# Action {#action}

- Entire muscle: abducts the hip, stabilizes the pelvis in the coronal plane @gilroyAtlasAnatomy2020
- Anterior fibers: flexion and internal rotation @gilroyAtlasAnatomy2020 
- Posterior fibers: extension and external rotation @gilroyAtlasAnatomy2020
    - At &ge;60&deg; hip flexion, the *posterior fibers* of the gluteus minimus switch and produce an *internal rotation* torque @neumannKinesiologyMusculoskeletalSystem2017.



# Overview


# Tests & Measures

- External Derotation Test (gluteus medius tendinopathy)