---
title: Quadratus Femoris Muscle
---

# Overview

```{r}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/gt_oian.R"))

# Example usage
identifier_col <- "muscle_identifier"  # or "group_identifier"
filter_patterns <- "quadratus_femoris"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Quadratus Femoris Muscle"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Origin {#origin}

Lateral border of the ischial tuberosity @gilroyAtlasAnatomy2020

# Insertion {#insertion}

Intertrochanteric crest of the femur @gilroyAtlasAnatomy2020

# Innervation {#innervation}

Sacral plexus Direct Branches ([L5]({{< var ref-nerve-root.l5 >}}), [S1]({{< var ref-nerve-root.s1 >}})) @gilroyAtlasAnatomy2020

# Action {#action}

**Hip**: External rotation @gilroyAtlasAnatomy2020



# Palpation

1. Position the patient in prone @bielTrailGuideBody2019.
1. locate: @bielTrailGuideBody2019.
    1. Posterior aspect of Greater trochanter @bielTrailGuideBody2019.
    1. Ischial tuberosity @bielTrailGuideBody2019.
1. Bisect these two landmarks and place your fingerpads here @bielTrailGuideBody2019.
1. Press firmly *through* the more superficial Gluteus maximus muscle belly @bielTrailGuideBody2019.
1. Strum vertically over the QF muscle belly @bielTrailGuideBody2019.

:::{layout-ncol="2"}

### Passive tension
You can passively tense and slack the quadratus femoris by flexing the knee to 90&deg; then moving between internal rotation (tension) to external rotation (slack), which should cause the quadratus femoris to palpably increase in tension @bielTrailGuideBody2019.

:::