---
title: Iliotibial Band (IT Band)
keywords:
    - Iliotibial band
    - Iliotibial tract
---


Although the glute max and TFL can contract independently, when contracted together, these result in pure abduction @jonesProjectFoundations2025.


"The ITB or tract begins as a wide covering of the superior and lateral aspects of the pelvis and thigh in continuity with the fascia latae (Figs. 20-4 and 19-5). It inserts distal and lateral to the patella at the tubercle of Gerdy on the lateral condyle of the tibia. Anteriorly, it attaches to the lateral border of the patellar. Posteriorly, it is attached to the tendon of the biceps femoris. Laterally, it blends with an aponeurotic expansion from the VL (see Chapter 19)." @duttonDuttonOrthopaedicExamination2020 


"Like the patellar tendon, the ITB can be viewed as a ligament or a tendon. Its location adjacent to the center of rotation of the knee allows it to function as an anterolateral stabilizer of the knee in the frontal plane and to both flex and extend the knee.1 During stationary standing, the primary function of the ITB is to maintain knee and hip extension, providing the thigh muscles an opportunity to rest. While walking or running, the ITB helps maintain flexion of the hip and is a major support of the knee in squatting from full extension until 30 degrees of flexion. In knee flexion greater than 30 degrees, the iliotibial tract becomes a weak knee flexor, as well as an external rotator of the tibia." @duttonDuttonOrthopaedicExamination2020 



# Palpation


    - Follow it proximally as it moves anterolaterally to join the TFL @jones
    - Palpate it posterolaterally as it joins the gluteus maximus proximally
    - Assess the IT band against the femur as moves distally
    - It should feel fibrous, but the layers should be able to shear freely
    - Feel how the IT band acts as a divider between the lateral quadriceps and the hamstrings.

## Proximal IT Band

- Sidelying
- Feel the fibrous it band on the lateral surface of the femur @jonesProjectPhysicalTherapy2025
- Palpate the posterior border of the femur, note where the fibrous tissue ends, that is where the IT band branches posterolaterally to the [gluteus maximus]({{< var ref-gluteus-maximus.insertion >}}) @jonesProjectPhysicalTherapy2025.
- Return to the lateral femoral shaft and palpate anterosuperiorly to find the IT bands attachment to the [TFL]({{< var ref-tensor-fascia-latae.insertion >}}) @jonesProjectPhysicalTherapy2025.


- On the lateral femoral surface, move the hip while pinning down the IT band to assess if the femur can move *independently* from the IT Band.


## Distal IT band

- Patient prone
- Flex knee to 90&deg;
- Palpate distal lateral femur
- Feel if the femur can move *independently* from the IT Band
- If the IT band feels adhered to the femur then treat it:

**Treatment**: 

- apply *pure pressure* to the border between the IT Band and the femur
- Rotate the femur back and forth to increase or decrease pressure and separate the IT band from the femoral shaft @jonesProjectFoundations2025.
