---
title: Psoas Major Muscle
---

# OIAN

| Muscle  | Origin | Insertion | Nerve | Action |
|------|--------|-------|----------|--------|
| [Psoas Major]({{< var ref-psoas-major.path >}}) | {{< var ref-psoas-major.origin >}} | {{< var ref-psoas-major.insertion >}} | {{< var ref-psoas-major.nerve >}} | {{< var ref-psoas-major.action >}} |
: {.striped .hover}

```{r tbl-psoas-major-oian}
#| echo: false
#| warning: false
#| message: false

# Load the here package
library(here)

# Source the functions script
source(here("scripts/gt_oian.R"))

# Example usage
identifier_col <- "muscle_identifier"  # or "group_identifier"
filter_patterns <- "psoas_major"
display_columns <- c("name_final", "origin_final", "insertion_final", "innervation_final", "action_final")
table_title <- "Psoas Major Muscle"

# Call the function
gt_table <- gt_oian(identifier_col, filter_patterns, display_columns, table_title)

gt_table
```

# Origin {#origin}

- Superficial: T12–L4 and associated intervertebral disks (lateral surfaces) @gilroyAtlasAnatomy2020 
- Deep: L1–L5 vertebrae (TPs @bogdukAnatomyBiomechanicsPsoas1992)
- The Psoas Major has fibrous attachments from the anterior TP of the lumbar spine as well as the anteromedial aspect of the lumbar IVD, except for L5/S1 disc @bogdukAnatomyBiomechanicsPsoas1992 

# Insertion {#insertion}
Femur (lesser trochanter) @gilroyAtlasAnatomy2020

# Innervation {#innervation}
Lumbar plexus Direct Br. ([L1]({{< var ref-nerve-root.l1 >}}), [L2]({{< var ref-nerve-root.l2 >}}), [**L3**]({{< var ref-nerve-root.l3 >}})) @gilroyAtlasAnatomy2020

# Action {#action}
**Hip joint**: flexion and external rotation @gilroyAtlasAnatomy2020
**Lumbar spine**: unilateral contraction (with the femur fixed) flexes the trunk laterally to the same side; bilateral contraction raises the trunk from the supine position @gilroyAtlasAnatomy2020




# Overview