---
title: Lateral Pterygoid muscle
---

::: {.callout title="Reading list"}

- Trigger points
    - Lateral pterygoid Muscle @donnellyTravellSimonsSimons2019
    - Pterygoids @finandoTriggerPointTherapy2005

:::



 


# Origin {#origin}
**Superior Head:** Greater wing of sphenoid bone (infratemporal crest); **Inferior head:** Lateral surface of pterygoid plate (lat surface) @gilroyAtlasAnatomy2020

# Insertion {#insertion}
**Superior Head:** Tempormandibular joint (articular disc); **Inferior head:** Mandible (condylar process) @gilroyAtlasAnatomy2020

# Innervation {#innervation}

[Mandibular (V~3~) divison of CN V via lateral pterygoid n.]({{< var ref-cn5.path >}}) @gilroyAtlasAnatomy2020

# Action {#action}
- **BIL:** Protrudes mandible (pulls articular disk forward)
- **UNIL:** C/L Lateral movements of mandible (chewing)  @gilroyAtlasAnatomy2020

:::{.callout title="neummann explanation"}
"The lateral pterygoid muscle is generally described as a bipennate muscle with two distinct heads (see Fig. 11.19B).28,74,77,99 The superior head arises from the greater wing of the sphenoid bone (see Figs. 11.5 and 11.7). The considerably larger inferior head arises from the lateral surface of the lateral pterygoid plate and adjoining region of the maxilla.
As a whole, the lateral pterygoid muscle traverses nearly horizontally to insert into a region of the neck of the mandible, very near the joint (review Fig. 11.10).4,27,28,77,99 Although the specific anatomic details are debated,14 the superior head of the lateral pterygoid shares attachments with the pterygoid fossa (see Fig. 11.2), the medial wall of the capsule, and the medial side of the" @neumannKinesiologyMusculoskeletalSystem2017
:::

# Palpation

- Intraoral: debatable (Turp 2001)
    - posterior up towards the mandibular neck
    - cranial directed pressure underneath zygomatic arch (have subject protrude)
    - Ask them to protrude w/ palpation



# Clinical Significance

Practically functions to stabilize the [articular disc of the TMJ]({{< var ref-temporomandibular-joint.articular-disc >}})

Tears or excessive elongation of the lateral ligament may cause the disc to migrate medially by an unopposed pull of the superior head of the lateral pterygoid muscle @neumannKinesiologyMusculoskeletalSystem2017


# Strain-Counterstrain

::: {.callout}
"Location of Tender Point: 1) 1cm anterior to the neck of the condyle. Push medial and posterior. 2) Lower edge of the greater wing of sphenoid.  Anatomical Correlation: Lateral ptyergoid muscle.  Direction to Press on Tender Point: Tender Point 1, press medial and slightly posterior. Tender Point 2, press medially.  Treatment Position(s): With patient supine, push their open jaw 2cm laterally away from the Tender Point side deviating mandible to the opposite side. Apply stabilizing force with forearm of the motion hand.  Frequency of Occurrence: Very common.  Clinical Correlation(s): 1) Pain with chewing 2) Click in TMJ 3) Dyskinesia with mouth opening  Alternate Names/Nomenclatures: TM) and maxilla." @myersClinicalCounterstrain2012
:::