---
title: Temporalis muscle
---

::: {.callout}

- Trigger poitns
    - Temporalis Muscle @donnellyTravellSimonsSimons2019
    - Temporalis @finandoTriggerPointTherapy2005

:::




 

# Origin {#origin}
Temporal fossa (inferior temporal line) @gilroyAtlasAnatomy2020

# Insertion {#insertion}
Coronoid process of mandible (apex and medial surface) @gilroyAtlasAnatomy2020

# Innervation {#innervation}

[Mandibular (V~3~) divison of CN V via deep temporal nn]({{< var ref-cn5.path >}}) @gilroyAtlasAnatomy2020

# Action {#action}
**Vertical fibers**: Elevate mandible; **Horizontal Fibers**: Retract (retrude) mandible; **Unilateral Fibers:** Lateral movement of mandible (chewing)  @gilroyAtlasAnatomy2020


:::{.callout title="Neumann explanation"}
"The temporalis is a flat, fan-shaped muscle that fills much of the concavity of the temporal fossa of the skull (see Fig. 11.17B). The superficial surface of the muscle is covered by and partially adhered to a relatively thick sheet of fascia, which limits the ease of palpating the belly of the muscle. From its cranial attachment, the temporalis forms a broad tendon that narrows distally as it passes through a space formed between the zygomatic arch and the lateral side of the skull (see Fig. 11.5). The muscle attaches distally to the coronoid process and to the anterior edge and medial surface of the ramus of the mandible (see Fig. 11.2). Bilateral contractions of the temporalis muscles elevate the mandible, producing a very effective biting force.91 The more oblique posterior fibers elevate and retrude the mandible. Similar to the masseter, the temporalis courses slightly medially as its approaches its distal attachment. Unilateral contraction of the temporalis, therefore, as when chewing in a side-to-side manner, causes slight ipsilateral excursion of the mandible (see Fig. 11.18). As explained for the masseter, the effectiveness of the temporalis for producing ipsilateral excursion is enhanced when the muscle is activated from a position of contralateral excursiona natural, cyclic kinematic pattern used while chewing." @neumannKinesiologyMusculoskeletalSystem2017
:::

# Palpation
Temporalis is a thin sheet so use light pressure



# Clinical Significance



# Strain-Counterstrain

::: {.callout}
"Location of Tender Point: Anywhere in the fan-shaped fibers of the muscle.  Anatomical Correlation: Temporalis muscle.  Direction to Press on Tender Point: Palpate the different fiber directions for thick and raised tissue in the muscle. Press medially.  Treatment Position(s): With patient supine, push the relaxed jaw toward the Tender Point side. Stabilize patient’s head with monitoring hand.  Frequency of Occurrence: Moderate.  Clinical Correlation(s): 1) Pain with yawning 2) Restricted mouth opening 3) Dental neuritis 4) Lateral shift to same side with mouth opening  Associated Pain Referral Patterns: Anterior, medial, and posterior temporal region.  Explanatory Notes: Usually seen in conjunction with masseter." @myersClinicalCounterstrain2012
:::