---
title: Thomas Test
---



- Can be positive for [acetabular labral tear]({{< var ref-acetebular-labral-tear.path >}}) @wongPhysicalExaminationHip2022



# Modified Thomas Test

:::{.callout-note}

See @cookMovementFunctionalMovement2010

:::

# Contract-Relax Technique {#contract-relax}

[contract-relax]({{< var ref-contract-relax.path >}})

- Position the patient at the end of the table with their tailbone at the end of the table.
- Place the contralateral foot on your chest/shoulder and your contralateral hand in the popliteal space on their thigh.
- Hook your inside leg around their ipsilateral lower leg, with your knee on the inside of their knee, but your foot on the outside of their foot.
    - This will allow you to control the amount of ipsilateral knee flexion.
- Place your inside hand on on the superomedial aspect of their knee.

- Press their contralateral hip into flexion and their ipsilateral hip into extension.
- Vary your pressure until you find the end feel.
- Have the patient extend their ipsilateral knee then move into flexion + adduction against your manual resistance for 3-5 seconds.
- Have the patient relax and try to sink in until you reach the end feel.

# Strain Counterstrain

{{< video https://www.youtube.com/watch?v=xFhQiQhIhCU >}}