---
title: Greater Trochanteric Pain Syndrome (GTPS)
---

<!-- 
reading list:

@disantis2022InternationalSociety2023
-->

Greater trochanteric pain syndrome (GTPS) refers to an array of symptoms including lateral hip pain localized around the <i>femur's greater trochanter</i>  [@neumannKinesiologyMusculoskeletalSystem2017].
GTPS symptoms generally stem from [degeneration of Gluteus medius tendon, gluteus minimus tendon, and/or associated bursitis](#pathophysiology)


**Syndrome not a pathology**: Greater trochanteric pain syndrome, meaning that there are different ways patients can all arrive at the same constellation of symptoms

# Demographics

GTPS is more common in woman &gt;40 years old [@neumannKinesiologyMusculoskeletalSystem2017].


# Presentation

- Aching or point tenderness around the greater trochanter [@neumannKinesiologyMusculoskeletalSystem2017]
- Weak hip abduction [@neumannKinesiologyMusculoskeletalSystem2017]
- Gait deviation due to weak/painful hip abductors [@neumannKinesiologyMusculoskeletalSystem2017]

Symptoms are generally aggravated by movements involving hip abductors undergoing high forces sustained or repeated [@neumannKinesiologyMusculoskeletalSystem2017].

- Single-leg stance
- Ascending stairs or hills

## Co-existing conditions

- Hip Osteoarthritis [@aptaCurrentConceptsOrthopaedic2024]
- Acetabular labral pathology [@aptaCurrentConceptsOrthopaedic2024]

# Pathophysiology

GTPS can be the result of multiple pathologies

- External snapping hip
- Proximal iliotibial band syndrome
- Trochanteric bursitis
- Gluteus medius or gluteus minimus tendinopathy
- Gluteus medius or gluteus minimus tearing

The source of symptoms in GTPS is generally due to [gluteus medius or minimus tendinopathies](#gluteal-tendinopathies) or [bursitis](#bursitis)




## Gluteal tendinopathies {#gluteal-tendinopathies}

GTPS is believed to be primarily due to [gluteus medius]({{< var ref-gluteus-medius.tendinopathy >}}) or [gluteus minimus tendinopathies]({{< var ref-gluteus-minimus.tendinopathy >}}) [@neumannKinesiologyMusculoskeletalSystem2017]

MRI evidence supports this theory since GTPS is often associated with thickening or thinning of the affected tendons as well as partial or full-thickness tears [@neumannKinesiologyMusculoskeletalSystem2017].

In the case of tendon tears, the gluteus medius experiences tears more often due to its [proximal attachment on the lateral surface of the greater trochanter]({{< var ref-gluteus-medius.insertion >}}) [@neumannKinesiologyMusculoskeletalSystem2017].

Due to parallels between gluteus medius and minimus tendinopathy with rotator cuff pathologies, GTPS has been nicknamed "rotator cuff pathology of the hip" [@neumannKinesiologyMusculoskeletalSystem2017].
Both the [supraspinatus]({{< var ref-supraspinatus.path >}}) and [gluteus medius]({{< var ref-gluteus-medius.path >}}) and [minimus]({{< var ref-gluteus-minimus.path >}}) tendons experience degneeration on the inferior aspect of the tendons as the tendons rub against the underlying bone [@neumannKinesiologyMusculoskeletalSystem2017].
Excessive force or tension through the gluteal medius or minimus can cause compression of the tendon against the underlying bone [@neumannKinesiologyMusculoskeletalSystem2017].

In addition, excessive tension of the <i>fascia latae</i> can cause force the gluteus medius and minimus tendons into the underlying bone as well [@neumannKinesiologyMusculoskeletalSystem2017].
Using this hypothesis, situations where the gluteus minimus and medius are abnormally weak, the TFL could compensate, resulting in increased tension on the <i>fascia latae</i> which would compress the gluteus minimus and medius tendons against the underyling bone resulting in respective tendinopathies [@neumannKinesiologyMusculoskeletalSystem2017].

## Bursitis

Bursitis is the other cause of GTPS, making up ~20% of cases [@neumannKinesiologyMusculoskeletalSystem2017].
The bursa over the posterior-inferior aspect of the greater trochanter is most commonly affected, followed by the bursa underneath the gluteus medius and minimus insertions [@neumannKinesiologyMusculoskeletalSystem2017].


# DDX

- Intra-articular hip disorders [@disantis2022InternationalSociety2023]
- Lumbosacral spine disorders [@disantis2022InternationalSociety2023]
- Muscle-tendon disorders of the hip [@disantis2022InternationalSociety2023]

## Lumbosacral spine disorders

Patients with the following symptoms should undergo a comprehensive lower quarter screen:

- Radiating pain below the knee [@disantis2022InternationalSociety2023]
- Pain in the lowback [@disantis2022InternationalSociety2023]
- Aggravations with lumbar movements


Comprehensive lower quarter screen involves:

- Myotome-related weakness [@disantis2022InternationalSociety2023]
- Decreased sensation in a dermatomal pattern [@disantis2022InternationalSociety2023]
- Abnormal reflexes [@disantis2022InternationalSociety2023]
- Lumbar ROM [@disantis2022InternationalSociety2023]

## Intra-articular Hip conditions

Intra-articular hip conditions include:

- Hip OA [@disantis2022InternationalSociety2023]

Screen:

- Groin pain [@disantis2022InternationalSociety2023]
- AM stiffness [@disantis2022InternationalSociety2023]
- FABER (+groin pain)[@disantis2022InternationalSociety2023]
- IROP Test [@disantis2022InternationalSociety2023]
- Scour Test [@disantis2022InternationalSociety2023]
- Capsular pattern ROM limitations [@disantis2022InternationalSociety2023]
- Palpation
    - Ischial tuberosity



### Hip OA

patients with hip OA will commonly present with:

- Groin pain[@disantis2022InternationalSociety2023]
- AM Pain [@disantis2022InternationalSociety2023]






# Management

## Conservative
Conservative management of GTPS has demonstrated good results.
Some of the most successful treatments include:

- Corticosteroid injection
- Shockwave therapy
- Exercise

## Surgical management

Patients who have poor response to conservative management can be candidates for surgical management.

Here are the following procedures commonly given to treat GTPS:

- Gluteal Tendon Repair
- ITB release/lengthening surgery
- Trochanteric Osteotomy


# Treatments

## Corticosteroid injection

Corticosteroid injection has been shown to decrease inflammatory pain, allowing for improved activity tolerance [@aptaCurrentConceptsOrthopaedic2024].


## Shockwave Therapy

- Extracorporeal shockwave therapy + exercise demonstrated an 87% success rates within 2months [@aptaCurrentConceptsOrthopaedic2024]

## Manual Therapy

### Soft-Tissue Mobilization

STM is indicated for patients with tissue-hypomobility or pain control [@aptaCurrentConceptsOrthopaedic2024].

Due to the compressive etiology, caution is advised for symptomatic tissues since STM can add more irritating stimuli [@aptaCurrentConceptsOrthopaedic2024].

### Joint Mobilizations

Joint mobilizations are indicated if concurrent joint hypomobility is present [@aptaCurrentConceptsOrthopaedic2024].

## Exercise

### Exercises

### Stretching

Stretching has traditionally been prescribed in the management of GTPS, specifically of the ITB-complex [@aptaCurrentConceptsOrthopaedic2024].
Stretching the ITB can be unproductive and even **aggravating** since [ITB tensile forces can indirectly result in compression of the gluteal tendons](#gluteal-tendinopathies)[@aptaCurrentConceptsOrthopaedic2024].

As a result, clinicians should only perform stretching to restore tissue length *if* it is hindering optimum function [@aptaCurrentConceptsOrthopaedic2024].
In these scenarios, stretching should be dosed per patient tolerance [@aptaCurrentConceptsOrthopaedic2024].


Simplified Rehab Process

1. Decrease TFL-ITB tension
1. Less compression of gluteal tendons & bursa
1. Less degeneration
1. Less pain
1. Happy patients


Many clinicians *assume* that prescribing stretches will result in decreased TFL-ITB tension and overall less degeneration and pain.

This is only *half*-true, this perspective overlooks the potential harms of stretching.

#### Stretching does have benefits

After a stretch, the improved muscle extensibility and joint ROM can result in:


- Less ITB tension &rarr;
- Less tissue compression &rarr;
- Less degeneration &rarr;
- Less pain

#### The Drawbacks of Stretching

During the stretch, tension on the TFL-ITB <i>increases</i> and can cause: 

- More compression &rarr;
- More degeneration &rarr;
- More pain



Deciding whether to stretch TFL-ITB will come down to a simple tradeoff: Does stretching cause more or less **net compression**?

Choose the option that results in the **least net compression**

The long term *decreases* in compression from stretching **must** outweigh the short term *increases* in compression during the stretch exercise.



In the clinic, look for a *direct* relationship where a limited TFL-ITB complex results in dysfunctional movement patterns.


Perform a *movement analysis* and look for limitations in hip extension and adduction during:

::: {.columns}
::: {.column}
- Sitting
- Standing
- Walking
:::

::: {.column}
- Lifting
- Running
- Jumping
:::
:::


Patients who can perform these activities correctly without experiencing TFL-ITB tightness are **less** likely to benefit from stretching.

Patients who experience TFL-ITB tightness and exhibit movement compensations **would benefit** most from stretching.



# Patient Education

- Self-modifying activities and positions to decrease load/compressive forces

## Modification

- Avoiding high compression activities:
    - Sitting with legs crossed [@aptaCurrentConceptsOrthopaedic2024]
    - Standing with legs crossed [@aptaCurrentConceptsOrthopaedic2024]
    - Standing with a lateral lean [@aptaCurrentConceptsOrthopaedic2024]

## Sleeping

Sleeping positions are important to consider since these are static positions maintained for extended periods of time.

**Recommended position**: Supine with legs in slight abduction is best for patients with severe symptoms since it minimizes compression of gluteal tendons [@aptaCurrentConceptsOrthopaedic2024].

Sidelying with affected leg on top and adducted creates **excessive** compression on the trochanteric region and should be modified to include a pillow between the knees to decrease adduction [@aptaCurrentConceptsOrthopaedic2024].


# Sports

## Running

- Avoid banked tracks [@aptaCurrentConceptsOrthopaedic2024]
- Avoid running altogether if possible if aggravating

## Cycling

- Minimizing cycling on roads/tracks with excessive camber [@aptaCurrentConceptsOrthopaedic2024]



