---
title: Interspinous Ligaments
---

# Anatomy

The interspinous ligaments connect consecutive *spinous processes* together @standringGraysAnatomyAnatomical2021.


The interspinous ligaments start ventrally from *ligamentum flavum* and extend dorsally to the *supraspinous ligament* @standringGraysAnatomyAnatomical2021.


# Histology

# Morphology

The interspinous ligaments have different structures based on the cervical, thoracic, and lumbar levels @standringGraysAnatomyAnatomical2021.

- Cervical region
    - Not distinct @standringGraysAnatomyAnatomical2021
    - Appears as the median septum of LF @standringGraysAnatomyAnatomical2021
- Thoracic region
    - Narrow
    - Elongated
- Lumbar
    - Thick @standringGraysAnatomyAnatomical2021
    - Quadrilateral @standringGraysAnatomyAnatomical2021
    - separated by a narrow cleft @standringGraysAnatomyAnatomical2021
    - Run obliquely inferiorly and ventrally @standringGraysAnatomyAnatomical2021
    - Only the *deep*(ventral) fibers are *true ligaments* (span bone-to-bone)
        - *superficial* (dorsal) fibers span from the *longissimus thoracis mm.* to the superior edge of the SP @standringGraysAnatomyAnatomical2021.


