---
title: Nuchal Ligament
---

:::{.callout-tip title="AKA"}

- Ligamentum Nuchae
- Nuchal Ligament
:::

The Nuchal ligament serves as an attachment for the [upper trapezius]({{< var ref-upper-trapezius.path >}}), [splenius capitis]({{< var ref-splenius-capitis.path >}}), and [splenius cervicis]({{< var ref-splenius-cervicis.path >}}) @neumannKinesiologyMusculoskeletalSystem2017.


# Anatomy

- Comprised of four portions formed by traps, splenius capitus, rhomboid major and serratus posterior @duttonDuttonOrthopaedicExamination2020
- Continues as supraspinous ligament @ C7 @duttonDuttonOrthopaedicExamination2020



# Muscular Attachments

- [Serratus Posterior Superior]({{< var ref-serratus-posterior-superior.path >}})


# Function

- Aids in suspension of head and neck @duttonDuttonOrthopaedicExamination2020
- Fxn is controversial @duttonDuttonOrthopaedicExamination2020
- Stability of C7, occiput @duttonDuttonOrthopaedicExamination2020
- Potential Role in cervicogenic headaches @duttonDuttonOrthopaedicExamination2020
- Limits anterior translation of head and flexion @duttonDuttonOrthopaedicExamination2020




