---
title: Posterior Longitudinal Ligament (PLL)
---

The *PLL* is the opposite of the *ALL*.

The *PLL* lies on the posterior surface of the vertebral bodies within the vertebral canal @standringGraysAnatomyAnatomical2021.

The *PLL* is a continuation of the *tectorial membrane* rostrally @standringGraysAnatomyAnatomical2021.
The PLL spans from the *C02 vertebral body* to the 



# Attachments

- Intervertebral discs @standringGraysAnatomyAnatomical2021
- Vertebral end-plates @standringGraysAnatomyAnatomical2021
- Adjacent margins of vertebral bodies @standringGraysAnatomyAnatomical2021

The *basivertebral veins* and associated *venous channels* separate the attachments of the *PLL* @standringGraysAnatomyAnatomical2021.

# Anatomy

The PLL is board and has a consistent width in the cervical and upper thoracic region @standringGraysAnatomyAnatomical2021.
In the lower thoracic and lumbar region, the ligament's width becomes denticulated; it is *narrow* over the vertebral bodies and *broad* over the intervertebral discs @standringGraysAnatomyAnatomical2021.

# Fibers

- Superficial Fibers 
- Deeper fibers

**Superficial Fibers** span 3-4 vertebrae @standringGraysAnatomyAnatomical2021.

**Deeper fibers** extend between adjacent vertebrae @standringGraysAnatomyAnatomical2021


# Fascial Counterstrain




# Anatomy

- Sacrum to body of C2
- Continuous w tectoral membrane

# Function

- Prevents disk protrusions and restrains flexion of vert column
- Dural mater strongly adhered to PLL at C3 and higher, diminishes lower



# Manual therapy

- IASTM between 
- Cupping
- Fascial pumping (to Lumbar spine and sacrum) @NickPerkinsClinicalInternship
    - place one hand on T/S kyphosis with fingers pointing rostrally
    - Place the other hand on the sacrum with fingers pointing caudally
    - As the patient inhales, assist the spine into flexion and distraction
    - As the patient exhales, hold the position, then slowly decrease the flexion and distraction force