---
title: Joint Mobilization
---



# Grades

## Maitland

| Grade | Description |
|-|-|
| 0 | No detecteble movement |
| 1 | Small amp <br> Within resistance free range ($<$R1) |
| 2 | Large amp <br> Within resistance free range ( $<$R1) |
| 3 | Large amp <br> Into resistance (R1) |
| R1 | The point at which resistance became perceptible |
| 4 | Small amp <br>  Into resistance (Past R1) |
| 5 | High velocity low amplitude thrust (HVLT) |


# End Feel


Normal end feel:

| Type | Cause | Characteristics and Examples |
|-|-|-|
| Bony | Bone-to-bone approximation | Abrupt and unyielding </br> Feels as if more pressure could break something |
| Elastic | Muscle-tendon unit tension </br> Can occur with adaptive shortening | "Stretches with elastic recoil and exhibits constant-length phenomenon; further forcing feels as if it will snap something" |
| Soft-tissue approximation | "Produced by contact of two muscle bulks on either side of a flexing joint where joint range exceeds other restraints" | "Very forgiving end-feel that gives impression that further normal motion is possible if enough force could be applied" |
| Capsular | Produced by ligaments or capsule | "Various degrees of stretch without elasticity; stretch ability is dependent on thickness of tissue Strong capsular or extracapsular ligaments produce hard capsular end-feel, whereas thin capsule produces softer one Impression given to clinician is that if further force is applied, something will tear" |
: Normal Joint end-feels (From @duttonDuttonOrthopaedicExamination2020)



| Type | Cause | Characteristics and Examples |
|-|-|-|
| Springy | "Produced by articular surface rebounding from intra-articular meniscus or disk; impression is that if forced further, something will give way" | "Rebound sensation as if pushing off from a rubber pad" |
| Boggy | "Produced by viscous fluid (blood) within joint" | "“Squishy” sensation as joint is moved toward its end range; further forcing feels as if it will burst joint" |
| Spasm | "Produced by reflex and reactive muscle contraction in response to irritation of nociceptor, predominantly in articular structures and muscle; forcing it further feels as if nothing will give" |  "Abrupt and “twangy” end to movement that is unyielding while the structure is being threatened but disappears when threat is removed (kicks back) With joint inflammation, it occurs early in range, especially toward closepacked position, to prevent further stress With irritable joint hypermobility, it occurs at end of what should be normal range, as it prevents excessive motion from further stimulating the nociceptor Spasm in grade II muscle tears becomes apparent as muscle is passively lengthened and is accompanied by a painful weakness of that muscle Note: Muscle guarding is not a true end-feel, as it involves co-contraction" |
| Empty | "Produced solely by pain; frequently caused by serious and severe pathologic changes that do not affect joint or muscle and so do not produce spasm; demonstration of this end-feel is, with exception of acute subdeltoid bursitis, de facto evidence of serious pathology; further forcing simply increases pain to unacceptable levels" | "Limitation of motion has no tissue resistance component, and resistance is from patient being unable to tolerate further motion due to severe pain; it is not same feeling as voluntary guarding, but rather it feels as if patient is both resisting and trying to allow movement simultaneously" |
| Facilitation | "Not truly an end-feel, as facilitated hypertonicity does not restrict motion; it can, however, be perceived near end range" | "Light resistance as from constant light muscle contraction throughout latter half of range that does not prevent end of range being reached; resistance is unaffected by rate of movement" |
: Abnormal Joint end-feels (From @duttonDuttonOrthopaedicExamination2020)



Some abnormal joint end feels have 'recommended' manual techniques [@duttonDuttonOrthopaedicExamination2020]. 

| Barrier | End-feel | Technique |
|-|-|-|
| Pain | Empty | None |
| Pain | Spasm | None |
| Pain | Capsular | Oscillations (I, IV) |
| Joint adhesions | Early capsular | Passive articular motion stretch (I–V) |
| Muscle adhesions | Early elastic | Passive physiologic motion stretch |
| Hypertonicity | Facilitation | Muscle energy (hold/ relax, etc.) |
| Hard/Bone | Bony | None |
: Recommended manual techniques for abnormal joint end feel (From @duttonDuttonOrthopaedicExamination2020).

