---
title: Elbow and forearm
subtitle: Musculoskeletal overview
---


::: {.callout title="Reading list"}

- Clinical Considerations of Elbow, Wrist, and Hand Pain @donnellyTravellSimonsSimons2019
- Kinesiology / biomech
    - Elbow and forearm @neumannKinesiologyMusculoskeletalSystem2017
    - wrist @neumannKinesiologyMusculoskeletalSystem2017
    - Hand @neumannKinesiologyMusculoskeletalSystem2017
- MMT
    - wrist flex MMT @weinstockNeuroKineticTherapyInnovative2010
    - wrist ext MMT @weinstockNeuroKineticTherapyInnovative2010
    - wrist abduction (Radial dev) MMT @weinstockNeuroKineticTherapyInnovative2010
    - Wrist adduction MMT @weinstockNeuroKineticTherapyInnovative2010
    - Hand MMT
        - MMT @weinstockNeuroKineticTherapyInnovative2010
- General
    - Ch17 elbow @duttonDuttonOrthopaedicExamination2020
    - Ch 18 @duttonDuttonOrthopaedicExamination2020
- Examination
    - Ch19 Screening the Shoulder and Upper Extremity @heickGoodmanSnyderDifferential2023
- Pathology
    - Elite Athlete's Hand and Wrist Injury, an Issue of Hand Clinics @carlsonEliteAthletesHand2012
    - Tendon disorders of the hand and wrist: IFSSH/FESSH instructional course book 2022 @federationoftheeuropeansocietiesforsurgeryofthehandTendonDisordersHand2022
- Manual tx
    - ch23 Orthopaedic Manual Physical Therapy of the Elbow and Forearm @wiseOrthopaedicManualPhysical2015
    - Ch24 Orthopaedic Manual Physical Therapy of the Wrist and Hand @wiseOrthopaedicManualPhysical2015
- Surgery
    - Management of Hand Fractures @chungGrabbSmithPlastic2020
    - Management of Wrist Fractures @chungGrabbSmithPlastic2020
    - Flexor Tendon Repair and Reconstruction @chungGrabbSmithPlastic2020
    - Extensor Tendon Repair and Reconstruction @chungGrabbSmithPlastic2020
    - Tenosynovitis Disorders of the Upper Extremity @chungGrabbSmithPlastic2020
    - Principles and Applications of Tendon Transfers @chungGrabbSmithPlastic2020
    - Ligament Injuries of the Hand @chungGrabbSmithPlastic2020
    - Ligament Injuries of the Wrist @chungGrabbSmithPlastic2020
    - Management of Mutilating Upper Extremity Injuries @chungGrabbSmithPlastic2020
    - Replantation Strategies of the Hand and Upper Extremity @chungGrabbSmithPlastic2020
    - Thumb Reconstruction @chungGrabbSmithPlastic2020
    - Dupuytren Disease @chungGrabbSmithPlastic2020
    - Hand Tumors @chungGrabbSmithPlastic2020
    - Treatment of Vascular Disorders of the Hand @chungGrabbSmithPlastic2020
    - Comprehensive Management of the Burned Hand @chungGrabbSmithPlastic2020 
    - Compartment Syndrome of the Upper Extremity  @chungGrabbSmithPlastic2020 
    - Common Congenital Hand Anomalies @chungGrabbSmithPlastic2020
    - Upper Limb Amputations and Prosthetics @chungGrabbSmithPlastic2020
    - Rheumatoid Arthritis and Inflammatory Arthropathies @chungGrabbSmithPlastic2020 
    - Osteoarthritis @chungGrabbSmithPlastic2020

:::


# Elbow Overview

3 bones:

1. Humerus
1. Radius
1. Ulna




# Humerus


### Medial epicondyle
<!-- PT, FCR, PL, Flexsuperf, FCU -->
```{python tbl-humerus-medial-epicondyle-oian}
#| label: tbl-humerus-medial-epicondyle-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Muscles originating from the Medial Epicondyle"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'origin_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['humerus_medial_epicondyle']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```



### Lateral epicondyle

```{python tbl-humerus-lateral-epicondyle-oian}
#| label: tbl-humerus-lateral-epicondyle-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Muscles originating from the Lateral Epicondyle"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'origin_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['humerus_lateral_epicondyle']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

# Elbow Ligaments

- [Ulnar collateral ligament]({{< var ref-ulnar-collateral-ligament.path >}})
- [Radial collateral ligament]({{< var ref-radial-collateral-ligament.path >}})

# Radius bone

## Head of Radius



# Elbow Joint

## Articular surfaces


# Carrying Angle

# Elbow Flexion & Extension

## Elbow Flexion

Limits of *active* flexion: apposition of anterior arm and forearm muscles @jonesProjectFoundations2025

Limits of *passive* flexion with overpressure:

- Muscle compression @jonesProjectFoundations2025
- Bony block of radial head against *radial fossa* @jonesProjectFoundations2025
- Bony impact of *coronoid process* against *coronoid fossa* @jonesProjectFoundations2025
- Tension in posterior aspect of capsule @jonesProjectFoundations2025
- Triceps stretch tension @jonesProjectFoundations2025



<!-- Should be: Biceps brachii, brachialis, brachioradialis -->
```{python tbl-elbow-flexors-oian}
#| label: tbl-elbow-flexors-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Elbow Flexor Muscles"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'action_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['elbow_flex']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```



## Elbow Extension


Limits of extension:

- bony block of *olecranon process* in the *olecranon fossa* @jonesProjectFoundations2025
- Anterior ligament tensioning @jonesProjectFoundations2025
- [Elbow flexor](#tbl-elbow-flexors-oian) resistance

```{python tbl-elbow-extensors-oian}
#| label: tbl-elbow-extensors-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Elbow Extensor Muscles"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'action_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['elbow_ext']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

::: {.callout-warning title="Hyperextension injuries"}

- Olecranon fracture @jonesProjectFoundations2025
- Capsule tear @jonesProjectFoundations2025
    - With or without posterior dislocation @jonesProjectFoundations2025
        - Circumflex humeral artery can be damaged @jonesProjectFoundations2025

:::

# Elbow Joint Stabilization

## Longitudinal traction

Longitudinal traction is limited primarily through soft tissue structures:

- Medial and lateral collateral ligaments @jonesProjectFoundations2025
- Muscles:
    - Triceps
    - Biceps
    - Coracobrachialis
    - Forearm muscles: Brachioradialis
    - Medial epicondyle muscles
    - Lateral epicondyle muscles

In **full extension** the olecranon of the humerus hooks onto the humeral trochlea in the *olecranon* fossa which can provide resistance to elongation of the humeroulnar joint @jonesProjectFoundations2025.

## Longitudinal Compression

Unlike [longitudinal traction](#longitudinal-traction), longitudinal compression is supported primarily through boney contacts @jonesProjectFoundations2025.

Compressive force is transmitted through the [radius]({{< var ref-radius-bone.path >}}) to the *radial head* @jonesProjectFoundations2025.

Compressive force is also abosrbed through the [ulna]({{< var ref-ulna-bone.path >}}) to the coronoid process of the ulna @jonesProjectFoundations2025.

::: {.callout-important title="Overload"}
Excessive compressive load through the [radius]({{< var ref-radius-bone.path >}}) can result in a [radial head fracture]({{< var ref-radius-bone.fracture >}}) @jonesProjectFoundations2025.
Likewise, excessive load through the ulna can result in a fracture or posterior dislocation @jonesProjectFoundations2025.
:::

## 90&deg; Flexion

At 90&deg; of flexion, the [ulna]({{< var ref-ulna-bone.path >}}) is "perfectly" stabilized, but the [radius]({{< var ref-radius-bone.path >}}) is unstable @jonesProjectFoundations2025.

The [ulna]({{< var ref-ulna-bone.path >}}) is stabilized at the *trochlear notch* due to musculotendinous insertions on either side from the [triceps common insertion]({{< var ref-triceps-brachii.insertion >}}) and the [coracobrachialis]({{< var ref-coracobrachialis.isnertion >}}) @jonesProjectFoundations2025.
These two muscles insert on opposite sides of the trochlear notch and oppose eachother when contracting, resulting in joint approximation and stabilization @jonesProjectFoundations2025.
The [anconeus]({{< var ref-anconeus.action >}}) also plays a role in humeroulnar stability at 90&deg; flexion @jonesProjectFoundations2025.

The [radius]({{< var ref-radius-bone.path >}}) has a large amount of freedom at 90&deg; flexion, which results in decreased stability.
When the [biceps]({{< var ref-biceps-brachii.path >}}) contract, the radius could dislocted "proximately" @jonesProjectFoundations2025, if the *annular ligament* did not prevent it @jonesProjectFoundations2025.
Patients with annular ligament tears, commonly experience proximal and anterior radial dislocations during from the slightest degree of flexion following [biceps]({{< var ref-biceps-brachii.path >}}) contraction @jonesProjectFoundations2025.

# Proximal Radioulnar Joint

The proximal RUJ refers to the articulation of the *radial head* on the *radial notch of the ulna* @jonesProjectFoundations2025.

The radial head is convex with a cartilage rim that widens anteromedially @jonesProjectFoundations2025.

::: {.callout-note}
The cartilage extends to the *superior articular facet of the radius* which is concave and articulates with the *humerus' capitulum* @jonesProjectFoundations2025.
:::

The readial head is surrounded by a fibro-osseous ring

Read more about the [proximal radioulnar joint here]({{< var ref-proximal-radioulnar-joint.path >}}).

# Distal Radio-ulnar Joint



Read more about the [distal radioulnar joint here]({{< var ref-distal-radioulnar-joint.path >}}).

# Pronation & Supination

Pronation and supination are important forearm mechanics that allow us to optimally position the hand for grasp, press, pull, or support objects @jonesProjectFoundations2025.

Pronation and supination are a compound movement that occurs through 2 joints:

1. Proximal radioulnar joint
1. Distal radioulnar joint


## Range of motion

ROM for pronation and supination should be assessed with the elbow flexed to 90&deg; @jonesProjectFoundations2025.
When fully extended, the axis for pronation and supination is collinear with shoulder internal and external rotation, making it difficult to isolate @jonesProjectFoundations2025.



## Complexity


## Pronation



```{python tbl-forearm-pronators-oian}
#| label: tbl-forearm-pronators-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Forearm Pronation Muscles"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'action_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['elbow_pronation']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

::: {.callout-note}
Limited pronation will result in compensations, most notably excessive shoulder internal rotation.
:::

## Supination

```{python tbl-forearm-supinators-oian}
#| label: tbl-forearm-supinators-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: "Forearm Supination Muscles"

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'action_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['elbow_supination']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

::: {.callout-note}
Limited supinationwill result in compensations, most notably excessive shoulder external rotation.
:::

## Range of Motion

# Radio-ulnar complex

The radius and ulna stay together during pronation and supination due to:

- [IO membrane]({{< var ref-interosseous-membrane-forearm.path >}})
- Oblique cord: Reinforces connection between the superior radius and ulna @jonesProjectFoundations2025.
- Annular ligament
- [Radial Collateral Ligament (of the forearm)]({{< var ref-radial-collateral-ligament.path >}}): Reinforces the annular ligament
- [Ulnar collateral ligament (of the forearm)]({{< var ref-ulnar-collateral-ligament.path >}}) reinforces the annular lig.
- Radio-ulnar joint ligaments
    - Anterior Radio-ulnar joint ligament
    - Posterior Radio-ulnar joint ligament
    - Inferior Radio-ulnar joint ligament 
- Articular disc
- Muscle limits
    - Medial epicondyle flexors
        - FDS
        - PL
        - FCR
    - Lateral epicondyle extensors
        - ED 
        - ECRL
        - ECRB 
        - ECU 
    - Elbow joint:
        - Supinator
        - Pronator Teres
        - Brachioradialis

## Interosseous membrane

[Interosseous membrane (IO Membrane)]({{< var ref-interosseous-membrane-forearm.path >}})

## Ligaments

- Oblique cord
- Annular ligament
- Lateral Collateral Ligament (of the forearm) 
- Medial collateral ligament (of the forearm)
- Radio-ulnar joint ligaments
    - Anterior Radio-ulnar joint ligament
    - Posterior Radio-ulnar joint ligament
    - Inferior Radio-ulnar joint ligament



## Movement

# MMT

See reading list

# Elbow evaluation

- Palpate:
    - Olecranon
    - Medial epicondyle
    - lateral epicondyle


# Wrist


# Wrist Movements

- Flexion & Extension
- Radial (abduction) & Ulnar Deviation (adduction)
- Circumduction

## Flexion


## Extension


## Radial Deviation

AKA *wrist abduction*

## Ulnar deviation

AKA *wrist adduction*

# Radiocarpal Joint {#radiocarpal-joint}

# Wrist Ligaments

- Palmar radiocarpal ligaments
    - [Radioscaphocapitate ligament]({{< var ref-radioscaphocapitate-ligament.path >}})
    - [Long radiolunate ligament]({{< var ref-long-radiolunate-ligament.path >}})
    - [Radioscapholunate ligament]({{< var ref-radioscapholunate-ligament.path >}})
    - [Short radiolunate ligament]({{< var ref-short-radiolunate-ligament.path >}})
- [Palmar ulnocarpal ligament]({{< var ref-palmar-ulnocarpal-ligament.path >}})
- [Dorsal Radiocarpal ligament]({{< var ref-dorsal-radiocarpal-ligament.path >}})
- Collateral Carpal ligaments
    - [Ulnar collateral carpal ligament]({{< var ref-ulnar-collateral-carpal-ligament.path >}})
    - [Radial collateral carpal ligament]({{< var ref-radial-collateral-carpal-ligament.path >}})
- Radiocarpal Ligaments
    - Anterior radiocarpal ligament
    - Posterior radiocarpal ligament
- Interosseous ligaments (link the scaphoid, lunate, and triquetrum)
    - [Scapholunate interosseous ligament (SLIL)]({{< var ref-scapholunate-interosseous-ligament.path >}})
    - [Lunotriquetral interosseous ligament (LTIL)]({{< var ref-lunotriquetral-interosseous-ligament.path >}})
    - Trapezotrapezoidal interosseous ligament
    - Trapezoidocapitate interosseous ligament
    - Hamatocapitate interosseous ligament
- Lunatocapitate ligament
- Triquetrocapitate ligament
- Scaphotrapezial ligament
- Triquetrohamate ligament
- Pisohamate ligament
- Pisometacarpal ligaments
    - 


## Radiocarpal and Midcarpal Joint ligaments

# Triangular Fibrocartilage Complex (TFcC)

The [Triangular Fibrocartilage Complex (TFcC)]({{< var ref-triangular-fibrocartilage-complex.path >}})

# Carpal Bones

- [Scaphoid]({{< var ref-scaphoid-bone.path >}})
- [Lunate]({{< var ref-lunate-bone.path >}})
- [Triquetrum]({{< var ref-triquetrum-bone.path >}})

# Midcarpal Joint

# Carpus

- Median pillar: Lunate and capitate
- Lateral pillar: Scaphoid, trapezium, trapezoid


# Carpus Variability



# Therex

## Elbow Exercises


- Elbow CARs

## Wrist Exercises

- ROM
    - Wrist CARs

## Compound Movements

- Deadhangs
- Scap retraction deadhangs
- Grip variations
    - Lumbrical grip on ankle weight
    - Pronated grip
    - Neutral
    - Supinated grip
    - Suicide grip (no thumb)
- Shoulder I's
- Shoulder T's 
- Shoulder Y's 

## Recovery Movements

- ULTT1



# Hand MMT

see reading list


:::{.callout title="To read"}

- Rehabilitation of Elbow Injuries: Nonoperative and Operative @wilkRehabilitationElbowInjuries2020

:::


# Ligaments


# Assessment

## Follow the Radial nerve

- Patient in supine with ipsilateral arm abducted
- Clinician stands between patient's ipsilateral arm and torso
- 1 hand on patient's wrist
- Other hand wraps *over* the brachium and the fingertips of #2-4 palpate the intermuscular septum between the [medial head of the triceps]({{< var ref-triceps-brachii-medial-head.path >}}) and the [brachialis]({{< var ref-brachialis.path >}}).
- Tension the radial nerve by:
    - Shoulder depression
    - Shoulder abduction
    - Forearm pronation
    - Wrist flexion
- Tension the radial nerve while you palpate to find it and track its movement
- Follow the radial nerve as it courses distally and laterally between the lateral and middle heads of the triceps
- Palpate the ECRL and ECRB origins on the lateram brachium
- Follow the radial nerve as it passes through the extensors in the lateral compartment of the forearm
- Separate the wrist extensors by putting your fingers between their intermuscular septums and bringing the wrist/forearm into flexion + pronation.
    - Apply pressure with your fingertips on the extensors and apply movement using the hand holding the wrist @jonesProjectFoundations2025


## Proximal radius mobility

- Patient supine
    - Slight horizontal adduction
    - 90&deg; abduction
- Knee to stabilize humerus
- One hand wraps around radius and palpates joint line 


Testing Pronation/supination mobility


Testing end range extension mobility

# Exercises

# Recovery Movements

- Pec stretch
- Wall ULTT1
- 

# Tests

## Stress Tests

"Elbow instability can be viewed on a continuum from mild laxity to severe and recurrent dislocation that progresses from the lateral to the medial side of the elbow and may involve soft tissue and/or bone.2" @duttonDuttonOrthopaedicExamination2020 

- Medial (Ulnar) Collateral Ligament (Valgus Test) @duttonDuttonOrthopaedicExamination2020 
- Posterolateral Rotary Drawer Test
- Tabletop Rotatory Test
- Lateral Pivot Shift Apprehension Test
- Lateral (Radial) Collateral Ligament (Varus Test)

# Examination

## Lateral elbow

- UCL Band
    - Ulnar Collateral Ligament Valgus Test
        - Anterior band (20-30&deg;) @duttonDuttonOrthopaedicExamination2020 
        - Posterior band (>55&deg;)