---
title: Deadlift Foundational Exercises
keywords:
    - Foundational exercise
---


# Load transfer

During a deadlift the load transfers from:

1. Barbell
1. Grip contact
1. Arms
1. Shoulders
1. Trunk
1. Pelvis
1. Lower extremity

# Shoulder

A common compensation at the shoulder occurs when the patient is overly focused on depth and lacks hip mobility.
This patient will protract their shoulders in order to create the *allusion* of depth @jonesProjectPhysicalTherapy2025.
Shoulder protraction places the shoulder in an unstable position.
Full shoulder protraction places the retractor muscles in their most stretched position, causing them to be weaker than at midrange @jonesProjectPhysicalTherapy2025.


# Stance

Stance varies based on the individual, but it should be somewhere between hip and shoulder width apart.

::: {.callout-tip}
A wider stance can help to better expose asymmetries in range of motion or stability @jonesProjectPhysicalTherapy2025.
:::
# Assessment

- Bar path


## Bar path

The bar should follow a perfectly vertical path during the movement.


# Progressions

- Modified deadlift (MDL)
    - No knee/hip sequencing
    - Hip focused
- Romanian deadlift (RDL)
    - Asynchronous hip and knee sequencing
    - Hip focused
    - More extreme knee ROM than MDL
- Balance-assisted deadlift
- Deadlift (DL)
- Barbell deadlift

# Modified Deadlift



# Deadlift (BW)


# Single leg Modified deadlift

# Single Leg Deadlift




# Barbell Deadlift
## Setup
Bar in line with shoe laces
Arms straight with lats engaged
Neutral spine

## Action
Engage lats and press thru feet

## Key Points

- Stand up w bar
- Neutral spine
- Arms straight
- Hips and shoulders move at same time
- Heels down

## Faults

- Lose neutral spine
- Early Arm bend
- Hips/shoulder out of sync
- Heels up (Make sure to keep heelds down)

## Treatment Principles

- Cueing HUGE
- Regression; 
- Top down (if someone has a hard time building tension at the bottom, start them at the top then eccentrically lower then lift up again)
- Elevate starting position
- Inc lat engagement

