---
title: Longissimus Muscle
---


```{python tbl-longissimus-muscles-oian}
#| label: tbl-longissimus-muscles-oian
#| warning: false
#| message: false
#| echo: false
#| tbl-cap: Longissimus muscles

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'muscle_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['longissimus_capitis', 'longissimus_cervicis', 'longissimus_thoracis']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

# Longissimus Capitis
## Origin {#origin}
T1-T3 (TP), C4-C7 (TP & articular process) @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
Temporal bone (Mastoid process)

## Innervation {#innervation}
[Spinal nn. C1-L5 (Posterior Rami, lateral branches)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}

- BIL: Extends head @gilroyAtlasAnatomy2020
- UNIL: Flexes and I/L rotation @gilroyAtlasAnatomy2020

# Longissimus Cervicis
## Origin {#origin}
T1-T6 (TP) @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
C2-C5 (TP) @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. C1-L5 (Posterior Rami, lateral branches)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}
- BIL: Extends spine @gilroyAtlasAnatomy2020
- UNIL: I/L SB @gilroyAtlasAnatomy2020

# Longissimus Thoracis
## Origin {#origin}
Sacrum; Iliac crest; Lumbar vertebrae (SP); Lower thoracic vertebrae (TP) @gilroyAtlasAnatomy2020

## Insertion {#insertion} 
2nd-12th ribs; Thoracic & Lumbar vertebrae (TP) @gilroyAtlasAnatomy2020

## Innervation {#innervation}
[Spinal nn. C1-L5 (Posterior Rami, lateral branches)]({{< var ref-spinal-nerves.path >}}) @gilroyAtlasAnatomy2020

## Action {#action}
- BIL: Extends spine @gilroyAtlasAnatomy2020
- UNIL: I/L SB @gilroyAtlasAnatomy2020