---
title: Fibularis Longus Muscle
---


```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'muscle_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['fibularis_longus']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


# Origin {#origin}

Proximal lateral surface of the fibiula @gilroyAtlasAnatomy2020

# Insertion {#insertion}

- Medial cuneiform @gilroyAtlasAnatomy2020
- Base of 1st MT @gilroyAtlasAnatomy2020



# Innervation {#innervation}
[Superficial Fibular N.]({{< var ref-superficial-fibular-nerve.path >}}) ([L5]({{< var ref-nerve-root.l5 >}}), [S1]({{< var ref-nerve-root.s1 >}})) @gilroyAtlasAnatomy2020

# Action {#action}

- **TCJ**: Plantarflexion @gilroyAtlasAnatomy2020
- **STJ**: Eversion @gilroyAtlasAnatomy2020
- **Transverse arch**: Support @gilroyAtlasAnatomy2020


The fibularis longus also plays a role in calcaneal frontal plane stabilization.
Although it does not *insert* on the calcaneus, the fibularis longus tendon "hooks" onto the calcaneus allowing it to exert a force upon the calcaneus @jonesProjectFoundations2025.
The fibularis longus tendon can control and prevent excessive calcaneal valgus/abduction @jonesProjectFoundations2025.


# Tendon

"The tendon of the fibularis (peroneus) longus runs superficially behind the lateral malleolus. Resisted pronation and plantar flexion of the foot make the tendon more prominent" @duttonDuttonOrthopaedicExamination2020 