---
title: Muscle tone
---

::: {.callout title="Reading list"}


- Ch 1.1.2 Examination of Muscle Tone @DynamicNeurologicalStabilizationClinicalRehabilitation2014
- Ch3 @sindouNeurosurgerySpasticityPractical2022


In progress:

- Ch55 Spinal Cord Motor Functions;  the Cord Reflexes @hallGuytonHallTextbook2021
- @gangulyMuscleTonePhysiology2021


to review

- Kandel Ch32 @kandelPrinciplesNeuralScience2021


:::

# What is muscle tone?

Muscle tone has many definitions, which can lead to misconceptions of this concept.

In short, muscle tone refers to **a muscle's resistance to a passive stretch when relaxed** @gangulyMuscleTonePhysiology2021.
This resistance is the summation of both an [active contractile component](#active-passive) and a [passive viscoelastic component](#active-passive) @gangulyMuscleTonePhysiology2021.


## Erroneous Definitions

Traditionally, tone refers "the tension in the relaxed muscle" or "the resistance, felt by the examiner during passive stretching of a joint when the muscles are at rest" @gangulyMuscleTonePhysiology2021.
This definition is too ambiguous and different interpretations lead to variation in clinical diagnoses.

- What does resistance to passive stretch mean? @gangulyMuscleTonePhysiology2021
- "Felt by examiner" is too subjective @gangulyMuscleTonePhysiology2021.

Some studies have attempted to define muscle tone as "baseline EMG activity at a relaxed state," but this is imperfect as well @gangulyMuscleTonePhysiology2021.
Muscle tone includes a passive viscoelastic component independent of its active neural activity which is **undetectable by EMG** @gangulyMuscleTonePhysiology2021.


Skeletal muscle tone refers to baseline contraction or "tautness" the skeletal muscles have at rest @hallGuytonHallTextbook2021.


Mathematical definitions have been developed to define muscle tone (see @eq-force-tissue-displacement) @gangulyMuscleTonePhysiology2021.

$$
\textrm{Muscle tone} = \frac{\Delta \textrm{Force}}{\Delta \textrm{Displacement of tissue}}
$$ {#eq-force-tissue-displacement}

$$
R_{\text{total}} = R_{\text{inertia}} + R_{\text{stretch resistance}} + R_{\text{Resistance to velocity}}
$$ {#eq-relaxed-state}

These mathematical definitions make an incorrect assumption that the person is in a *completely* relaxed state, which is almost impossible to achieve without pharmeceuticals @gangulyMuscleTonePhysiology2021.

Bernstein created an alternative definition, by hypothesizing that muscle tone is the "state of preparedness to movement" @gangulyMuscleTonePhysiology2021.
If true, then we should not measure muscle tone by asking a person to fully relax and *not* make any movement @gangulyMuscleTonePhysiology2021.


Carpenter created a similar hypothesis, defining tone as “the constant muscular activity that is necessary as a background to actual movement in order to maintain the basic attitude of the body, particularly against the force of gravity” @gangulyMuscleTonePhysiology2021.



# Introduction

A skeletal muscle consists of the muscle belly and its tendinous insertions.
Skeletal muscles have two main functions:

1. Generate forces to maintain postures or move the body
1. Protect muscle belly and tendon from damage due to excessive tension

Muscle tone is the culmination of mechanisms responding to a stretch to protect the muscle.

The muscle belly can be broken down into two fibers: the extrafusal fibers and intrafusal fibers.
The [extrafusal fibers](#extrafusal-fibers) which we traditionally think of muscle which generate force to move the body.
The [intrafusal fibers](#intrafusal-fibers) perform a sensory role to protect the muscle from damage due to overstretching.


# Extrafusal fibers {#extrafusal-fibers}

Read more about [extrafusal fibers here]({{< var ref-skeletal-muscle.extrafusal-fiber >}})

# Intrafusal fibers {#intrafusal-fibers}

- Terminal ends: Contractile elements
- Middle portion: Receptor elements


Types of Intrafusal fibers:

1. Nuclear Chain fibers
1. Dynamic Nuclear bag fibers
1. Static nuclear bag fibers

Read more about [intrafusal fibers here]({{< var ref-skeletal-muscle.intrafusal-fiber >}})


# Tone Classification

Muscle tone can be classified in different ways.
When classifying tone based on the physiological process inciting the tone, we can create two classifications: [*Postural tone* and *Phasic tone*](#postural-and-phasic-tone) @gangulyMuscleTonePhysiology2021.
we can also view tone based on the processes by which resistance to stretch occurs: [*active* and *Passive* tone](#active-passive) @gangulyMuscleTonePhysiology2021.

## Postural & Phasic tone {#postural-phasic}

**Postural tone** is observed in axial muscles where gravity is the most important inciting factor.
Gravity applies a steady stretch on the muscles and tendons, which is countered by a prolonged muscle contraction known as "postural tone" @gangulyMuscleTonePhysiology2021.

**Phasic tone** is what we commonly think of as "muscle tone" and is found in the extremities @gangulyMuscleTonePhysiology2021.
Phasic tone is observed as a rapid and short duration response resulting from muscle spindle activation following a *rapid* stretch on the tendon and muscle @gangulyMuscleTonePhysiology2021.


# Active & Passive Tone {#active-passive}


## Active (Contractile) Tone {#active-component}

Active tone refers to muscle tone generated by active contraction of the [extrafusal fibers](#extrafusal-fibers).
This active component is regulated by *spinal* and *supraspinal mechanisms* @gangulyMuscleTonePhysiology2021.

::: {.callout-note}
This aspect of tone can be measured by EMG studies @gangulyMuscleTonePhysiology2021.
:::


Dysfunctional increases in active tone is known as a "muscle spasm" @DynamicNeurologicalStabilizationClinicalRehabilitation2014.


## Passive (Connective tissue) Tone {#passive-component}

"The viscoelastic component in turn depends upon multiple factors like the sarcomeric actin-myosin cross-bridges, the viscosity, elasticity, and extensibility of the contractile filaments, filamentous connection of the sarcomeric non-contractile proteins (e.g., desmin, titin), osmotic pressure of the cells, and also on the surrounding connective tissues [3,4]" @gangulyMuscleTonePhysiology2021.


Increased tone in the *connective/passive* components is termed "muscle contracture" @DynamicNeurologicalStabilizationClinicalRehabilitation2014.


# Muscle Stretch Reflex {#muscle-stretch-reflex}



The (muscle) stretch reflex refers to a muscle contraction elicted by a passive muscle stretch (lengthening) @kandelPrinciplesNeuralScience2021.

1. Agonist muscle is stretched
1. Muscle spindle detects stretch
1. Muscle spindle sends sensory afferents to spinal cord
1. Spinal cord sends two signals back:
    1. Inhibition of the motor efferents to the antagonist muscle in order to prevent it from activating and stretching the agonist ([polysynaptic reflex pathway](#polysnaptic-pathway) and *reciprocal inhibition*)
    1. An excitatory motor signal is sent to the agonist muscle to contract and resist the stretch to protect the muscle ([Monosynaptic reflex pathway](#monosynaptic-pathway))

::: {.callout}


Increased complexity:

1. Agonist muscle is stretched
1. Muscle spindle intrafusal fibers are also stretched
    1. Dynamic nuclear bag
    1. Static nuclear bag fibers
    1. Nuclear chain fibers
1. Sensory afferents
    1. Type Ia
    1. Type II
1. Spinal cord synapse
    1. Interneuron
    1. Motor efferent

NOT FINSIHED
:::

- Type Ia afferent makes *direct* excitatory connection on the motor neuron and also synapses on the inhibitory interneuron of the antagonist muscle @kandelPrinciplesNeuralScience2021.
    - The concept of a single efferent having synapses that impact the agonist *and* antagonist is known as "reciprocal innervation" @kandelPrinciplesNeuralScience2021.
    - The inhibition of the antagonist muscle motor efferents prevents the antagonist muscle from resisting the protective stretch reflex @kandelPrinciplesNeuralScience2021


Sherrington performed an experiment on decerebrate reflexes @kandelPrinciplesNeuralScience2021.
Decerebrate preparation was performed: transection of the midbrain between the superior and inferior colliculi @kandelPrinciplesNeuralScience2021.
This disconnects the brain from the spinal cord, which prevents sensory pain afferent signals from reaching the brain and blocks efferent signals from higher brain centers that modulate and maintain normal reflexes @kandelPrinciplesNeuralScience2021.
In a transection like this, the spinal mechanisms are still intact, but the *supraspinal mechanisms* are disconnected.
The result is heightened stretch reflexes known as "decerebrate reflexes" @kandelPrinciplesNeuralScience2021.

Without modulation by the higher brain centers, the descending pathways from the brainstem are *uninhibited* and thus facilitate the stretch reflex circuits @kandelPrinciplesNeuralScience2021.
These facilitate stretch reflex circuits cause a *significant* increase in muscle tone @kandelPrinciplesNeuralScience2021.


::: {.callout-caution}
Kandel makes it seem that these descending pathways from the brainstem only impact the extensor muscles, but I am not sure @kandelPrinciplesNeuralScience2021
:::


## Monosynaptic pathway {#monosynaptic-pathway}


- The monosynaptic pathway refers to the part of the stretch reflex where the sensory afferent synapses directly onto the motor efferent.
- [Type Ia afferents]({{< var ref-type-ia-afferent.path >}}) synapse on the agonist or homonymous muscle as well as heteronymous synergists @kandelPrinciplesNeuralScience2021.

When the Type Ia afferents synapse on on the motor efferents, the Type Ia afferents use *divergence* to make widespread connections to all the homonymous motor efferents, amplifying the motor signal @kandelPrinciplesNeuralScience2021.
A muscle's excitatory to response to its own afferent signalling, is known as autogenic excitation @kandelPrinciplesNeuralScience2021.

The [type Ia afferents]({{< var ref-type-ia-afferent.path >}}) also have excitatory synapses on up to 60% of the motor efferents of the heteronymous synergists @kandelPrinciplesNeuralScience2021.





## Muscle Spindle Sensitivity

Muscle spindle sensitivity is adjusted by sending &gamma;-motor efferents to the contractile ends of the intrafusal fibers, which changes muscle spindle tension.

::: {.callout-note}
When we mention "&gamma;-motor efferents" this includes &gamma;-static motor efferents (&gamma;-s) and &gamma;-dynamic motor efferents (&gamma;-d)
:::



An increase in activity in &gamma;-motor efferent is associated with an increase in muscle spindle activity @kandelPrinciplesNeuralScience2021.
The components involved in changing tension of the muscle spindle via &gamma; motor efferents is known as the "fusimotor system" @kandelPrinciplesNeuralScience2021.


If **only extrafusal fibers are stimulated**, this will result in extrafusal fiber contraction, shortening the muscle and reducing tension on the muscle spindle, resulting in decresed type Ia afferent stimulation.
This sudden drop in tension will reduce sensitivity of the muscle spindle, resulting in decreased proprioception.

When **both extrafusal and intrafusal fibers are stimulated**, the extrafusal and intrafusal fibers contract, resulting in the muscle shortening, but the muscle spindle tension is maintained due to the intrafusal fiber contraction @kandelPrinciplesNeuralScience2021.
This will maintain the firing rate for the type Ia fibers and keeps it in an optimal range for detecting a change in muscle length @kandelPrinciplesNeuralScience2021.
Co-contraction of extrafusal fibers and intrafusal fibers is an important component in many voluntary movements @kandelPrinciplesNeuralScience2021.

But how do we neurologically achieve this intrafusal-extrafusal co-contraction?
There are two methods: 

1. Alpha-gamma co-activation
1. Beta fusimotor system

**Alpha-gamma co-activation** refers to when the &alpha;-motor efferents stimulate the extrafusal fibers and &gamma;-motor neurons stimulate the intrafusal fibers simultaneously.

The **beta fusimotor system** refers to cases when the &alpha;-motor efferent has axon collaterals known as "beta axon collaterals" that extend to **both** extrafusal and intrafusal fibers @kandelPrinciplesNeuralScience2021.
As a result, only &alpha;-motor efferent excitation is required to result in co-contraction of extrafusal and intrafusal fibers @kandelPrinciplesNeuralScience2021.

::: {.callout-note}
Beta innervation of spindles exists in both cats and humans, but it is largely unquantified for most muscles @kandelPrinciplesNeuralScience2021.

:::


"The forced linkage of extrafusal and intrafusal contraction by the beta fusimotor system highlights the importance of the independent fusimotor system (the gamma motor neurons). Indeed, in lower vertebrates, such as amphibians, beta efferents are the only source of intrafusal innervation. Mammals have evolved a mechanism that frees muscle spindles from complete dependence on the behavior of their parent muscles. In principle, this uncoupling allows greater flexibility in controlling spindle sensitivity for different types of motor tasks." @kandelPrinciplesNeuralScience2021

"This conclusion is supported by recordings in spindle sensory axons during a variety of natural movements in cats. The amount and type of activity in gamma motor neurons are set at steady levels, which vary according to the specific task or context. In general, activity levels in both static and dynamic gamma motor neurons (Figure 32–2B) are set at progressively higher levels as the speed and difficulty of the movement increase. Unpredictable conditions, such as when the cat is picked up or handled, lead to marked increases in activity in dynamic gamma motor neurons and thus increased spindle responsiveness when muscles are stretched. When an animal is performing a difficult task, such as walking across a narrow beam, both static and dynamic gamma activation are at high levels (Figure 32–6)." @kandelPrinciplesNeuralScience2021

"Thus, the nervous system uses the fusimotor system to fine-tune muscle spindles so that the ensemble output of the spindles provides information most appropriate for a task. The task conditions under which independent control of alpha and gamma motor neurons occurs in humans have not yet been clearly established." @kandelPrinciplesNeuralScience2021

## Polysnaptic Pathway

"The monosynaptic Ia pathway is not the only spinal reflex pathway activated when a muscle is stretched. Type II sensory fibers from muscle spindles are also activated. These discharge tonically depending on muscle length and gamma motor neuron activity (Box 32–1) and connect to different populations of excitatory and inhibitory interneurons in the spinal cord." @kandelPrinciplesNeuralScience2021

"Some of the interneurons project directly to the spinal motor neurons, whereas others have more indirect connections. Because of the slower conduction velocity of type II sensory fibers and the signal relay through interneurons, the muscular responses elicited by group II fibers are smaller, more variable, and delayed compared to the monosynaptic stretch reflex. Some of the interneurons activated by group II fibers send axons across the midline of the spinal cord and give rise to crossed reflexes. Such connections that cross the midline are important for coordination of bilateral muscle activity in functional motor tasks." @kandelPrinciplesNeuralScience2021

# Golgi Tendon Stretch Reflex

"Golgi Tendon Organs Provide Force-Sensitive Feedback to the Spinal Cord" @kandelPrinciplesNeuralScience2021

"Stimulation of Golgi tendon organs or their Ib sensory fibers in passive animals produces disynaptic inhibition of homonymous motor neurons (autogenic inhibition) and excitation of antagonist motor neurons (reciprocal excitation). Thus, these effects are the exact opposite of the responses evoked by muscle stretch or stimulation of Ia sensory axons." @kandelPrinciplesNeuralScience2021

"This autogenic inhibition is mediated by Ib inhibitory interneurons. These inhibiting interneurons receive their principal input from Golgi tendon organs, sensory receptors that signal the tension in a muscle (Box 32–4), and they make inhibitory connections with homonymous motor neurons. However, stimulation of the Ib sensory fibers from tendon organs in active animals does not always inhibit homonymous motor neurons. Indeed, as we shall see later, stimulation of tendon organs may in certain conditions excite homonymous motor neurons." @kandelPrinciplesNeuralScience2021

"One reason that the reflex actions of the sensory axons from tendon organs are complex in natural situations is that the Ib inhibitory interneurons also receive input from the muscle spindles, cutaneous receptors, and joint receptors (Figure 32–8A). In addition, they receive both excitatory and inhibitory input from various descending pathways." @kandelPrinciplesNeuralScience2021

"Golgi tendon organs were first thought to have a protective function, preventing damage to muscle. It was assumed that they always inhibited homonymous motor neurons and that they fired only when tension in the muscle was high. We now know that these receptors signal minute changes in muscle tension, thus providing the nervous system with precise information about the state of a muscle’s contraction." @kandelPrinciplesNeuralScience2021


"The convergent sensory input from tendon organs, cutaneous receptors, and joint receptors to the Ib inhibitory interneurons (Figure 32–8A) may allow for precise spinal control of muscle force in activities such as grasping a delicate object. Additional input from cutaneous receptors may facilitate activity in the Ib inhibitory interneurons when the hand reaches an object, thus reducing the level of muscle contraction and permitting a soft grasp." @kandelPrinciplesNeuralScience2021

"As is the case with the Ia fibers from muscle spindles, the Ib fibers from tendon organs form widespread connections with motor neurons that innervate muscles acting at different joints. Therefore, the connections of the sensory fibers from tendon organs with the Ib inhibitory interneurons are part of spinal networks that regulate movements of whole limbs." @kandelPrinciplesNeuralScience2021

::: {.callout}
"Golgi tendon organs are slender encapsulated structures approximately 1 mm long and 0.1 mm in diameter located at the junction between skeletal muscle fibers and tendon. Each capsule encloses several braided collagen fibers connected in series to a group of muscle fibers." @kandelPrinciplesNeuralScience2021

"Each tendon organ is innervated by a single Ib axon that branches into many fine endings inside the capsule; these endings become intertwined with the collagen fascicles (Figure 32–7A). " @kandelPrinciplesNeuralScience2021

"Stretching of the tendon organ straightens the collagen fibers, thus compressing the Ib nerve endings and causing them to fire. Because the nerve endings are so closely associated with the collagen fibers, even very small stretches of the tendons can compress the nerve endings. " @kandelPrinciplesNeuralScience2021

"Whereas muscle spindles are most sensitive to changes in length of a muscle, tendon organs are most sensitive to changes in muscle tension. Contraction of the muscle fibers connected to the collagen fiber bundle containing the receptor is a particularly potent stimulus to a tendon organ. The tendon organs are thus readily activated during normal movements. This has been demonstrated by recordings from single Ib axons in humans making voluntary finger movements and in cats walking normally." @kandelPrinciplesNeuralScience2021

"Studies in anesthetized animal preparations have shown that the average level of activity in the population of tendon organs in a muscle is a good index of the total force in a contracting muscle (Figure 32–7B). This close agreement between firing frequency, and force is consistent with the view that the tendon organs continuously measure the force in a contracting muscle." @kandelPrinciplesNeuralScience2021

:::



# Cutaneous Reflexes Produce Complex Movements That Serve Protective and Postural Functions

"Most reflex pathways involve interneurons. One such reflex pathway is that of the flexion-withdrawal reflex, in which a limb is quickly withdrawn from a painful stimulus. Flexion-withdrawal is a protective reflex in which a discrete stimulus causes all the flexor muscles in that limb to contract coordinately. We know that this is a spinal reflex because it persists after complete transection of the spinal cord." @kandelPrinciplesNeuralScience2021

"The sensory signal of the flexion-withdrawal reflex activates divergent polysynaptic reflex pathways. One excites motor neurons that innervate flexor muscles of the stimulated limb, whereas another inhibits motor neurons that innervate the limb’s extensor muscles (Figure 32–1B). This reflex can produce an opposite effect in the contralateral limb, that is, excitation of extensor motor neurons and inhibition of flexor motor neurons. This crossed-extension reflex serves to enhance postural support during withdrawal of a foot from a painful stimulus. Activation of the extensor muscles in the opposite leg counteracts the increased load caused by lifting the stimulated limb. Thus, flexion-withdrawal is a complete, albeit simple, motor act." @kandelPrinciplesNeuralScience2021


"Although flexion reflexes are relatively stereotyped, both the spatial extent and the force of muscle contraction depend on stimulus intensity. Touching a stove that is slightly hot may produce moderately fast withdrawal only at the wrist and elbow, whereas touching a very hot stove invariably leads to a forceful contraction at all joints, leading to rapid withdrawal of the entire limb. The duration of the reflex usually increases with stimulus intensity, and the contractions produced in a flexion reflex always outlast the stimulus." @kandelPrinciplesNeuralScience2021

"Because of the similarity of the flexion-withdrawal reflex to stepping, it was once thought that the flexion reflex is important in producing contractions of flexor muscles during walking. We now know, however, that a major component of the neural control system for walking is a set of intrinsic spinal circuits that do not require sensory stimuli (Chapter 33). Nevertheless, in mammals, the intrinsic spinal circuits that control walking share many of the interneurons involved in flexion reflexes." @kandelPrinciplesNeuralScience2021

# Convergence of Sensory Inputs on Interneurons Increases the Flexibility of Reflex Contributions to Movement

"The Ib inhibitory interneuron is not the only interneuron that receives convergent input from many different sensory modalities. An enormous diversity of sensory information converges on interneurons in the spinal cord, enabling them to integrate information from muscle, joints, and skin." @kandelPrinciplesNeuralScience2021

"Interneurons activated by groups I and II sensory fibers have received special attention. It was thought for some time that excitatory and inhibitory interneurons activated by group II fibers could be distinguished from those activated by group Ib afferents, but it is now believed that this distinction has to be abandoned and that groups I and II fibers converge on common populations of interneurons that integrate force and length information from the active muscle and thereby help coordinate muscle activity according to the length of the muscle, its activity level, and the external load." @kandelPrinciplesNeuralScience2021

# Voluntary movement

"Sensory Feedback and Descending Motor Commands Interact at Common Spinal Neurons to Produce Voluntary Movements"


"As pointed out by Michael Foster in his 1879 physiology textbook, it must be an “economy to the body” that the will should make use of the networks in the spinal cord to generate coordinated movements “rather than it should have recourse to an apparatus of its own of a similar kind.” Research in the subsequent 140 years has confirmed this conjecture. " @kandelPrinciplesNeuralScience2021

"The first evidence came from intracellular recordings of synaptic potentials elicited in cat spinal motor neurons by combined and separate stimulation of sensory fibers and descending pathways. When separate stimuli are reduced in intensity to just below threshold for evoking a synaptic potential, combining the stimulations at appropriate intervals makes the synaptic potential reappear. This provides evidence of convergence of the sensory fibers and the descending pathways onto common interneurons in the reflex pathway (see Figure 13–14). Direct recordings from spinal interneurons have confirmed this, as have noninvasive Hoffmann reflex tests in human subjects (Figure 32–9). " @kandelPrinciplesNeuralScience2021

"Direct evidence that sensory feedback helps to shape voluntary motor commands through spinal reflex networks in humans comes from experiments in which sensory activity in length- and force-sensitive afferents has suddenly been reduced or abolished. This can be done by suddenly unloading or shortening a muscle during a voluntary contraction. The short latency of the consequent reduction in muscle activity can only be explained by sensory activity through a reflex pathway that directly contributes to the muscle activity." @kandelPrinciplesNeuralScience2021

## Muscle Spindle Sensory Afferent Activity Reinforces Central Commands for Movements Through the Ia Monosynaptic Reflex Pathway

"Stretch reflex pathways can contribute to the regulation of motor neurons during voluntary movements and during maintenance of posture because they form closed feedback loops. For example, stretching a muscle increases activity in spindle sensory afferents, leading to muscle contraction and consequent shortening of the muscle. Muscle shortening in turn leads to decreased activity in spindle afferents, reduction of muscle contraction, and lengthening of the muscle. " @kandelPrinciplesNeuralScience2021

"The stretch reflex loop thus acts continuouslythe output of the system, a change in muscle length, becomes the input—tending to keep the muscle close to a desired or reference length. The stretch reflex pathway is a negative feedback system, or servomechanism, because it tends to counteract or reduce deviations from the reference value of the regulated variable. " @kandelPrinciplesNeuralScience2021

"In 1963, Ragnar Granit proposed that the reference value in voluntary movements is set by descending signals that act on both alpha and gamma motor neurons. The rate of firing of alpha motor neurons is set to produce the desired shortening of the muscle, and the rate of firing of gamma motor neurons is set to produce an equivalent shortening of the intrafusal fibers of the muscle spindle. If the shortening of the whole muscle is less than what is required by a task, as when the load is greater than anticipated, the sensory fibers increase their firing rate because the contracting intrafusal fibers are stretched (loaded) by the relatively greater length of the whole muscle. If shortening is greater than necessary, the sensory fibers decrease their firing rate because the intrafusal fibers are relatively slackened (unloaded) (Figure 32–10A). " @kandelPrinciplesNeuralScience2021

"In theory, this mechanism could permit the nervous system to produce movements of a given distance without having to know in advance the actual load or weight being moved. In practice, however, the stretch reflex pathways do not have sufficient control over motor neurons to overcome large unexpected loads. This is immediately obvious if we consider what happens when we attempt to lift a heavy suitcase that we believe to be empty. Automatic compensation for the greater-than-anticipated load does not occur. Instead, we have to pause briefly to plan a new movement with much greater muscle activation. " @kandelPrinciplesNeuralScience2021

"Strong evidence that alpha and gamma motor neurons are co-activated during voluntary human movement comes from direct measurements of the activity of the sensory fibers from muscle spindles. In the late 1960s, Åke Vallbo and Karl-Erik Hagbarth developed microneurography, a technique for recording from the largest afferent fibers in peripheral nerves. Vallbo later found that during slow movements of the fingers the large-diameter Ia fibers from spindles in the contracting muscles increase their rate of firing even when the muscle shortens as it contracts (Figure 32–10B). This occurs because the gamma motor neurons, which have direct excitatory connections with spindles, are coactivated with alpha motor neurons." @kandelPrinciplesNeuralScience2021

"Furthermore, when subjects attempt to make slow movements at a constant velocity, the firing of the Ia fibers mirrors the small deviations in velocity in the trajectory of the movements (sometimes the muscle shortens quickly and at other times more slowly). When the velocity of flexion increases transiently, the rate of firing in the fibers decreases because the muscle is shortening more rapidly and therefore exerts less tension on the intrafusal fibers. When the velocity decreases, firing increases because the muscle is shortening more slowly, and therefore, the relative tension on the intrafusal fibers increases. This information can be used by the nervous system to compensate for irregularities in the movement trajectory by exciting the alpha motor neurons." @kandelPrinciplesNeuralScience2021

## Modulation of Ia inhibitory Interneurons and Renshaw Cells by Descending Inputs Coordinate Muscle Activity at Joints

"Reciprocal innervation is useful not only in stretch reflexes but also in voluntary movements. Relaxation of the antagonist muscle during a movement enhances speed and efficiency because the muscles that act as prime movers are not working against the contraction of opposing muscles." @kandelPrinciplesNeuralScience2021

"The Ia inhibitory interneurons receive inputs from collaterals of the axons of neurons in the motor cortex that make direct excitatory connections with spinal motor neurons. This organizational feature simplifies the control of voluntary movements, because higher centers do not have to send separate commands to the opposing muscles." @kandelPrinciplesNeuralScience2021

"It is sometimes advantageous to contract both the prime mover and the antagonist at the same time. Such co-contraction has the effect of stiffening the joint and is most useful when precision and joint stabilization are critical. An example of this phenomenon is the co-contraction of flexor and extensor muscles of the elbow immediately before catching a ball. The Ia inhibitory interneurons receive both excitatory and inhibitory signals from all of the major descending pathways (Figure 32–11A). By changing the balance of excitatory and inhibitory inputs onto these interneurons, supraspinal centers can modulate reciprocal inhibition of muscles and enable co-contraction, thus controlling the relative amount of joint stiffness to meet the requirements of the motor act." @kandelPrinciplesNeuralScience2021

"The activity of spinal motor neurons is also regulated by another important class of inhibitory interneurons, the Renshaw cells. Excited by collaterals of the axons of motor neurons and receiving significant synaptic input from descending pathways, Renshaw cells make inhibitory synaptic connections with several populations of motor neurons, including the motor neurons that excite them, as well as Ia inhibitory interneurons (Figure 32–11B). The connections with motor neurons form a negative feedback system that regulates the firing rate of the motor neurons, whereas the connections with the Ia inhibitory interneurons regulate the strength of inhibition of antagonistic motor neurons, for instance in relation to co-contraction of antagonists. The distribution of projections from Renshaw cells to different motor nuclei also facilitate that muscle activity is coordinated in functional synergies during movement." @kandelPrinciplesNeuralScience2021


## Transmission in Reflex Pathways May Be Facilitated or Inhibited by Descending Motor Commands

"As we have seen, in an animal at rest, the Ib sensory fibers from extensor muscles have an inhibitory effect on homonymous motor neurons. During locomotion, they produce an excitatory effect on those same motor neurons because transmission in the disynaptic inhibitory pathway is depressed (Figure 32–8B), while at the same time transmission through excitatory interneurons is facilitated." @kandelPrinciplesNeuralScience2021

"This phenomenon, called state-dependent reflex reversal, illustrates how transmission in spinal circuit is regulated by descending motor commands to meet This phenomenon, called state-dependent reflex reversal, illustrates how transmission in spinal circuit is regulated by descending motor commands to meet" @kandelPrinciplesNeuralScience2021

"State-dependent reflex reversal has also been demonstrated in humans. Stimulation of skin and muscle afferents from the foot produces facilitation of muscles that lift the foot early in the swing phase, but suppresses activity of the same muscles late in the swing phase. Both effects make good functional sense. Early in the swing phase, positive feedback from the foot will help to lift the foot over an obstacle, whereas suppression of the same muscles in late swing will help to lower the foot quickly to the ground so that the obstacle may be passed using the opposite leg first." @kandelPrinciplesNeuralScience2021

## Descending Inputs Modulate Sensory Input to the Spinal Cord by Changing the Synaptic Efficiency of Primary Sensory Fibers

"In the 1950s and early 1960s, John C. Eccles and his collaborators demonstrated that monosynaptic excitatory postsynaptic potentials (EPSPs) elicited in cat spinal motor neurons by stimulation of Ia sensory fibers become smaller when other Ia fibers are stimulated. This led to the discovery in the spinal cord of several groups of GABAergic inhibitory interneurons that exert presynaptic inhibition of primary sensory neurons (Figure 32–12). Some interneurons inhibit mainly Ia sensory axons, whereas others inhibit mainly Ib axons or sensory fibers from skin." @kandelPrinciplesNeuralScience2021

"The principal mechanism responsible for sensory inhibition is a depolarization of the primary terminal caused by an inward Cl− current when GABAergic receptors on the terminal are activated. This depolarization inactivates some of the Na+ channels in the terminal, so the action potentials that reach the synapse are reduced in size. The effect of this is that release of neurotransmitter from the sensory afferent is diminished." @kandelPrinciplesNeuralScience2021

"When tested by stimulation of peripheral afferents, presynaptic inhibition is widespread in the spinal cord and affects primary afferents from all muscles in a limb. However, similar to other interneurons, the neurons responsible for presynaptic inhibition are also controlled by descending pathways, making possible a much more focused modulation of presynaptic inhibition in relation to movement. Presynaptic inhibition at the synapse of Ia axons with motor neurons of the muscles that are activated as part of a movement is reduced at the onset of movement. In contrast, presynaptic inhibition of Ia axons on motor neurons connected to inactive muscles is increased. One example of this selective modulation is increased presynaptic inhibition of Ia axons at their synapse with antagonist motor neurons, which explains part of the reduction of stretch reflexes in antagonist muscles at the onset of agonist contraction. In this way, the nervous system takes advantage of the widespread connectivity of Ia axons, using presynaptic inhibition to shape activity in the Ia afferent network to facilitate activation of specific muscles." @kandelPrinciplesNeuralScience2021

"Presynaptic inhibition provides a mechanism by which the nervous system can reduce sensory feedback predicted by the motor command, while allowing unexpected feedback access to the spinal motor circuit and the rest of the nervous system. In line with this function, presynaptic inhibition of Ia sensory axons from muscle spindles generally increases during movements that are highly predictable, such as walking and running." @kandelPrinciplesNeuralScience2021

"Finally, presynaptic inhibition may help stabilize the execution of movements by preventing excessive sensory feedback and associated self-reinforcing oscillatory activity." @kandelPrinciplesNeuralScience2021


# Part of the Descending Command for Voluntary Movements Is Conveyed Through Spinal Interneurons

"In cats as well as most other vertebrates, the corticospinal tract has no direct connections to spinal motor neurons; all the descending commands have to be channeled through spinal interneurons that are also part of reflex pathways. Humans and Old World monkeys are the only species in which corticospinal neurons make direct connections with the spinal motor neurons in the ventral horn of the spinal cord. Even in these species, a considerable fraction of the corticospinal tract fibers terminate in the intermediate nucleus on spinal interneurons, and the corticospinal fibers that terminate on motor neurons also have collaterals that synapse on interneurons. A considerable part of each descending command for movement in the corticospinal tract therefore has to be conveyed through spinal interneurons—and integrated with sensory activity—before reaching the motor neurons." @kandelPrinciplesNeuralScience2021


## Propriospinal Neurons in the C3–C4 Segments Mediate Part of the Corticospinal Command for Movement of the Upper Limb

"In the 1970s, Anders Lundberg and his collaborators demonstrated that a group of neurons in the C3–C4 spinal segments of the cat spinal cord send their axons to motor neurons located in more caudal cervical segments (Figure 32–13). Since the neurons in the C3–C4 segments project to motor neurons that innervate a range of forelimb muscles controlling different joints, and receive input from both skin and muscles throughout the forelimb, they are named propriospinal neurons. In addition to sensory input from skin and muscle afferents, the C3–C4 propriospinal neurons are activated by collaterals from the corticospinal tract and thereby relay disynaptic excitation from the motor cortex to the spinal motor neurons." @kandelPrinciplesNeuralScience2021


"Subsequent experiments by Bror Alstermark in Sweden and Tadashi Isa in Japan have confirmed that similar propriospinal neurons also exist in the C3–C4 segments of the monkey spinal cord and are involved in mediating at least part of the motor command for reaching. Noninvasive experiments have also provided indirect evidence of the existence of C3–C4 propriospinal neurons in the human spinal cord. With the evolution of direct monosynaptic corticomotor connections in monkeys and humans, the corticospinal transmission through this disynaptic pathway may have become less important." @kandelPrinciplesNeuralScience2021

"Lumbar interneurons that receive input from groups I and II sensory axons from muscle also receive significant input from descending motor tracts and provide excitatory projections to spinal motor neurons. These interneurons thus convey part of the indirect motor command for voluntary movements to the spinal motor neurons that control leg muscles and may be a lumbar equivalent of the C3–C4 propriospinal neurons in the cervical spinal cord." @kandelPrinciplesNeuralScience2021

## Neurons in Spinal Reflex Pathways Are Activated Prior to Movement

"Synaptic transmission in spinal reflex pathways may change in response to the intention to move, independent of movement. Intracellular recordings from active monkeys have demonstrated that the intention to make a movement modifies activity in interneurons in the spinal cord and alters transmission in spinal reflex pathways. Similarly, in human subjects who have been prevented from contracting a muscle (by injection of lidocaine into the peripheral nerve supplying the muscle), the voluntary effort to contract the muscle still changes transmission in reflex pathways as if the movement had actually taken place." @kandelPrinciplesNeuralScience2021

"In both humans and monkeys, spinal interneurons also change their activity well in advance of the actual movement. For example, in human subjects, Hoffmann reflexes elicited in a muscle that is about to be activated are facilitated fully 50 ms prior to the onset of contraction and remain facilitated throughout the movement. Conversely, reflexes in the antagonist muscles are suppressed. The suppression of stretch reflexes in the antagonist muscle prior to the onset of movement is an efficient way of preventing the antagonist from being reflexively activated when it is stretched at the onset of the agonist contraction." @kandelPrinciplesNeuralScience2021

"Transmission in spinal reflex pathways can also be modified in connection with higher cognitive functions. Two examples are (1) an increase in the tendon jerk reflex in the soleus muscle of a human subject imagining pressing a foot pedal and (2) modulation of the Hoffmann reflex in arm and leg muscles while a subject observes grasping and walking movements, respectively." @kandelPrinciplesNeuralScience2021

# Physiology

::: {.callout}
Skeletal muscles do not contract without the action potential from the fibers, this tone is the product of low rate nerve impulses from the spinal cord @hallGuytonHallTextbook2021.
These *low level nerve impulses* are modulated partially by the brain and partially by the muscle spindles @hallGuytonHallTextbook2021.
The brain sends afferent signals to the anterior motoneurons of the spinal cord @hallGuytonHallTextbook2021.
The muscle spindle within the skeletal muscle sends signals to the muscle belly itself @hallGuytonHallTextbook2021.
:::






::: {.callout}

- See Chapter 55 @hallGuytonHallTextbook2021 for an in depth explanation of 

:::

# Regulation

| Level | Structures |
|-|-|
| [Supraspinal](#supraspinal-control) | Interaction between facilitory and inhibitory long tracts and cerebellum |
| [Spinal](#spinal-control) | Interaction between muscle spindle, spinal cord, and interneurons |
: @gangulyMuscleTonePhysiology2021 {.striped}

## Supraspinal control {#supraspinal-control}

The cerebellum plays an important role in modulation of muscle tone @DynamicNeurologicalStabilizationClinicalRehabilitation2014.

A number of transmitters play a role in modulating muscle tone:

- Glutamate: Glutamate is an **excitatory** neurotransmitter released in the [corticospinal tract]({{< var ref-corticospinal-tract.path >}}) and [type Ia afferent fibers]({{< var ref-type-ia-afferent.path >}}) @DynamicNeurologicalStabilizationClinicalRehabilitation2014.
- Gamma Aminobutyric Acid (GABA): GABA is an **inhibitory** neurotransmitter @DynamicNeurologicalStabilizationClinicalRehabilitation2014.
    - GABA is released on the interneurons of the posterior spinal horns @DynamicNeurologicalStabilizationClinicalRehabilitation2014.
    - Presynaptic inhibition decreases afferent signalling and thus decreases glutamate release @DynamicNeurologicalStabilizationClinicalRehabilitation2014.
- Catecholamines & serotonin: These regulate spinal reflexes @DynamicNeurologicalStabilizationClinicalRehabilitation2014.


## Spinal control {#spinal-control}


## Stretch detection

Spinal control is dependent on sensory afferents providing information about a stretch a certain muscle and its tendon are experiencing.
The intrafusal fibers of the [muscle spindle]({{< var ref-muscle-spindle.path >}}) detect change and rate of change in muscle length while the [golgi tendon organ (GTO)]({{< var ref-golgi-tendon-organ.path >}}) are located in the tendon and detect tendon stretching @gangulyMuscleTonePhysiology2021.

During a dynamic stretch, the muscle spindle detects changes in muscle length and transmits these signals via *type Ia afferents* @gangulyMuscleTonePhysiology2021.

Tonic activity during Steady-state length is a static response which is transmitted through both *type Ia* and *type II* afferents @gangulyMuscleTonePhysiology2021.

Tendon stretching detected by the [GTOs]({{< var ref-golgi-tendon-organ.path >}}) is transmitted to the spinal cord via *type Ib afferents* @gangulyMuscleTonePhysiology2021.


## Stretch-reflex

::: {.callout title="Reading list"}

- Ch32 p762 @kandelPrinciplesNeuralScience2021
- 

:::

These muscle spindle signals travelling through [type Ia]({{< var ref-type-ia-afferent.path >}}) and [II]({{< var ref-type-ii-afferent.path >}}) active the *stretch-reflex* @gangulyMuscleTonePhysiology2021.
A motor efferent signal is transmitted through [alpha-motor (&alpha;-motor)]({{< var ref-alpha-motor-neuron.path >}}) and [gamma-motor (&gamma;-motor)]({{< var ref-gamma-motor-neuron.path >}}) neurons @gangulyMuscleTonePhysiology2021.
The [&alpha;-motor neurons]({{< var ref-alpha-motor-neuron.path >}}) activate the [extrafusal fibers]({{< var ref-skeletal-muscle.extrafusual-fibers >}}) @gangulyMuscleTonePhysiology2021.
The [&gamma;-motor neurons]({{< var ref-gamma-motor-neuron.path >}}) activate the [intrafusal fibers]({{< var ref-skeletal-muscle.intrafusul-fibers >}}) @gangulyMuscleTonePhysiology2021.

The stretch reflex can come in 2 forms: **Dynamic** or **static** @gangulyMuscleTonePhysiology2021.


### Dynamic stretch reflex
The dynamic type of *stretch reflex* is created when a muscle is suddenly and rapidly stretched @gangulyMuscleTonePhysiology2021.
This change in rate/velocity stimulates the annulospiral endings and the sigmal is transmitted via *nuclear bag fibers* and [type Ia afferents]({{< var ref-type-ia-afferent.path >}}) to the spinal cord @gangulyMuscleTonePhysiology2021.

At the spinal cord, the afferent stretch signal is received, processed, and an efferent motor signal is created @gangulyMuscleTonePhysiology2021.
The efferent motor signal is sent through [&alpha;-motor efferents]({{< var ref-alpha-motor-neuron.path >}})

Efferent motor signal from the spinal cord through [&alpha;-motor neurons]({{< var ref-alpha-motor-efferent.path >}}) to extrafusal fibers, resulting in sudden, *synchronous* contraction of the muscle known as the dynamic stretch reflex @gangulyMuscleTonePhysiology2021.
The synchonicity of the contract makes the muscle have a strong contractile response @gangulyMuscleTonePhysiology2021.

::: {.callout-tip}
This process is the basis of producing deep tendon reflexes @gangulyMuscleTonePhysiology2021.
:::

### Sustained Stretch Reflex

During a sustained stretch, we elicit a *sustained stretch reflex* which is known as 

"On the other hand, sustained stretch of the muscle stimulates nuclear chain fibers and type II afferents (flowerspray endings) carry the signal to cord. 
Efferent signal from the cord travels via alpha efferents to extrafusal fibers. 
However, this time there will be asynchronous contraction of the extrafusal muscle fibers (motor units not discharging all together) that will result in mild sustained contraction of these fibers as long as it is stretched. 
This static stretch reflex response is the physiological basis of maintaining muscle tone" @gangulyMuscleTonePhysiology2021



# Static response loop

- &gamma;-s motor efferents
- Nuclear chain fibers

# Dynamic response loop


- &gamma;-d motor efferents
- Nuclear bag fibers

# Dysfunction


::: {.callout title="Reread"}
Tone dysfunction can be divided into hypertonia, paratonia, or dystonia.

*Spasticity* and *rigidity* are the two types of hypertonia.
These forms of hypertonia result from dysfunction in the supraspinal pathways and the interaction between spinal cord and muscle spindle @gangulyMuscleTonePhysiology2021.

Dystonia and paratonia are *not* related to physiological dysfunction in tone pathways @gangulyMuscleTonePhysiology2021.
The other two disorders of altered tone, namely dystonia and paratonia, are not exactly related to the physiological dysfunction of the tone pathways @gangulyMuscleTonePhysiology2021.

In the motor control system, spasticity and rigidity are primarily an "output system" problem, whereas *dystonia* is a "system level processing" problem @gangulyMuscleTonePhysiology2021.

Dystonia and paratonia have altered tone secondary to network disruption in the basal ganglia, the thalamocortical circuits, and their connections.
:::



According to the *IAB-Interdisciplinary Working Group for Movement Disorders* @dresslerDefiningSpasticityNew2018, spasticity is used as a general term to describe "involuntary muscle hyperactivity in the presence of central paresis" @dresslerDefiningSpasticityNew2018.

Within this "involuntary muscle hyperactivity" includes: *spasticity sensu strictu*, rigidity, dystonia, spasms, or a combination of these @dresslerDefiningSpasticityNew2018.

- [**Spasticity sensu strictu**](#spasticity-sensu-strictu): Muscle hyperactivity triggered by *rapid passive joint movement* @dresslerDefiningSpasticityNew2018.
- [**Rigidity**](#rigidity): Muscle hyperactivity triggered by *slow passive joint movement* @dresslerDefiningSpasticityNew2018.
- [**Dystonia**](#dystonia) refers to *spontaneous* involuntary muscle hyperactivity @dresslerDefiningSpasticityNew2018.
- [**Spasms**](#spasm): Complex involuntary muscle activity triggered by acoustic or sensory stimuli @dresslerDefiningSpasticityNew2018.




::: {#tbl-spasticity-rigidity}
<table class="basic-table">
  <thead>
    <tr>
      <th>Differentiating points</th>
      <th>Spasticity</th>
      <th>Rigidity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Velocity dependency</td>
      <td>Yes</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Resistance to movement</td>
      <td>Unidirectional <br> (flexion or extension)</td>
      <td>Bidirectional</td>
    </tr>
    <tr>
      <td>Length dependency</td>
      <td>Yes</td>
      <td>No</td>
    </tr>
    <tr>
      <td>Type of hypertonicity</td>
      <td><em>Clasp-knife</em></td>
      <td><em>Lead pipe</em> or <em>Cog-wheel</em></td>
    </tr>
  </tbody>
</table>

Spasticity versus rigidity @gangulyMuscleTonePhysiology2021
:::


::: {#tbl-pathophysiology-spasticity-rigidity-dystonia-paratonia}

<table class="basic-table">
    <thead>
        <tr>
            <th>Tone Abnormalities</th>
            <th colspan="2">Basic Pathophysiology</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="4">[Spasticity]({{< var ref-spasticity.path >}})</td>
            <td>1</td>
            <td>Alterations in spinal excitatory and spinal inhibitory circuitry resulting in increased excitation and decreased inhibition</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Supraspinal influence primarily involving inhibitory drive from dorsal reticulospinal tract and facilitatory drive from medial reticulospinal tract</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Abnormal sensory feedback</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Non-neural or "passive" factors such as viscoelastic properties of muscle and surrounding connective tissue</td>
        </tr>
        <tr style="border-top: 1px solid black;">
            <td rowspan="5">[Rigidity]({{< var ref-rigidity.path >}})</td>
            <td>1</td>
            <td>Exaggeration of long-latency stretch reflexes (LLSR)</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Enhancement of *shortening reaction (SR)* and *stretch-induced inhibition (SII)*</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Dysfunction of brainstem circuitry </br> (sublaterodorsal nucleus, nucleus reticularis gigantocellularis (NRGC), locus coeruleus, caudal raphse, and pedunculopontine nucleus)</td>
        </tr>
        <tr>
            <td>4</td>
            <td></td>
        </tr>
        <tr>
            <td>5</td>
            <td></td>
        </tr>
        <tr style="border-top: 1px solid black;">
            <td rowspan="4">[Dystonia]({{< var ref-dystonia.path >}})</td>
            <td>1</td>
            <td></td>
        </tr>
        <tr>
            <td>2</td>
            <td></td>
        </tr>
        <tr>
            <td>3</td>
            <td></td>
        </tr>
        <tr>
            <td>4</td>
            <td></td>
        </tr>
        <tr style="border-top: 1px solid black;">
            <td rowspan="2">[Paratonia]({{< var ref-paratonia.path >}})</td>
            <td>1</td>
            <td></td>
        </tr>
        <tr>
            <td>2</td>
            <td></td>
        </tr>
    </tbody>
</table>

Pathophysiological basis of spasticity, rigidity, dystonia, and paratonia @gangulyMuscleTonePhysiology2021

:::



| Manifestations | Pyramidal Motor Syndrome | Extrapyramidal Motor Syndrome |
|-|-|-|
| Unilateral movement | Paralysis of voluntary movement | Little-to-No paralysis of voluntary movement |
| tendon reflexes | Increased | Normal or *slightly* increased |
| Babinski Sign | Present | Absent |
| Involuntary movements | Absence of involuntary movements | Tremors, chorea, athetosis, or dystonia |
| Muscle tone | Spasticity in muscles (e.g. clasp knife phenomenon) | Plastic rigidity (equal throughout movement) or *intermittent-cogwheel rigidity* (generalized but predominantly in flexors of limbs and trunk) |
| | Hypertonia present in flexors of arms and extensors of legs | Hypotonia, weakness, and gait disturbances in cerebellar disease |
: Pyramidal versus Extrapyramidal motor syndrome @huetherUnderstandingPathophysiology2020 {.striped}

# CNS Dysfunction

"Damage to the Central Nervous System Produces Characteristic Alterations in Reflex Responses" @kandelPrinciplesNeuralScience2021

"Stretch reflexes are routinely used in clinical examinations of patients with neurological disorders. They are typically elicited by sharply tapping the tendon of a muscle with a reflex hammer. Although the responses are often called tendon reflexes or tendon jerks, the receptor that is stimulated, the muscle spindle, actually lies in the muscle rather than the tendon. Only the primary sensory fibers in the spindle participate in the tendon reflex, for these are selectively activated by a rapid stretch of the muscle produced by the tendon tap." @kandelPrinciplesNeuralScience2021

"Measuring alterations in the strength of the stretch reflex can assist in the diagnosis of certain conditions and in localizing injury or disease in the central nervous system. Absent or hypoactive stretch reflexes often indicate a disorder of one or more of the components of the peripheral reflex pathway: sensory or motor axons, the cell bodies of motor neurons, or the muscle itself (Chapter 57). Nevertheless, because the excitability of motor neurons is dependent on descending excitatory and inhibitory signals, absent or hypoactive stretch reflexes can also result from lesions of the central nervous system. Hyperactive stretch reflexes, conversely, always indicate that the lesion is in the central nervous system." @kandelPrinciplesNeuralScience2021


## Interruption of Descending Pathways to the Spinal Cord Frequently Produces Spasticity

"The force with which a muscle resists being lengthened depends on the muscle’s intrinsic elasticity, or stiffness. Because a muscle has elastic elements in series and parallel that resist lengthening, it behaves like a spring (Chapter 31). In addition, connective tissue in and around the muscle may also contribute to its stiffness. These elastic elements may be pathologically altered following brain and spinal cord injury and thereby cause contractures and abnormal joint positions. However, there is also a neural contribution to the resistance of a muscle to stretch; the feedback loop inherent in the stretch reflex pathway acts to resist lengthening of the muscle." @kandelPrinciplesNeuralScience2021

"Spasticity is characterized by hyperactive tendon jerks and an increase in resistance to rapid stretching of the muscle. Slow movement of a joint elicits only passive resistance, which is caused by the elastic properties of the joint, tendon, muscle, and connective tissues. As the speed of the stretch is increased, resistance to the stretch rises progressively. This phasic relation is what characterizes spasticity; an active reflex contraction occurs only during a rapid stretch, and when the muscle is held in a lengthened position, the reflex contraction subsides." @kandelPrinciplesNeuralScience2021


"Spasticity is seen following lesion of descending motor pathways caused by stroke, injuries of the brain or spinal cord, and degenerative diseases such as multiple sclerosis. It is also seen in individuals with brain damage that occurs before, during, or shortly after birth, resulting in cerebral palsy." @kandelPrinciplesNeuralScience2021

"Spasticity is not seen immediately following lesions of descending pathways, but develops over days, weeks, and even months. This parallels plastic changes at multiple sites in the stretch reflex circuitry. Sensory group Ia axons release more transmitter substance when active, and the alpha motor neurons change their intrinsic properties and their morphology (dendritic sprouting and denervation hypersensitivity) so that they become more excitable. Changes in excitatory and inhibitory interneurons that project to the motor neurons also take place and probably contribute to the increased excitability." @kandelPrinciplesNeuralScience2021

::: {.callout}
See [Brunnstrom stages of recovery]({{< var ref-brunnstrom-stages-of-recovery.path >}})
:::


"Whatever the precise mechanisms that produce spasticity, the effect is a strong facilitation of transmission in the monosynaptic reflex pathway. It is not the only reflex pathway affected by lesions of descending motor pathways. Pathways involving group I/II interneurons and sensory fibers from skin are also affected and exhibit the symptomatology observed in patients with central motor lesions. In the clinic, spasticity is therefore used in a broader sense and does not only relate to stretch reflex hyperexcitability. It is still debated whether reflex hyperexcitability contributes to the movement disorder following lesion of descending pathways or whether it may be a pertinent adaptation that helps to activate the muscles when descending input is diminished." @kandelPrinciplesNeuralScience2021


## Lesion of the Spinal Cord in Humans Leads to a Period of Spinal Shock Followed by Hyperreflexia

"Damage to the spinal cord can cause large changes in the strength of spinal reflexes. Each year, approximately 11,000 Americans sustain spinal cord injuries, and many more suffer from strokes. More than half of these injuries produce permanent disability, including impairment of motor and sensory functions and loss of voluntary bowel and bladder control. Approximately 250,000 people in the United States today have some permanent disability from spinal cord injury" @kandelPrinciplesNeuralScience2021

"When the spinal cord is completely transected, there is usually a period immediately after the injury when all spinal reflexes below the level of the transection are reduced or completely suppressed, a condition known as spinal shock. During the course of weeks and months, spinal reflexes gradually return, often greatly exaggerated. For example, a light touch to the skin of the foot may elicit strong flexion withdrawal of the leg." @kandelPrinciplesNeuralScience2021

# Examination

::: {.callout}

- Re-read
    - Ch "Examination of muscle tone" @DynamicNeurologicalStabilizationClinicalRehabilitation2014
:::

- Velocity dependency
- Resistance to movement
- Length dependency
- Type of hypertonicity





# Orthopedic "Tone"

Throughout my (@ngy) year of clinical rotations, I repeated the language of my clinical instructors, and claimed that patients with tight or overactive muscles as being "high tone" or "hypertonic."




# Hypotonia

"In hypotonia (decreased muscle tone), passive movement of a muscle occurs with little or no resistance. Causes include cerebellar damage and pure pyramidal tract damage (a rare occurrence). The hypotonia contributes to the ataxia and intention tremor in cerebellar damage and manifests with minimal weakness and normal or slightly exaggerated reflexes. A pure pyramidal tract injury produces hypotonia and weakness. Hypotonia also occurs when the nerve impulses needed for muscle tone are lost, such as in spinal cord injury or cerebrovascular accident." @huetherUnderstandingPathophysiology2020

"Individuals with hypotonia tire easily or are weak. They may have difficulty rising from a sitting position, sitting down without using arm support, and walking up and down stairs, as well as an inability to stand on their toes. Because of their weakness, accidents during ambulatory and self-care activities are common. The joints become hyperflexible, so persons with hypotonia may be able to assume positions that require extreme joint mobility. The joints may appear loose. The muscle mass atrophies because of decreased input entering the motor unit, and muscles appear flabby and flat. Muscle cells are gradually replaced by connective tissue and fat. Fasciculations may be present in some cases." @huetherUnderstandingPathophysiology2020

# Hypertonia

"four types of hypertonia are spasticity paratonia (gegenhalten), dystonia, and rigidity" @huetherUnderstandingPathophysiology2020

"In hypertonia (increased muscle tone), passive movement of a muscle occurs with resistance to stretch and is caused by upper motor neuron damage (see p. 381). The four types of hypertonia are spasticity (usually corticospinal in origin) (Figures 15-12 and 15-13), paratonia (gegenhalten), dystonia (Figure 15-14), and rigidity (usually extrapyramidal in origin). Four types of rigidity are described: plastic or lead-pipe, cogwheel, gamma (independent of stretch reflex pathways), and alpha (dependent on stretch reflex pathways) (see Table 15-16)." @huetherUnderstandingPathophysiology2020

"Individuals with hypertonia tire easily or are weak. Passive movement and active movement are affected equally, except in paratonia, in which more active than passive movement is possible. As a result of hypertonia and weakness, accidents occur during ambulatory and self-care activities." @huetherUnderstandingPathophysiology2020

"The muscles may atrophy because of decreased use. However, hypertrophy occasionally occurs as a result of the overstimulation of muscle fibers. Overstimulation occurs when the motor unit reflex arc remains intact and functioning but is not inhibited by higher centers. This causes continual muscle contraction, resulting in enlargement of the muscle mass and the development of firm muscles." @huetherUnderstandingPathophysiology2020



# Spasm {#spasm}

A spasm differs from [hypertonia](#hypertonia), a spasm is a reflexive muscle contraction elicited by nociception or other pathological processes @DynamicNeurologicalStabilizationClinicalRehabilitation2014.

Spasms can be measured using the *Frequency of Spasms Score* @gangulyMuscleTonePhysiology2021.

# Spasticity sensu strictu {#spasticity}

- [Lateral reticulospinal tract]({{< var ref-lateral-reticulospinal-tract.path >}})
- [Medial reticulospinal tract]({{< var ref-medial-reticulospinal-tract.path >}})


- "A scissors gait is associated with bilateral injury and spasticity" @huetherUnderstandingPathophysiology2020


*Spasticity sensu strictu* is a variant of muscle hyperactivity disorder where the hyperactivity is triggered by rapid passive joint movement.
This includes the *clasp-knife phenomenon* @dresslerDefiningSpasticityNew2018.


Spasticity is a motor disorder characterized by both velocity and length (stretch) dependent increaases in muscle tone (tonic stretch reflexes) with exaggerated tendon jerks (hyperreflexia) that is due to a hyperexcitability of the *muscle stretch reflex* @gangulyMuscleTonePhysiology2021.

Although spasticity is considered to be "only velocity dependent," degree of spasticity is affected by **muscle length** @gangulyMuscleTonePhysiology2021.
In the knee extensors, the degree of spasticity increases as the knee extensors are in shorter positions @gangulyMuscleTonePhysiology2021.
Conversely, in the upper limb flexors (i.e. biceps) and ankle plantarflexors, the degree of spasticity increases as the muscle lengthens @gangulyMuscleTonePhysiology2021.


Spasticity can be classified into **phasic spasticity** and **tonic spasticity** @gangulyMuscleTonePhysiology2021.

- **Phasic spasticity**: Refers to spasticity that develops in ambulatory patients and involves brisk stretch reflexes and clonus @gangulyMuscleTonePhysiology2021.
- **Tonic spasticity**: Develops in non-ambulatory patients and is demosntrated by a passive stretch at the ankle as well as vibratory tonic reflex testing @gangulyMuscleTonePhysiology2021.



Spasticity includes

- Velocity *and* length dependence
- motor *and* sensory dysfunction


:::{#tbl-spasticity-localization}
| Region | Pathology |
|-|-|
| Supraspinal | Stroke </br> Multiple sclerosis </br> Cerebral palsy </br> Hypoxic brain damage </br> Traumatic brain injury </br> Mass lesions: tumours, vascular malformations </br> Inflammation |
| Spinal | Cervical myelopathy </br> Mass lesions: tumours, vascular malformations </br> Inflammation </br> Stroke </br> Traumatic spinal cord lesion </br> Hereditary spastic paraplegia </br> Spina bifida </br> Myelomeningocele </br> Tethered cord |
| Mixed | Multiple sclerosis </br> Motoneuron disease, primary lateral sclerosis </br> Inflammation |
: Etiology of spasticity classified by the localisation of the underlying pathology @dresslerDefiningSpasticityNew2018 {.striped}
:::



"Motor impairment in humans may result from damage to efferent cerebral cortical fibers passing within the internal capsule. This might happen following a stroke to the blood supply to the internal capsule. The resulting disorder is often termed a pyramidal tract syndrome or upper motor neuron disease, although these names are misnomers. Motor changes characteristic of this disorder include: (1) increased phasic and tonic stretch reflexes (spasticity); (2) weakness, usually of the distal muscles, especially the finger muscles; (3) pathological reflexes, including the sign of Babinski (dorsiflexion of the big toe and fanning of the other toes when the sole of the foot is stroked); and (4) a reduction in superficial reflexes, such as the abdominal and cremasteric reflexes. Of importance is that if only the corticospinal tract is interrupted, as can occur with a lesion of the medullary pyramid, most of these signs are much reduced or absent. In this situation, the most prominent deficits are weakness of the contralateral distal muscles, especially those of the fingers, and a Babinski sign. Spasticity does not occur; instead, muscle tone may actually decrease. Evidently, the presence of spasticity requires the disordered function of other pathways, such as the reticulospinal tracts, as would occur after loss of the descending cortical influence to the brainstem nuclei of origin of these tracts." @berneLevyPhysiology2024

## Clasp-knife phenomenon


::: {.callout-important}
Initially, the clasp-knife phenomenon was theorized to be the result of the muscle contraction tensioning the GTO and resulting in reflex inhibition @berneLevyPhysiology2024.
Studies indicating that GTO reflexes act at much lower levels of force indicate that this is not the underlying mechanism behind the clasp-knife phenomenon @berneLevyPhysiology2024.
:::

Currently, it is hypothesized that muscle contraction results in activation of high-threshold receptors innervating the surrounding fascia, which is sent to the spinal cord and synapses on inhibitory interneurons that inhibit the motor efferents of the muscle @berneLevyPhysiology2024

"After damage to the descending motor pathways, hyperactive stretch reflexes may result in spasticity, in which there is large resistance to passive rotation of the limbs. In this condition, it may be possible to demonstrate what is called the clasp-knife reflex. When spasticity is present, attempts to rotate a limb about a joint initially meet high resistance. However, if the applied force is increased, there comes a point at which the resistance suddenly dissipates and the limb rotates easily. This change in resistance is caused by reflex inhibition. The group Ib reflex arc suggests that rising activity in this pathway could underlie the sudden release of resistance, and indeed, the clasp-knife reflex was once attributed to the activation of Golgi tendon organs when these receptors were thought to have a high threshold to muscle stretch. However, the tendon organs have since been shown to be activated at very low levels of force and are no longer thought to cause the clasp-knife reflex." @berneLevyPhysiology2024

"While passively stretching a muscle, more resistance is felt in the initial part of stretching, but with continued stretching, a sudden release of resistance occurs, described as ‘clasp-knife phenomenon’. Because of length dependency of spasticity, initially while bending the knee (quadriceps is short) increased resistance is felt (spasticity is more). However, with continued stretching (quadriceps is lengthening), after reaching a critical length, the resistance suddenly decreases [40–42]. The excitation of slowly conducting, higher-threshold inhibitory group III and IV muscle afferents (part of flexor reflex afferents/FRA) may also be responsible for this phenomenon [43]." @gangulyMuscleTonePhysiology2021

## Pathophysiology

*Spasticity sensu strictu* is a form of "involuntary motor hyperactivity disorder." @dresslerDefiningSpasticityNew2018.


### Spinal Influence {#spasticity-spinal-influence}

"Spinal influence on spasticity can either be from increased excitation or decreased inhibition. Enhanced fusimotor drive [22], denervation hypersensitivity [23], axonal sprouting [24,25], hyperexcitability of alpha motor neurons [25], excitation of interneurons [25] and increased cutaneous stretch reflexes [10] are responsible for increased excitatory influence on spasticity. Animal models have shown the role of membrane properties of the motor neuron in spasticity. Voltage dependent persistent inward current (PIC) mediated via Na+ and Ca2+ channels can cause prolonged depolarization (plateau potential), modulated by the descending serotonergic and noradrenergic drive [10,25]. Descending monoaminergic drive normally has an excitatory effect on alpha motor neurons at the ventral horn via 5HT2 and NEα1 receptors, whereas it has inhibitory effect at dorsal horn via 5HT1b/d and NEα2 receptors [25]. In the acute stage after spinal injury, due to loss this descending monoaminergic influence, hypoexcitability of motor neurons occurs at the ventral horn whereas disinhibition and excitation of sensory input at the dorsal horn. However, spasticity doesn’t develop acutely despite interneuronal excitability until motor neurons regain the excitability. In the chronic stage, denervation hypersensitivity of ventral horn motor neurons occurs to the remaining monoaminergic input and PIC is activated that in turn leads to development of spasticity." @gangulyMuscleTonePhysiology2021

"Apart from excitatory mechanisms contributing to spasticity, the role of altered spinal inhibitory circuitry is increasingly being appreciated in recent studies [10]. Disinhibition of the alpha motor neuron in spasticity can occur from decreased presynaptic inhibition of Ia afferents [26], decreased disynaptic reciprocal Ia afferent inhibition from the antagonist muscle group [27,28], decreased Ib afferent mediated inhibition by Golgi tendon organ [29], and altered recurrent inhibition by Renshaw cells (doubtful role) [30]." @gangulyMuscleTonePhysiology2021

### Supraspinal influence {#spasticity-supraspinal-influence}

"In the normal scenario, human muscle tone is critically balanced by the inhibitory drive of CST and dorsal RST and facilitatory drive (on extensor tone) by medial RST and to some extent VST [10]. Among them, dorsal RST also inhibits flexor reflex afferents (FRA). In the spinal cord, lateral funiculus contains the corticospinal tract (CST) and dorsal RST while anterior funiculus contains VST and medial RST. Based on this, the effects of cortical and spinal lesions on muscle tone can be summarized as follows." @gangulyMuscleTonePhysiology2021


### Cortical lesions

"Isolated involvement of CST is insufficient to produce spasticity [31,32]. Cortical lesions produce spasticity due to associated involvement of corticoreticular fibers, the connection between premotor cortex and medullary reticular formation from where dorsal RST originates. Hemiplegia with spasticity and antigravity posturing occurs because of unopposed facilitatory action of medial RST, in the absence of inhibitory influence of dorsal RST." @gangulyMuscleTonePhysiology2021

### Spinal cord lesions {#spasticity-spinal-cord-lesions}

"Incomplete/partial myelopathy involving lateral funiculus: If there is involvement of CST only, it will result in weakness, hypotonia and loss of superficial reflexes. If there is additional involvement of dorsal RST, spasticity and hyperreflexia will develop due to unopposed activity of medial RST. Spasticity will be predominant in antigravity muscles and will result in paraplegia in extension and extensor spasms. Flexor spasms can occur if FRA are activated by pressure sores. On the other hand, if there is involvement of dorsal RST only with sparing CST, there will be spasticity without much weakness." @gangulyMuscleTonePhysiology2021

"Complete myelopathy with involvement of all four tracts: Spasticity will be less in this case because of lack of facilitatory input from medial RST and VST. Disinhibition of FRA will result in paraplegia in flexion and flexor spasms." @gangulyMuscleTonePhysiology2021

### Role of sensory feedback

"Recent studies have argued that co-activation of antagonist muscles, stiff posture and stiff gait of spasticity may be the adaptations to stabilize the joint and posture in a background of decreased muscle strength, whereas hyperexcitable reflexes play a minor or no role [33,34]. Spastic movement disorders may result due to inadequate prediction of the sensory consequences of movements [35,36]. Due to the absence of a firm prediction of somatosensory feedback from the moving limb, the patient with UMN lesion will have difficulty in optimizing the movement. Co-contraction of the muscles around the joint may therefore be a strategy to minimize random movement and to stabilize the movement as far possible [33]. Therefore, spastic movement disorder may rather be a compensation to the weakness. The concept can be implemented in uncomplicated hereditary spastic paraplegia (HSP), where large fiber proprioceptive sensory loss occurs along with corticospinal tract (CST) involvement. As discussed previously, selective loss of CST is not sufficient to produce significant spasticity more than weakness. Thus, defective sensory feedback may also play a role in the clinical manifestation of marked spasticity out of proportion to weakness in HSP. DeLuca et al. highlighted that, in HSP, axonal loss occurs in both large (>3 μm2) and small (<3 μm2) diameter nerve fibers of motor (CST) and sensory (posterior column) tracts, whereas in multiple sclerosis (MS) small diameter fibers are preferentially affected [37]. Thus, the affection of large diameter nerve fibers may be responsible for the predominance of spasticity seen in HSP, in comparison to MS where weakness predominates." @gangulyMuscleTonePhysiology2021

### Non-neural factors {#spasticity-non-neural-factors}

"As discussed previously, changes in non-neural factors like tissue viscoelastic properties (e.g., elastic stiffness, viscous damping) can also contribute to the generation of spasticity [38,39]." @gangulyMuscleTonePhysiology2021

# Clonus

"Clonus is defined as the “regular, repetitive, rhythmic contractions of a muscle subjected to sudden, maintained stretch” [11]. Clonus sustained for five or more beats is considered as clinically abnormal. The pathological basis has been explained in the literature in multiple ways: (1) stretch reflex-inverse stretch reflex sequence, (2) disruption of the Renshaw cell and type Ia inhibitory interneuron mediated inhibition of the antagonist → repetitive sequential contraction of agonist and antagonist → clonus results, (3) hyperactivity of the muscle spindles → activation of all the motor neurons from the burst of impulses coming from the spindle → consequent muscle contraction stops spindle discharge → during maintenance of the sustained stretch, the muscle is again stretched as soon as the muscle relaxes → spindles are again stimulated [11,44]. However, the exact pathophysiology is still debated." @gangulyMuscleTonePhysiology2021


# Rigidity {#rigidity}


Rigidity refers to an variant of involuntary muscle hyperactivity (spasticity @dresslerDefiningSpasticityNew2018) triggered by **slow, passive joint movements** @dresslerDefiningSpasticityNew2018.
Additional factors, such as muscular viscosity can contribute to the level of hyperactivity @dresslerDefiningSpasticityNew2018.

- Velocity
    - Not velocity dependent @gangulyMuscleTonePhysiology2021 
    - triggered by "slow passive joint movement" @dresslerDefiningSpasticityNew2018
- Localization: Equal impact on flexors and extensors @gangulyMuscleTonePhysiology2021.
- Resistance: 
    - Lead-pipe phenomenon: Uniform resistance to passive stretch in all directions @gangulyMuscleTonePhysiology2021.
    - Cog-wheel phenomenon: Resistance to passive stretch in the form of invisible tremors at 6-9hz @gangulyMuscleTonePhysiology2021.
- Parkinson's Disease
    - Rigidity is a cardinal sign of PD @gangulyMuscleTonePhysiology2021.
    - Rigidity is present in both *akinetic-rigid PD* and *tremor dominant PD* @gangulyMuscleTonePhysiology2021.
    - Rigidity is more severe in *akinetic-rigid PD* @gangulyMuscleTonePhysiology2021.
    - Idiopathic PD: Appendicular rigidity is more marked than axial rigidity @gangulyMuscleTonePhysiology2021.
    - Atypical parkinsons (i.e. progressie supranuclear palsy): Marked axial rigidty @gangulyMuscleTonePhysiology2021
- Factors contributing to rigidity:
    - [Exaggeration of Long-Latency Stretch Reflexes (LLSR)](#exaggeration-of-long-latency-stretch-reflexes-(llsr))

## Cog-wheel phenomenon

- AKA "Cog-wheel rigidity"
- Refers to a form of rigidity where the a superimposed tremor or "non-visible tremor" can 
    - Cog-wheel phenomenon can be present *without* the presence of over, visible tremors @gangulyMuscleTonePhysiology2021

| PD Tremors | Frequency |
|-|-|
| Cog-wheel rigidity | 6-9Hz |
| Postural tremor | 5-6Hz
| Rest tremor | 4-5Hz |
: Parkinson's Disease Tremor Frequency {.striped}





## Pathophysiology

::: {.callout title="Relevant structures"}


- [Long-latency stretch reflexes (LLSR)]({{< var ref-long-latency-stretch-reflex.path >}})
- Shortening reaction (SR)
- Stretch-induced inhibition (SII)
- [Sublaterodorsal nucleus]({{< var ref-sublaterodorsal-nucleus.path >}})
- [Nucleus reticularis gigantocellularis (NRGC)]({{< var ref-nucleus-reticularis-gigantocellularis.path >}})
- [Locus coeruleus]({{< var ref-locus-coeruleus.path >}})
- [Caudal raphe nucleus]({{< var ref-caudal-raphe-nucleus.path >}})
- [Pedunculopontine nucleus (PPN)]({{< var ref-pedunculopontine-nucleus.path >}})

:::


## Exaggeration of Long-Latency Stretch Reflexes (LLSR)
"Initial studies suggested that parkinsonian rigidity is likely of spinal reflex origin, substantiated by the fact that the rigidity improved by dorsal cord resection [51]. Enhanced response of the muscle receptors to passive stretch was thought to be the main culprit. However, subsequent studies with microneurographic recordings found that the increased muscle afferent discharge from enhanced fusimotor drive was not sufficient enough to cause rigidity [52]. Monosynaptic segmental stretch reflexes didn’t differ significantly between PD patients and healthy subjects in the studies utilizing electrophysiological analysis [53,54]. Rather, Ia afferent mediated spinal reflexes like tendon jerks, H-reflex and tonic vibration reflex were found to be mostly normal in PD patients [55,56]. So, the notion gradually shifted to the exaggerated long-loop or long-latency stretch reflex (supraspinal influence) on parkinsonian rigidity rather than spinally mediated reflexes. Berardelli et al. noted co-relation between increase of LLSR with rigidity and suspected the role of group II afferents in this regard [57]. Rothwell et al., although noted enhanced LLSR in PD, couldn’t find any quantitative correlation of this with rigidity. They suggested that LLSR is not solely responsible for parkinsonian rigidity and enhanced late polysynaptic reflexes mediated by cutaneous afferents may also be important [53]." @gangulyMuscleTonePhysiology2021

## Enhanced Shortening Reaction (SR) and Stretch-Induced Inhibition (SII) {#rigidity-enhanced-shortening-reaction-stretch-induced-inhibition}
"Exaggerated LLSR can explain hypertonia in PD but cannot explain the resistance to passive stretch being uniform throughout the range of movement (‘lead pipe’ character)? Anomalous reaction in the muscle that is shortening was initially noted by Westphal and subsequently named ‘shortening reaction’ (SR) by Sherrington [58]. Alteration in the pathways for short-latency autogenic inhibition, mediated by altered excitability of Ia and Ib spinal interneurons, may be responsible for the phenomenon of SR [59]. On the other hand, a sudden decrease in resistance is seen while continuously stretching or lengthening a muscle beyond a critical joint angle. The phenomenon is called a ‘lengthening reaction’ or stretch-induced inhibition (SII) [60]. The combined effect of SR and SII generate ‘lead pipe’ effect while examining limb tone in PD [61]." @gangulyMuscleTonePhysiology2021

## Role of Brainstem {#rigidity-role-of-brainstem}


"The role of non-dopaminergic system in PD is increasingly being highlighted in recent studies. Recently, Linn-Evans et al. have noted increased and more symmetric rigidity in upper limb of PD patients in wakefulness who have REM sleep without atonia (PD-RSWA+) compared to with-atonia (PD-RSWA-) and controls [62]. The brainstem circuit responsible for tone in REM sleep overlaps with the circuit maintaining motor neuron excitability and postural control in wakefulness [63]. In PD, there is evidence of alpha-synuclein deposition in the nuclei of both the circuits including sublaterodorsal nucleus (responsible for tone regulation in REM sleep), nucleus reticularis gigantocellularis (NRGC), locus coeruleus, caudal raphe and pedunculopontine nucleus (PPN) [64]. Caudal PPN gives cholinergic excitatory inputs to NRGC from where dorsal or lateral reticulospinal tract (dorsal RST) originates and activates Ib spinal interneurons that in turn inhibits alpha motor neuron (Figure 3). PPN also receives inhibitory input from globus pallidus interna (GPi). In PD, degeneration of PPN and NRGC decrease excitation of Ib spinal interneurons that in turn disinhibit alpha motor neuron and can lead to rigidity [65]. Increased inhibitory tone from GPi to PPN in PD can also lead to the same phenomenon. Heckman et al. have also highlighted the role of noradrenergic and serotonergic influence from locus coeruleus and caudal raphe respectively on motor neuron excitability by promoting firing via persistent inward current (PIC) [66]. Affection of these pathways in PD may lead to altered firing pattern of the motor neuron in response to incoming inputs and can contribute to rigidity [62]." @gangulyMuscleTonePhysiology2021

## Non-Neural Factors {#rigidity-non-neural-factors}

"As discussed earlier, viscoelastic properties of muscle fiber and surrounding connective tissues may also contribute to parkinsonian rigidity. Watts et al. have noted that in PD patients even with mild motor symptoms, upper limb stiffness was more than controls in relaxed state, but without any EMG activity [67]. The study highlighted the role of passive mechanical properties for the stiffness. Xia et al. have also noted the contribution from both neural and non-neural factors for parkinsonian rigidity while neural contribution dominates" @gangulyMuscleTonePhysiology2021

## Network hypothesis of Parkinsonian Rigidity {#rigidity-network-hypothesis-parkinsonian-rigidity}

"Baradaran et al. [69] explored the alteration in functional connectivity in brain networks in relation to parkinsonian rigidity. With progression of rigidity, they noted progressive abnormality of premotor → pre-cuneus connection (disease related change), while cerebellar → premotor connection approached normal values (compensatory mechanism). Kann et al. [70] have postulated that significant loss of gray matter and aberrant functional connectivity in fronto-parietal networks (critical for motor planning and execution) in akinetic-rigid subtype of PD are responsible for more aggressive course of functional decline, compared to tremor-dominant subtpye" @gangulyMuscleTonePhysiology2021

# Dystonia {#dystonia}

Dystonia is involuntary muscle hyperactivity that is spontaneous and has no triggers @dresslerDefiningSpasticityNew2018.
Dystonia involves co-contractions of antagonist muscle groups @dresslerDefiningSpasticityNew2018.

Often, co-contractions in antagonist muscle groups due to dystonia is worst when voluntarily attempting to activate the dystonic or non-dystonic muscle groups @dresslerDefiningSpasticityNew2018.
When dystonia worsens in relation to voluntary muscle activation, it is known "action-induced dystonia" or "dynamic dystonia" @dresslerDefiningSpasticityNew2018.

::: {.callout title="Relevant structures"}

- [Pallido-thalamo-cortical network]({{< var ref-pallido-thalamo-cortical-network.path >}})
- [Cerebello-thalamo-cortical network]({{< var ref-cerebello-thalamo-cortical-network.path >}})

:::









# Paratonia {#paratonia}

- [Orbitofrontal damage]({{< var ref-orbitofrontal.damage >}})
- [Frontal-subcortical dysfunction]({{< var ref-frontal-subcortical.dysfunction >}})
- [Advanced glycation end products]({{< var ref-advanced-glycation-end-products.path >}})

# Spinal Shock and muscle tone

"Spinal shock is the temporary loss of all spinal cord functions below the lesion (below the level of the pons). It is characterized by complete flaccid paralysis, absence of reflexes, and marked disturbances of bowel and bladder function. Hypotension can occur from loss of sympathetic tone at higher levels of spinal cord injury. A major factor in spinal shock is the sudden destruction of the efferent pathways. If destruction occurs more slowly, spinal shock may not develop (see Chapter 16)." @huetherUnderstandingPathophysiology2020

"If the pyramidal system is interrupted above the level of the pons, the hand and arm muscles are greatly affected. Paralysis rarely involves all the muscles on one side of the body, even when the hemiplegia results from complete damage to the internal capsule. Bilateral movements, such as those of the eye, jaw, and larynx, as well as those of the trunk, are affected only slightly, if at all. Predominantly the limbs are influenced." @huetherUnderstandingPathophysiology2020

"Paralysis associated with a pyramidal motor syndrome rarely remains flaccid for a prolonged time. After a few days or weeks, a gradual return of spinal reflexes marks the end of spinal shock. Reflexes then become hyperactive, and muscle tone increases significantly, particularly in antigravity muscles. Spasticity is common, although rigidity occasionally occurs (see p. 377). Most often, passive range-ofmotion movements cause “clasp-knife” rigidity, probably by activating the stretch receptors in the muscle spindles and the Golgi tendon organ. (Muscle function is discussed in Chapter 38.) With pyramidal motor syndrome, predominantly the flexors of the arms and the extensors of the legs are affected." @huetherUnderstandingPathophysiology2020

# Tests and Measures

- [Modified Ashworth Scale]({{< var ref-modified-ashworth-scale.path >}})
- [Modified Tardieu Scale]({{< var ref-modified-tardieu-scale.path >}})
- [Brunnstrom Stages of Recovery]({{< var ref-brunnstrom-stages-of-recovery.path >}})
- Spasms: Frequency of spasms score

# ALS management

"Symptomatic Therapy of ALS: Spasticity  Spasticity is an important component of the clinical features of ALS and the feature most amenable to present forms of treatment. Spasticity is defined as an increase in muscle tone characterized by an initial resistance to passive movement of a joint, followed by a sudden relaxation (the so-called clasped-knife phenomenon). Spasticity results from loss of descending inputs to the spinal motor neurons, and the character of the spasticity depends on which nervous system pathways are affected. See further discussion of antispasticity agents in Chapter 13." @GoodmanGilmanPharmacological2023

- Baclofen
- tizanidine
- Other Agents: "Benzodiazepines (see Chapter 22) such as clonazepam are effective antispasticity agents, but they may contribute to respiratory depression in patients with advanced ALS. Dantrolene, approved in the U.S. for the treatment of muscle spasms, is not used in ALS because it can exacerbate muscular weakness. Dantrolene acts directly on skeletal muscle fibers, impairing Ca2+ release from the sarcoplasmic reticulum. It is effective in treating spasticity associated with stroke or spinal cord injury and in treating malignant hyperthermia (see Chapter 13). Dantrolene may cause hepatotoxicity, so it is important to monitor liver-associated enzymes before and during therapy with the drug." @GoodmanGilmanPharmacological2023

::: {.callout-warning}
Dantrolene is *not* used in ALS since it can exacerbate muscular weakness @GoodmanGilmanPharmacological2023
:::

# Basal Ganglia

"The basal ganglia influence the cortical motor areas. Therefore, the basal ganglia have an important influence on the lateral corticospinal system of motor pathways. Such an influence is consistent with some of the movement disorders observed in diseases of the basal ganglia. The basal ganglia also regulate the medial motor pathways, because diseases of the basal ganglia can also affect the posture and tone of proximal muscles." @berneLevyPhysiology2024

"The deficits seen in the various basal ganglia diseases include abnormal movement (dyskinesia), increased muscle tone (cogwheel rigidity), and slowness in initiating movement (bradykinesia). Abnormal movement includes tremor, athetosis, chorea, ballism, and dystonia. The tremor of basal ganglion disease is a 3-Hz “pill-rolling” tremor that occurs when the limb is at rest. Athetosis consists of slow, writhing movement of the distal parts of the limbs, whereas chorea is characterized by rapid, flicking movement of the extremities and facial muscles. Ballism is associated with flailing movement of the limbs (ballistic movement). Finally, dystonic movements are slow involuntary movements that may cause distorted body postures." @berneLevyPhysiology2024

# Vibration training

::: {.callout-note title="Future Research"}
Preprints:

[Vibratory stimulation and not action observation or mirror therapy reduces paralyzed hand spasticity in chronic stroke survivors.](https://www.medrxiv.org/content/10.1101/2024.12.03.24318436v1)

- [Wearable Focal Muscle Vibration Improves Upper Limb Function in People with Sub-acute Stroke](https://www.medrxiv.org/content/10.1101/2024.11.11.24317091v1)
    - This says "spasticity" but it was measured via MAS which is more of a rigidity scale

[Effectiveness of Focal Muscle Vibrations in Improving Sensorimotor Performance, Mobility and Strength in Spinal Cord Injury Population: A Systematic Review](https://www.medrxiv.org/content/10.1101/2023.12.22.23300431v1)



:::

# Anti-Spastic Pharmacological Agents

| Drug | Therapeutic Uses | Clinical Pharmacological Tips |
|-|-|-|
| Baclofen | GABA_B_ receptor agonist | Sedation and CNS depression |
| Tizanidine | &alpha;_2_ Adrenergic receptor agonist | Causes drowsiness; treatment is initiated with low dose and titrated upward |
| Benzodiazepines (e.g., clonazepam) | See Chapter 22 @GoodmanGilmanPharmacological2023 | May contribute to respiratory depression |
| Diazepam | Minimizes seizures associated with neuronal toxicity | Administered parenterally after exposure |
| Dantrolene | Not used in ALS, but for treating muscle spasm in stroke or spinal injury and for treating malignant hyperthermia </br> Management and prevention of malignant hyperthermia • Treatment of spasticity associated with upper motor neuron disorders (e.g., spinal cord injury, stroke, cerebral palsy, or multiple sclerosis) | Hepatic metabolism </br> May cause hepatotoxicity |
: AntiSpastic Agents @GoodmanGilmanPharmacological2023 {.striped}

::: {.callout title="Treatment of MS Spasticity"}

- Baclofen Dantrolene Diazepam Clonazepam Tizanidine Tiagabine Gabapentin Pregabalin Botulinum toxin type A Dalfampridine Table74-4 @dipirosDiPirosPharmacotherapyPathophysiologic2023
:::

## Baclofen

::: {.callout title="Read"}

- ch13 p242 @GoodmanGilmanPharmacological2023

:::

- GABA<sub>B</sub> agonist @GoodmanGilmanPharmacological2023
- Centrally acting spasmolytic @GoodmanGilmanPharmacological2023
- CNS-Active Agents that controls muscle spasms @GoodmanGilmanPharmacological2023
- Brand names: 
    - Lioresal
    - Lyvispah
    - Gablofen
    - Fleqsuvy
    - Ozobax
    - Lyflex
    - Kemstro

"Baclofen (Lioresal), a short-acting &gamma;-aminobutyric acid (GABA) analog, is the preferred agent for spasticity and is started at 10 mg three times daily which is then titrated upward to achieve the desired response. Most patients respond with dosages between 40 and 80 mg/day, although some require dosages higher than the maximum recommended daily dose of 80 mg.33,130 Due to oral baclofen’s relatively short duration of action, continuous intrathecal administration of Gablofen may be used for patients unable to tolerate or unresponsive to oral therapy. " @dipirosDiPirosPharmacotherapyPathophysiologic2023

"Baclofen is similar in structure to GABA and binds to GABA<sub>B</sub>  receptors. These receptors are coupled to Ca<sup>2+</sup> and K<sup>+</sup> channels located pre- and postsynaptically. Essentially this leads to reduction in the release of excitatory glutamate and increases presynaptic inhibition. Additionally, baclofen may reduce the release of substance P. Sedation, dizziness, weakness, and nausea are possible adverse effects, with the most concerning being associated with baclofen as hallucinations or seizures may occur during withdrawal with abrupt discontinuation. Therefore, baclofen must be tapered slowly.105 Baclofen also requires dose adjustment for decreased renal function.10" @dipirosDiPirosPharmacotherapyPathophysiologic2023

::: {.callout-caution}
Baclofen should not be abruptly discontinued to avoid seizures @dipirosDiPirosPharmacotherapyPathophysiologic2023
:::

::: {.callout}
For ALS



"Baclofen. The best agent for the symptomatic treatment of spasticity in ALS is baclofen, a GABAB receptor agonist (see Figure 16–8). Initial doses of 5 to 10 mg/day are recommended, which can be increased to as much as 200 mg/day, if necessary. Alternatively, baclofen can be delivered directly into the space around the spinal cord using a surgically implanted pump and an intrathecal catheter. This approach minimizes the adverse effects of the drug, especially sedation, but it carries the risk of potentially life-threatening CNS depression." @GoodmanGilmanPharmacological2023

"Baclofen, a GABAB receptor agonist, is a skeletal muscle relaxant used to reduce spasticity. It is approved to treat AUD in France and is indicated for use in patients not responsive to other treatments. There is increased risk of sedation when combining baclofen with alcohol. In a meta-analysis of randomized clinical trials, baclofen was associated with a delay in return to drinking and a greater likelihood of abstinence, especially in those with higher daily alcohol use at baseline (reviewed in Kranzler and Soyka, 2018). Although some results have been promising, evidence overall is uncertain regarding its use, particularly as a first-line treatment. For a review of baclofen in treating AUD, see de Beaurepaire et al., 2019." @GoodmanGilmanPharmacological2023


:::

::: {.callout title="PD dystonia"}

"“Off-Period” Dystonia In PD, dystonias are sustained muscle contractions that can occur and more commonly affect a distal lower extremity (eg, clenching of toes or involuntary turning of a foot). Dystonias often occur in the early morning hours, due to waning medication levels, and improve with the first carbidopa/L-dopa dose of the day. Remedies for early morning dystonia include bedtime administration of a long-acting dopamine agonist, long-acting carbidopa/L-dopa, or baclofen. Additionally, focal injections of botulinum toxin type A or B are effective for persistent focal dystonias, which can also occur as L-dopa peak dose effect; therefore, additional management of this specific adverse event is similar to that of dyskinesias.66"

:::


## Diazepam

::: {.callout title="Reading list"}

- Table 5-2 @GoodmanGilmanPharmacological2023
    - N-Dealkylation
    - Deamination

:::

| Drug | Therapeutic Uses | Clinical Pharmacological Tips |
|-|-|-|
| Diazepam | Minimizes seizures associated with neuronal toxicity, Anxiety disorders, alcohol withdrawal, status epilepticus, skeletal muscle relaxation, preanesthetic medication, Ménière disease (OL) | Administered parenterally after exposure |
: AntiSpastic Agents @GoodmanGilmanPharmacological2023 {.striped}

- Type of Benzodiazepine
- Brand names: 
    - Valium
    - Diastat
    - Valtoco
    - Diazemuls
    - Stesolid Rectal Tubes
    - Diazepam Rectubes
    - Diazepam Desitin
    - Vazepam
- Half life
    - "long acting" benzodiazepine (>24hr halflife (t_12_))
- Interactions
    - "For example, the benzodiazepine diazepam is highly lipid soluble and is excreted by the kidney. Because of the increase in body fat and the decrease in renal excretion that typically occur from age 20 to 80, the t1/2 of the drug may increase 4-fold over this span." @GoodmanGilmanPharmacological2023
    - "Omeprazole and esomeprazole selectively inhibit the hepatic CYP2C19 pathway and may decrease the elimination of several drugs (eg, phenytoin, warfarin, diazepam, and carbamazepine).5" @dipirosDiPirosPharmacotherapyPathophysiologic2023



"In patients unable to tolerate baclofen or tizanidine, diazepam (Valium; 2-10 mg/day), clonazepam (Klonopin; 1-3 mg/day), or dantrolene sodium (Dantrium; 100-400 mg/day) may be alternatives; however, they generally are less effective. Mild spasticity may respond to gabapentin (Neurontin; 1,800-3,600 mg/day) or tiagabine (Gabitril; 8-56 mg/day) may be useful but adverse medication reactions can prohibit their use. Pregabalin (Lyrica; 75-300 mg/day) has similar features as gabapentin but is approximately three times more potent and does not saturate the GI tract L-transporter system, so it may prove helpful in treating spasticity." @dipirosDiPirosPharmacotherapyPathophysiologic2023

"Diazepam is not often used for non-cancer pain because of its sedative effects and potential for physical dependence. Its mechanism of action involves binding to GABAA resulting in increased chloride conductance which subsequently leads to presynaptic inhibition of the spinal cord. Abrupt discontinuation of diazepam can lead to a withdrawal syndrome, namely seizures. Diazepam has a long half-life (20-50 hours for parent and up to 100 for active metabolites) which is problematic especially for older patients. Avoid the use of diazepam in patients with renal or hepatic impairment.105" @dipirosDiPirosPharmacotherapyPathophysiologic2023

"Diazepam is highly lipophilic with a large volume of distribution (1-2 L/kg). Although it distributes into the brain within seconds, it rapidly redistributes into fat, causing its CNS half-life to be less than 1 hour and its duration of effect to be less than 30 minutes. The rapid decrease in brain concentration, along with pharmacoresistance, can cause seizure recurrence; hence, a longer-acting antiseizure medication (eg, phenytoin, levetiracetam, or valproate) should be given immediately after diazepam. Table 76-4 outlines dosing."

"Diazepam and other benzodiazepines are effective in treating muscle rigidity but are limited in utility due to high abuse potential and substantial CNS depressant effects. A prominent effect of benzodiazepines is enhancing GABAergic neurotransmission, resulting in enhanced inhibitory signaling in GABA-sensitive synapses." @GoodmanGilmanPharmacological2023

"GABAA receptors have been extensively characterized as important drug targets and are the site of action of many neuroactive drugs, notably benzodiazepines (such as diazepam), barbiturates, ethanol, anesthetic steroids, and volatile anesthetics among others (Figure 16–11). These drugs are used to treat various neuropsychiatric disorders including epilepsy, Huntington’s disease, addictions, sleep disorders, and more. The GABAA receptors are pentamers of subunits that each contain four transmembrane domains and assemble around a central ion-permeable pore (Figures 16–3 and 16–5), which is selective for Cl– in the case of the GABAA receptor. The major forms of the GABAA receptor contain at least three different types of subunits: α, β, and γ, with a likely stoichiometry of 2α, 2β, 1γ. The IUPHAR/British Pharmacological Society recognizes 19 unique subunits that are known to form 11 native GABAA receptors that can be pharmacologically differentiated. Of interest is that the particular combination of the α and γ subunits can affect the efficacy of benzodiazepine binding and channel modulation. Many drugs, such as benzodiazepines and volatile anesthetics, act as positive allosteric modulators of the GABAA receptor (i.e., act at a site distinct from the GABA binding site to positively modulate the function of the receptor). The high-resolution cryo-electron microscopy structures of the α1β3γ2L GABAA receptor bound to the agonist GABA and the classical benzodiazepines, alprazolam and diazepam, have been solved and utilized to further deduce signaling mechanisms of this group of receptors (Masiulis et al., 2019). Brexanolone is a neuroactive steroid that is a PAM at GABAA receptors and is approved to treat postpartum depression. The interaction of various drugs with the GABAA receptor and their therapeutic uses are presented in Chapter 18." @GoodmanGilmanPharmacological2023

"Some benzodiazepines induce muscle hypotonia without interfering with normal locomotion and can decrease rigidity in patients with cerebral palsy. Clonazepam in nonsedating doses causes muscle relaxation, but diazepam and most other benzodiazepines do not. Tolerance occurs to the muscle relaxant and ataxic effects of these drugs." @GoodmanGilmanPharmacological2023

"however, with diazepam, the effects are secondary to a decrease in left ventricular work and cardiac output. Diazepam increases coronary flow, possibly by an action to increase interstitial concentrations of adenosine, and the accumulation of this cardiodepressant metabolite also may explain the negative inotropic effects of the drug." @GoodmanGilmanPharmacological2023



## Tizanidine

- CNS-Active Agents that controls muscle spasms @GoodmanGilmanPharmacological2023
- &alpha;-2 adrenergic agonists (clonidine and tizanidine) @GoodmanGilmanPharmacological2023
- Brand names:
    - Zanaflex
    - Sirdalud

::: {.callout}
table 79-11 @dipirosDiPirosPharmacotherapyPathophysiologic2023
:::

"Tizanidine is an &alpha;<sub>2</sub> adrenergic receptor agonist. It provides effective relief from spasticity due to multiple sclerosis and spinal cord injury. Although a precise mechanism of action in relieving spasms is not understood, tizanidine is thought to have actions similar to those of clonidine. The advantage of tizanidine over clonidine for this indication is tizanidine’s lesser effect on lowering blood pressure at an effective concentration to relieve spasm. Tizanidine has a short t1/2 and is taken at a dose of 2 mg every 6 h for up to three doses daily; the dosage can be gradually ramped up to a daily maximum of 36 mg. In reverse fashion, the drug must be withdrawn slowly, tapering by 2 to 4 mg daily, to avoid a rebound of spasms, tachycardia, and hypertension. Common side effects include dizziness, sedation, and dry mouth. Use of tizanidine with a potent CYP1A2 inhibitor (e.g., fluvoxamine, ciprofloxacin, cimetidine) can substantially elevate tizanidine’s AUC. Tizanidine can interact additively with CNS depressants; its combination with ethanol should be avoided; antibiotics, antiarrhythmics, and hypotensive agents should be used with caution." @GoodmanGilmanPharmacological2023

"Tizanidine is a muscle relaxant used for the treatment of spasticity associated with cerebral and spinal disorders (see Chapter 13). It is also an α2 agonist with some properties similar to those of clonidine." @GoodmanGilmanPharmacological2023

"Similar to diazepam, tizanidine has both antispasticity and antispasmodic uses and is a centrally acting α2-agonist. Presynaptically, tizanidine inhibits the release of excitatory neurotransmitters that leads to a reduction in postsynaptic activation of the upper motor neuron. In addition, tizanidine leads to the potentiation of glycine. Not surprisingly, because of its α2-agonist activity, hypotension can occur and rebound hypertension seen with abrupt discontinuation. Other significant issues with tizanidine include sedation and elevation in hepatic enzymes requiring periodic monitoring. Tizanidine is metabolized by CYP1A2 and is contraindicated in combination with ciprofloxacin or fluvoxamine.105,107" @dipirosDiPirosPharmacotherapyPathophysiologic2023

"Tizanidine is an agonist of α2 adrenergic receptors in the CNS. It reduces muscle spasticity, probably by increasing presynaptic inhibition of motor neurons. Tizanidine is primarily used in the treatment of spasticity in multiple sclerosis or after stroke, but it also may be effective in patients with ALS. Treatment should be initiated at a low dose of 2 to 4 mg at bedtime and titrated upward gradually. Drowsiness, asthenia, and dizziness may limit the dose that can be administered" @GoodmanGilmanPharmacological2023

"Another effective agent for spasticity is tizanidine (Zanaflex), a short-acting, α-adrenergic agonist that acts in the CNS by increasing the presynaptic inhibition of motor neurons. Its efficacy is comparable to baclofen.116 Starting at a dosage of 4 mg at bedtime, slowly titrated up over 2 to 4 weeks based on clinical response. The effective dosages range from 2 to 36 mg/day. Sedation, dizziness, and dry mouth are commonly reported adverse effects, but hypotension, as well as rare but severe hepatotoxicity, can occur. Tizanidine can be added to baclofen in small dosages, sometimes resulting in smaller doses of each medication and better outcomes." @dipirosDiPirosPharmacotherapyPathophysiologic2023


::: {.callout}
For ALS

"Tizanidine. Tizanidine is an agonist of α2 adrenergic receptors in the CNS. It reduces muscle spasticity, probably by increasing presynaptic inhibition of motor neurons. Tizanidine is primarily used in the treatment of spasticity in multiple sclerosis or after stroke, but it also may be effective in patients with ALS. Treatment should be initiated at a low dose of 2 to 4 mg at bedtime and titrated upward gradually. Drowsiness, asthenia, and dizziness may limit the dose that can be administered.  " @GoodmanGilmanPharmacological2023
:::

- Drug interactions
    - "Following oral administration, the elimination t1/2 for vemurafenib is 57 h. Vemurafenib is a substrate of CYP3A4 and a substrate and an inhibitor of the Pgp exporter. Vemurafenib can increase concentrations of CYP1A2 substrates. Thus, concomitant use with the centrally acting α2 adrenergic receptor agonist tizanidine, which has a narrow therapeutic window and is used as a muscle relaxant, should be avoided." @GoodmanGilmanPharmacological2023
    - Ciprofloxacin (antibiotic) will strongly (&gt;5x) increase Tizanidine effects

## Dantrolene

- RyR1 blocker @GoodmanGilmanPharmacological2023
- Brand names:
    - Dantrium
    - Revonto
    - Ryanodex

"Dantrolene inhibits Ca<sup>2+</sup> release from the sarcoplasmic reticulum of skeletal muscle by limiting the capacity of Ca<sup>2+</sup> and calmodulin to activate the ryanodine receptor, RYR1. Dantrolene is indicated for chronic muscle spasticity associated with upper motor neuron disorders (spinal cord injury, stroke, cerebral palsy, or multiple sclerosis). Dantrolene is initiated at 25 mg daily for 7 days and then titrated up every 7 days up to a maximum dose of 400 mg/day. It is also indicated for malignant hyperthermia and used off-label for neuroleptic malignant syndrome. With its peripheral action, it causes generalized weakness. Thus, its use should be reserved to nonambulatory patients with severe spasticity. Hepatotoxicity has been reported with chronic use, requiring frequent liver function tests and use of the lowest possible oral dose." @GoodmanGilmanPharmacological2023


::: {.callout-warning title="Contraindication"}
"Dantrolene, approved in the U.S. for the treatment of muscle spasms, is not used in ALS because it can exacerbate muscular weakness. Dantrolene acts directly on skeletal muscle fibers, impairing Ca2+ release from the sarcoplasmic reticulum. It is effective in treating spasticity associated with stroke or spinal cord injury and in treating malignant hyperthermia (see Chapter 13). Dantrolene may cause hepatotoxicity, so it is important to monitor liver-associated enzymes before and during therapy with the drug." @GoodmanGilmanPharmacological2023
:::

## Botox

Botulinum Toxin Type A (Botox) is an effective agent in reducing spasticity @dipirosDiPirosPharmacotherapyPathophysiologic2023.

Botox is currently used in smaller muscles, since the amount required to have a therapeutic effect in larger muscles is an unsafe level @dipirosDiPirosPharmacotherapyPathophysiologic2023.

"Peripherally Acting Antispasmodics Botulinum Toxin  Botulinum toxins act peripherally to reduce muscle contraction. There are numerous nonequivalent preparations: abobotulinumtoxinA, incobotulinumtoxinA, onabotulinumtoxinA, prabotulinumtoxinA-xvfs, and rimabotulinumtoxinB; all work by blocking ACh release. The botulinum toxins bind to cholinergic neurons, enter the cell, and cleave SNARE proteins, thereby inhibiting vesicular release of ACh. The result is flaccid paralysis of skeletal muscle and diminished activity of parasympathetic and sympathetic cholinergic synapses. Inhibition lasts from several weeks to 3 to 4 months, and restoration of function requires nerve sprouting. Originally approved for the treatment of the ocular conditions of strabismus and blepharospasm and for hemifacial spasms, botulinum toxins have been used to treat spasms and dystonias and spasms associated with the lower esophageal sphincter and anal fissures. Botulinum toxin treatments also have become a popular cosmetic procedure for those seeking a wrinkle-free face. Like the bloom of youth, the reduction of wrinkles is temporary; unlike the bloom of youth, the effect of botulinum toxin can be renewed by readministration. Botulinum toxins are extremely poisonous and must be administered with great caution. Lethal doses of pure toxin are, roughly, approximately 1 ng/kg when administered IM or IV, approximately 10 ng/kg when inhaled, and approximately 1000 ng/kg when ingested (Arnon et al., 2001). The FDA requires a boxed warning on preparations of botulinum toxin, alerting practitioners and patients to the risk of respiratory paralysis from unexpected spread of the toxin from the site of injection (uses are described in Chapter 75). The FDA requires the highly specific names of the various products to emphasize that different preparations of botulinum toxin are not interchangeable; that is, different preparations’ units of biological activity cannot safely be compared. Patients showing signs of botulism should be treated promptly with antitoxin and given long-term supportive therapy." @GoodmanGilmanPharmacological2023


"Botulinum Toxin Type A in the Treatment of Strabismus,  Blepharospasm, and Related Disorders  Several botulinum toxin type A preparations are marketed in the U.S. with similar indications: onabotulinumtoxinA, abobotulinumtoxinA, prabotulinumtoxinA, and incobotulinumtoxinA. These agents are used for the treatment of strabismus and blepharospasm associated with dystonia, facial wrinkles (glabellar lines), bladder dysfunction and urinary incontinence, spasticity, axillary hyperhidrosis, spasmodic torticollis (cervical dystonia), and chronic migraine, among others. By preventing acetylcholine release at the neuromuscular junction, botulinum toxin A usually causes a temporary paralysis of the locally injected muscles. Complications related to this toxin include double vision (diplopia), eyelid droop (ptosis), and rarely, potentially life-threatening distant spread of toxin effect from the injection site hours to weeks after administration" @GoodmanGilmanPharmacological2023





## Delta-9-tetrahydrocannabinol (THC)

- "&Delta;<sup>9</sup>-Tetrahydrocannabinol (THC) is the phytocannabinoid responsible for the characteristic psychoactivity of Cannabi" @GoodmanGilmanPharmacological2023



::: {.callout title="Future Directions"}

Preprints:

- [International perspective on physician knowledge, attitude and practices related to medical cannabis](https://www.medrxiv.org/content/10.1101/2023.07.26.23293157v1)

:::



# Future directions


::: {.callout title="Preprints"}

- [Reduced reciprocal inhibition during clinical tests of spasticity is associated with impaired reactive standing balance control in children with cerebral palsy](https://www.medrxiv.org/content/10.1101/2023.11.07.23298160v1)


- Orthotics
    - [ANTERIOR OR POSTERIOR ANKLE FOOT ORTHOSES FOR ANKLE SPASTICITY: WHICH ONE IS BETTER?](https://www.medrxiv.org/content/10.1101/2021.03.02.21251574v1)
- Spinal stimulation
    - [Effects of spinal stimulation and short-burst treadmill training on gait biomechanics in children with cerebral palsy](https://www.medrxiv.org/content/10.1101/2024.05.31.24308292v2)
    - [Transcutaneous Spinal Stimulation and Short-burst Interval Treadmill Training in Children with Cerebral Palsy: A Pilot Study](https://www.medrxiv.org/content/10.1101/2023.11.21.23298538v2)
:::