---
title: Postural Orthostatic Tachycardia Syndrome (POTS)
---

# Definition

Must last at least 6 months and characterized by:

1. An Increase in HR >=30 BPM within 5-10 min of quiet standing or upright tilt (or >=40 bpm in those 12-19 years old) @bryarlyPosturalOrthostaticTachycardia2019.
1. The absence of orthostatic hypotension (>20 mmHg drop in systolic or >10 mmHg drop in diastolic) @bryarlyPosturalOrthostaticTachycardia2019.
1. Frequent symptoms that occur with standing such as lightheadedness, palpitations, tremulousness, generalized weakness, blurred vision, exercise intolerance, fatigue @bryarlyPosturalOrthostaticTachycardia2019.



# Epidemiology

- Typically young women (mean age 30 years) @bryarlyPosturalOrthostaticTachycardia2019.
- Most frequently preceded by symptoms of viral illness (~42%) or can occur post operatively (~9.5%) @bryarlyPosturalOrthostaticTachycardia2019.
- Usually a stressor will precipitate symptom onset: trauma, pregnancy, virus, or surgery @bryarlyPosturalOrthostaticTachycardia2019.
- A period of deconditioning (i.e. bedrest, decrease in activity) correlating with onset of POTS is debated-deconditioning could be a cardiac trigger or just something seen after diagnosis and thus a period of inactivity d/t symptoms @blitshteynPosturalTachycardiaSyndrome2016.
- Average HR increase from supine to upright of ~44BPM
POTS onset can be subacute (14%), insidious (6%) or acute (12%) @bryarlyPosturalOrthostaticTachycardia2019.


# Symptoms

::: {.callout-note}
Patients will typically feel faint, but will likely **not** faint @bryarlyPosturalOrthostaticTachycardia2019.
:::

::: {.columns}
::: {.column}

- Fatigue @bryarlyPosturalOrthostaticTachycardia2019
- Lightheadedness @bryarlyPosturalOrthostaticTachycardia2019
- Palpitations @bryarlyPosturalOrthostaticTachycardia2019
- Cognitive impairments @bryarlyPosturalOrthostaticTachycardia2019.

:::
::: {.column}

- GI symptoms: 
    - Nausea @bryarlyPosturalOrthostaticTachycardia2019.
    - Abdominal pain @bryarlyPosturalOrthostaticTachycardia2019.
- Bladder complaints (suprapubic pain) @bryarlyPosturalOrthostaticTachycardia2019.

:::
::: {.column}

- Peripheral edema @bryarlyPosturalOrthostaticTachycardia2019
- Acrocyanosis @bryarlyPosturalOrthostaticTachycardia2019
- Clammy skin @bryarlyPosturalOrthostaticTachycardia2019
- Joint hypermobility @bryarlyPosturalOrthostaticTachycardia2019
- Changes in peripheral sensation @bryarlyPosturalOrthostaticTachycardia2019

:::
:::



# Pathophysiology



- True cause is unknown @benarrochPosturalTachycardiaSyndrome2012
- Triggers can include:
    - Pregnancy @benarrochPosturalTachycardiaSyndrome2012
    - Major trauma @benarrochPosturalTachycardiaSyndrome2012
    - Viral illness (especially + GI fluid loss) @benarrochPosturalTachycardiaSyndrome2012
    - Prolonged bed rest @benarrochPosturalTachycardiaSyndrome2012
- Causes sympathoexcitation @benarrochPosturalTachycardiaSyndrome2012
- Standing up triggers activation of baroreflex and also a vestibulosympathetic reflex @benarrochPosturalTachycardiaSyndrome2012
- Lack of readaptation of vestibulosympathetic response can cause → tachycardia @benarrochPosturalTachycardiaSyndrome2012
- Subtypes have been identified and potential systems involved in each @benarrochPosturalTachycardiaSyndrome2012


"impaired sympathetic vasoconstriction leading to venous pooling, hypovolemia, deconditioning, and hyperadrenergic state.
Excessive reflex sympathoexcitation may be triggered by orthostatic stress via reduced baroreceptor input to the nucleus of the solitary tract (NTS) and activation of vestibulosympathetic reflexes (VSR) relayed via the medial vestibular nucleus (MVN), resulting in increased activity of sympathoexcitatory neurons of the rostral ventrolateral medulla. 
Many comorbidities of POTS, including visceral pain and dysmotility, other chronic pain conditions, and dizziness may reflect abnormal processing of interoceptive information, relayed via the NTS and parabrachial nucleus (PBN) via the ventromedial portion of the thalamus to a central network that includes the anterior cingulate cortex, insula, amygdala, hypothalamus, and periaqueductal gray region." @benarrochPosturalTachycardiaSyndrome2012



1. Standing up
1. Decreased baroreceptor input/activation of vestibulosympathetic reflex
1. Increased sympathetic drive 

::: {.callout-note}
Chronic pain pathways also involved
:::



# Subtypes



@marPosturalOrthostaticTachycardia2020

## Neuropathic POTS

Neuropathic POTs occurs when lower extremity sympathetic *denervation* results in reduced venoconstriction and therefore venous pooling [@bryarlyPosturalOrthostaticTachycardia2019; @zhaoPosturalOrthostaticTachycardia2024].
This is usually caused by an autonomic neuropathy of lower limbs [@bryarlyPosturalOrthostaticTachycardia2019; @zhaoPosturalOrthostaticTachycardia2024].
Since there is an inability to increase vascular tone in the lower extremity, these individuals experience an exaggerated heart rate (Tachycardia) and CO in an attempt to maintain mean arterial pressure (MAP) [@bryarlyPosturalOrthostaticTachycardia2019; @zhaoPosturalOrthostaticTachycardia2024]. 

:::{.callout-note}
This subtype generally has less anxiety, depression, greater overall self perceived health related QOL scores compared to other subtypes [@bryarlyPosturalOrthostaticTachycardia2019; @zhaoPosturalOrthostaticTachycardia2024].
:::

This subtype was proposed due to studies that found >50% of the POTS cohort demonstrated anhidrosis (loss of sweat function) in distal lower extremities and reduced c-fiber density on skin biopsy [@zhaoPosturalOrthostaticTachycardia2024].
In addition, POTS patients have been observed to have decreased norepinephrine "spillover" in their lower extremities despite normal *systemic* norepinephrine spillover [@zhaoPosturalOrthostaticTachycardia2024].
The researchers believed that this difference was indicative of injuried terminal lower extremity nerves resulting in norepinephrine uptake dysfunction [@zhaoPosturalOrthostaticTachycardia2024].





# References

Angeli, A.M., Salonen, B.R., Ganesh, R. et al. Symptom presentation by phenotype of postural orthostatic tachycardia syndrome. Sci Rep 14, 205 (2024). https://doi.org/10.1038/s41598-023-50886-8

Blitshteyn S, Fries D. Postural tachycardia syndrome is not caused by deconditioning. Pulm Circ. 2016;6(3):401. doi:10.1086/687757

Bryarly, M, Phillips, L, Fu, Q. et al. Postural Orthostatic Tachycardia Syndrome: JACC Focus Seminar. JACC. 2019 Mar, 73 (10) 1207–1228.https://doi.org/10.1016/j.jacc.2018.11.059
Ganesh R, Bonnes SLR, DiBaise JK. Postural Tachycardia Syndrome: Nutrition Implications. Nutr Clin Pract. 2020;35(5):818-825. doi:10.1002/ncp.10564

Lambert E, Eikelis N, Esler M, et al. Altered sympathetic nervous reactivity and norepinephrine transporter expression in patients with postural tachycardia syndrome. Circ Arrhythm Electrophysiol. 2008;1(2):103-109. doi:10.1161/CIRCEP.107.750471

Vernino S, Bourne KM, Stiles LE, Grubb BP, Fedorowski A, Stewart JM, Arnold AC, Pace LA, Axelsson J, Boris JR, Moak JP, Goodman BP, Chémali KR, Chung TH, Goldstein DS, Diedrich A, Miglis MG, Cortez MM, Miller AJ, Freeman R, Biaggioni I, Rowe PC, Sheldon RS, Shibao CA, Systrom DM, Cook GA, Doherty TA, Abdallah HI, Darbari A, Raj SR. Postural orthostatic tachycardia syndrome (POTS): State of the science and clinical care from a 2019 National Institutes of Health Expert Consensus Meeting - Part 1. Auton Neurosci. 2021 Nov;235:102828. doi: 10.1016/j.autneu.2021.102828. Epub 2021 Jun 5. PMID: 34144933; PMCID: PMC8455420.

Zhao S, Tran VH. Postural Orthostatic Tachycardia Syndrome. [Updated 2023 Aug 7]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2024 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK541074/

Zadourian, A., Doherty, T. A., Swiatkiewicz, I., & Taub, P. R. (2018). Postural orthostatic tachycardia syndrome: Prevalence, pathophysiology, and management. Drugs, 78(10), 983-994. doi:https://doi.org/10.1007/s40265-018-0931-5

