---
title: Surfing (Overview)
---

::: {.callout title="Reading list"}

- Surf Survival @nathansonSurfSurvival2019

:::

We can break surfing into multiple sections

- Paddling
    - Breathing
    - Endurance
    - Thoracic extension
- Duckdiving
- Paddle in
    - Double paddle
    - Kicking
- Takeoff (Pop-up)
- Bottom turn
- Surfing maneuvers


All surfing maneuvers are 3 dimensional techniques that require power, mobility, and stability in multiple planes of motion.



Fundamental parts of each maneuver:

- Compression
- Extension
- Rotation



# Brad Gerlach


::: {.columns}
::: {.column}
Fundamentals (1&2)

- Takeoff
- Bottom Turn
- Top Turn
- Cutback
- Tube Ride
- Floater
- Basic Air
- Speed generation

:::
::: {.column}

Fundamentals 3

- Advanced Takeoff (FS & BS)
- Advanced Bottom Turn (FS & BS)
- Carve (FS & BS)
- Advanced Cutback (FS & BS)
- Advanced Tube Ride (FS & BS)
- Advanced Floater (FS & BS)
- Blowtail (FS & BS)
- FS Layback
- BS Top Turn

:::
:::






# Pre-surf Warm up

- Shoulder movement prep
- Prone press

# Land training

The goal for land training is to improve surf recovery and to create general mobility and stability.
From a physical therapy perspective, we should be optimizing a surfer's body to be able to achieve their goals.
We should *not* be telling them *how* to surf.

# Hip Mobility

- Rotation
    - low-high chop - closing pattern

- Lateral deadlift
    - Stability while weight shifting

- Bridge position
    - 9090 Alternating hip thrust
    - Elevated long bridge
    - Elevated long bridge with contralateral press

## Plyos


- Ladder 90&deg; rotation jumps
    - focus on landing with both feet at the same time

{{< video https://www.youtube.com/watch?v=tCh7MQ_VvNw >}}

# Paddle Training

Endurance is indirectly the most important aspect of surf training.
There is no method of training a sport better than <bold>just doing the sport</bold>.

This is where working on paddle endurance is important.
If we can paddle faster and for longer, it lets one go for more waves per session.
The more waves you catch, the more you can practice surfing.

<ul>
    <li>Swimming laps</li>
    <li>Prone on SB with lat pulldowns</li>
</ul>

# Takeoff training

An important aspect of the takeoff is the ability to extend the thoracic spine as the arms push one upwards and the ability to pull the lower extremity underneath oneself.

## Thoracic extension and scapular mobility {#thoracic-extension-training}

Mobility

- Prone press
    - This is designed to improve active thoracic extension
    - This is *not* supposed to be a way to replace a surfer's takeoff.

<ul>
    <li>Prone press-ups</li>
    <li>Prone WERs</li>
    <li>Prone superman</li>
</ul>

<ul>
    <li>Plank with scapular activation</li>
    <li></li>
    <li></li>
</ul>


Strength

<ul>
    <li>Behind the head pullups</li>
    <li>T's</li>
    <li>Push-ups</li>
    <li></li>
</ul>

Power

<ul>
    <li>Clap push-ups</li>
    <li>Burpees</li>
    <li></li>
</ul>

Functional training

<ul>
    <li>Pop-up on land</li>
    <li>Takeoff onto bosu</li>
</ul>


# Neck training

Overuse of global neck extensors, namely the [levator scapulae]({{< var ref-levator-scapulae.path >}}) and [upper trapezius]({{< var ref-upper-trapezius.path >}}) is common while surfing.
Here are some ways to strengthen the deep neck flexors

<ul>
    <li>Hemi Y's, T's, I's</li>
    <li>Prone/hemi/quadruped position</li>
</ul>




# Bottom Turn

## Frontside Bottom Turn
Bottom turn has a few key steps:

<ol>
    <li><bold>Compress down</bold>: After the takeoff, bend your knees and compress into <i>triple flexion</i> to get balance and control over your board.</li>
    <li><bold>Initiate the Turn</bold>: </li>
        <li>Weight distributed equally</li>
        <li>Look in the direction you want to go</li>
        <li>Dig the inside rail</li>
    <li>bold{Dig the Rails}:</li>
        <li>Lean forward to shift weight to your toes.</li>
        <li>Reaching forward with your rear hand can help.</li>
        <li>Stay compressed while holding the turn and pivoting towards the face.</li>
    <li><bold>Weighted back foot and rotation</bold>: "Once you start turning up towards the face, apply more pressure on the tail with your back foot. More pressure on the back foot and more rotation of your hips and chest will translate into more advanced, sharper and faster turns up towards the top of the wave. Notice how, from picture #3 to picture #4, the surfer’s hips and chest twisted towards the direction he wants to go.</li>
    <li>bold{Decompress + maneuver}: "As you go back up the face, decompress by slightly unbending your knees and lifting your chest in a straighter position. Draw the proper line on the shoulder according to the manoeuvre you want to do."</li>
    <li></li>
</ol>


## Backside Bottom Turn

<!-- "The backside bottom turn is very similar to the frontside bottom turn, except for a few differences. The first steps are the same: you need to compress low, look where you want to go and start with equal weight over both feet." -->

<bold>Differences</bold>:‍ 
<!-- "The main differences appear when you reach the bottom of the wave and initiate the turn. It will be harder to see the shape of the wave than on the frontside bottom turn because your back faces the wave. Make sure you look properly over your front shoulder." -->

<!"Instead of leaning forward, you will need to lean backward to put more weight over your heels. You can reach back towards the wave with your front hand to open your body in the direction of the wave. To do major backside bottom turns, surfers need to square their shoulders toward the direction they want to go. This means a backside bottom turn requires a full body rotation, bringing the back shoulder and arm pointing towards the top of the wave." -->

<bold>Similarities</bold>: ‍
<!-- "Apart from those differences, the rest is very similar to a frontside bottom turn. For example, you still need to compress and hold the turn as you get on your rail and start to pivot towards the face. Putting weight on the tail with your back foot will again help you come back up on the shoulder faster, with a more vertical line. Just like with a frontside bottom turn, you still need to decompress as you draw your line up on the shoulder." -->


<bold>Common mistakes</bold>:

<!-- <ul>
    <li><bold>Wrong depth of turn</bold>: "If you don’t draw the proper line according to the shoulder shape, you end up at the wrong place. For example, if you decide to do a very steep, vertical bottom turn on a soft, flat shoulder, the wave won’t have the power and shape to bring you back down. You will probably end up flying through the back of the wave."</li>
    <li>bold{Too much weight on the front foot}: "Having too much weight on your front foot during the bottom turn can bury the rail too much, stall the surfboard or make you fall off."</li>
    <li><bold>Not holding your line</bold>: "To maintain maximum speed you must hold your initial line. This is only possible if you initially drew the proper line to propel yourself in the right area of the wave. Changing direction is normal for beginners and intermediates, because they are learning to read how the wave will break. Note that tiny adjustments can have a huge effect on your momentum and make you lose a lot of speed."</li>
    <li><bold>Not opening the leading arm towards the wave on the backside bottom turn</bold>: Bottom turns are usually harder on the backside because it’s difficult to see and to turn your body to the wave. Reaching down towards the wave with your front hand will help initiate your body rotation towards the direction you want to go. It also helps you see the wave behind you and initiate the full-body rotation, bringing your back arm towards the top of the wave.</li>
    <li></li>
</ul> -->





## Training


To work on my bottom turn, I go into the session with the goal of

<ol>
    <li>Go for as many waves as possible</li>
    <li>Bottom turn as <i>hard</i>as possible</li>
    <li>Do <i>not</i> grab rail on backside</li>
</ol>


{{< video https://www.youtube.com/watch?v=HAH4QFu6iiQ >}}

# Endurance

Breath holds and aerobic endurance [@greeverAerobicFitnessMarkers2019].

# Stance

{{< video https://www.youtube.com/watch?v=kOgg2FJnxuU >}}

# Duck dive
{{< video https://www.youtube.com/watch?v=ELxAvt5eIJI >}}


# Top Turn

{{< video https://www.youtube.com/watch?v=SiLgfcAu6Gc >}}



