---
title: Surfing Roundhouse cutback
subtitle: Surfing technique
---


A roundhouse cutback refers to a surfing technique where the surfer performs a "figure 8" starting at the shoulder of the wave and ending by performing a turn off the whitewater.


A roundhouse cutback can be a good cue for training top turns, since it requires the surfer to look all the way back to the pocket.

# Approach

The approach must be less aggressive than a snap since you need to maintain speed in order to achieve the figure 8 path.


# Key moment

- Make sure the lead arm is pointed behind the whitewater as you turn towards
- The lead arm shoulder then be turned over the whitewater as you get the boost of speed from the turn off the whitewater.
# Steps



1. Compress at the bottom of the wave as you approach the top
1. Extend from the top of the wave as you turn
1. Half-compress as you ascend the wave, moving towards the whitewater
    - Look & point back to the whitewater behind you
1. Rebound off the whitewater

