---
title: Tibialis Anterior Muscle
---



```{python tbl-oian}
#| label: tbl-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'muscle_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['tibialis_anterior']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```

# Origin {#origin}

- Tibia (upper 2/3 of the lateral surface) @gilroyAtlasAnatomy2020
- Interosseous membrane @gilroyAtlasAnatomy2020
- Superficial crural fascia (highest part) @gilroyAtlasAnatomy2020

# Insertion {#insertion}

- Medial cuneiform specifically the medial and plantar surfaces @gilroyAtlasAnatomy2020
- 1st metatarsal (medial base) @gilroyAtlasAnatomy2020

Functionally, the anterior tibialis inserts on the convex aspect of the medial arch @jonesProjectFoundations2025.

# Nerve
[Deep Fibular N.]({{< var ref-deep-fibular-nerve.path >}}) ([L4]({{< var ref-nerve-root.l4 >}}), [L5]({{< var ref-nerve-root.l5 >}})) @gilroyAtlasAnatomy2020

# Action {#action}

- **Talocrural joint**: Dorsiflexion
- **Subtalar joint**: inversion (supination)

The tibialis anterior works more as a supinator rather than an adductor @jonesProjectFoundations2025.


# Observation

"The tendon of the tibialis anterior is visible at the level of the medial cuneiform and the base of the first metatarsal bone, especially if the foot is positioned in dorsiflexion and supination" @duttonDuttonOrthopaedicExamination2020 

# Examination

:::{layout-ncol="3"}
### MMT

- DF/inv
- "The tibialis anterior muscle produces the motion of dorsiflexion and inversion. The knee must remain flexed during the test to allow complete dorsiflexion. The patient’s foot is positioned in dorsiflexion and inversion. The leg is stabilized, and resistance is applied to the medial posterior aspect of the forefoot into plantar flexion and eversion" @duttonDuttonOrthopaedicExamination2020 

### ROM

- PF + EV

### Palpation


:::