---
title: Ski Athlete
---



# Preseason training

:::{.callout title="Stretch affect program"}


- SL RDL horizontal cable rows
- 

:::

## Cardio

- Wind bike (100kcal)
- Cascade climber 50% intensity 3x1min (for hip flexors)

::: {.columns}
::: {.column}
### Adductors

- Copenhagens
:::
::: {.column}

### Abductors

- CKC Clam shells
- Hip movement prep series
- SL Squat slideouts
    - Progress to bulgarians

:::
:::





## Calves

3D Calf raise

## Compound movements

- Squat low-high cable row
- SL RDL cable
- TRX Pistol squats
- SL squat reverse slideout
- Landmine lateral skater squat


## Agility

- Ladder drill
    - 2 in 2 out lateral steps
    - Lateral hops feet together

## Plyometric

- 1 leg lateral bound
- Alternating lateral hops
- Box jumps
    - DL to DL
    - SL to DL
    - DL turn to DL alternating


## Balance

- SLB with 3 way reach



# Foundation training

::: {.callout title="Stretch affect Ski foundations"}

- Open books
- "Brettzel"
- Gastroc stretch
- Soleus stretch
- Hip movement primer
- Hip airplanes
- SL Squat to RDL
- Wall sit + Adduction
- Forward Lunge rep to hold
- Lateral lunge rep to hold
- Squat rep to hold

:::
