---
title: Sacroiliac Joint (SIJ)
---

::: {.callout title="Reading list"}

- General
    - ch29 SIJ @duttonDuttonOrthopaedicExamination2020
- Examination
    - Ch16 Screening the Sacrum, Sacroiliac, and Pelvis @heickGoodmanSnyderDifferential2023

:::


planar synovial joints [@aptaCurrentConceptsOrthopaedic2024]

The joint surfaces are smooth in children and younger adults but slowly roughen over time which can decrease function [@aptaCurrentConceptsOrthopaedic2024].



# Aging


The joint surfaces are smooth in children and younger adults but slowly roughen over time which can decrease function [@aptaCurrentConceptsOrthopaedic2024].

# Function

A number of factors impact function of the SIJ.


# Dysfunction



# HVLAT

- SIJ HVLAT in Lateral Recumbent with Lateral Flex/Ext/Rot & Body Drop p101 [@dunningSMT1HighVelocityLowAmplitude2018]
- Lumbosacral Junction (L5-S1) HVLAT in Lateral Recumbent with Extension/Rotation & Sacral Forearm "Pull" Body Drop p101 [@dunningSMT1HighVelocityLowAmplitude2018]