---
title: Sternoclavicular Joint (SCJ)
---


The sternoclavicular joint is a saddle joint


# Joint Structure

Since the SCJ is a saddle joint, both the distal and proximal joint surfaces have concave and convex facets.

- Frontal plane: 
    - Convex on Concave
    - Superior roll and inferior slide
- Transverse plane:
    - Concave on convex
    - Concave clavicle on convex sternum 
    - Anterior roll and slide


- 6&deg; upward slope
- Posterior to the frontal plane 20 deg

# Kinematics

## Elevation

- Elevation (45-60&deg;)

## Depression

- Depression (10-15&deg;)

## Protraction

- Protraction = retraction (15-30&deg;)

## Retraction

- Protraction = retraction (15-30&deg;)

## Rotation

- Rotation (post) 40-50&deg;




# Palpation {#palpation}

To palpate the sternoclavicular joint:

- Locate the *suprasternal notch*, which can be found on the superior aspect of the manubrium @finandoTriggerPointTherapy2005.
- Move laterally from the *suprasternal notch* to the sternoclavicular joint @finandoTriggerPointTherapy2005.
- Alternating elevation and depression of the shoulder while palpating the joint will help you to clearly distinguish between the [manubrium]({{< var ref-sternum-bone.manubrium >}}) and the [clavicle]({{< var ref-clavicle-bone.path >}}) @finandoTriggerPointTherapy2005.

::: {.callout-note}
At the sternoclavicular joint, the [clavicle]({{< var ref-clavicle-bone.path >}}) is raised slightly above the manubrium at the articulation @finandoTriggerPointTherapy2005.
:::


# Stabilization

Tissues that stabilize the SCJ:

Anterior and posterior sternoclavicular joint ligaments
Interclavicular ligament
Costoclavicular ligament
Articular disc


::: {.columns}
::: {.column}
### Passive Stabilizers
:::
::: {.column}
### Active Stabilizers

- [Subclavius]({{< var ref-subclavius.path >}}) [@duttonDuttonOrthopaedicExamination2020; @gilroyAtlasAnatomy2020; @neumannKinesiologyMusculoskeletalSystem2017]
- [Sternocleidomastoid]({{< var ref-sternocleidomastoid.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Sternothyroid]({{< var ref-sternothyroid.path >}}) @neumannKinesiologyMusculoskeletalSystem2017
- [Sternohyoid]({{< var ref-sternohyoid.path >}}) @neumannKinesiologyMusculoskeletalSystem2017

:::
:::




# Clinical Significance

Biomechanical studies have shown a variation of 15-31 degrees in the SC joint through the rotation of the clavicle during the movements of the arm in the frontal plane (abduction) and less in the sagittal plane (flexion) @ludewigThreedimensionalClavicularMotion2004 (Ludewig et al. 2004)

# Clinical Presentation

AROM limitations 
- ABD is most limited when missing a clavicle