---
title: Functional Movement Spectrum
---


The functional movement spectrum has 3 purposes:

1. Identify principles to guide movement @grayinstituteFunctionalTechniques.
1. Simplify complexity to define function @grayinstituteFunctionalTechniques.
1. To guide development and utilization of functional movement @grayinstituteFunctionalTechniques.




::: {#tbl-functional-movement-spectrum}


<style>
  .basic-table tbody td:first-child {
    font-weight: bold;
  }
</style>
<table class="basic-table">
  <thead>
    <tr>
      <th></th>
      <th>Non-functional</th>
      <th>Functional</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Environment</td>
      <td>Unnatural</td>
      <td>Natural</td>
    </tr>
    <tr>
      <td>Gravity & GRF</td>
      <td>Confused</td>
      <td>Used</td>
    </tr>
    <tr>
      <td>Mass & Momentum</td>
      <td>Neglected</td>
      <td>Leveraged</td>
    </tr>
    <tr>
      <td>Motion</td>
      <td>1-D</td>
      <td>3-D</td>
    </tr>
    <tr>
      <td>Reaction</td>
      <td>Link</td>
      <td>Chain</td>
    </tr>
    <tr>
      <td>Proprioceptors</td>
      <td>Inhibited</td>
      <td>Facilitated</td>
    </tr>
    <tr>
      <td>Muscles</td>
      <td>Actor</td>
      <td>Reactor</td>
    </tr>
    <tr>
      <td>Joints</td>
      <td>Isolated</td>
      <td>Integrated</td>
    </tr>
    <tr>
      <td>Task</td>
      <td>Conscious reaction</td>
      <td>Subconscious reaction</td>
    </tr>
    <tr>
      <td>Specificity</td>
      <td>Stagnation</td>
      <td>Transformation</td>
    </tr>
    <tr>
      <td>Mobility / Stability</td>
      <td>Segregated</td>
      <td>Combined</td>
    </tr>
    <tr>
      <td>Encouragement</td>
      <td>Failure</td>
      <td>Success</td>
    </tr>
    <tr>
      <td>Empowerment</td>
      <td>External locus of control</td>
      <td>Internal locus of control</td>
    </tr>
    <tr>
      <td>Engagement</td>
      <td>Irrelevant</td>
      <td>Relevant</td>
    </tr>
  </tbody>
</table>

Functional movement spectrum @grayinstituteFunctionalTechniques

:::