---
title: Foundations Course Continued Education Notes
subtitle: My notes from the Gray Institute Course
---


# Environment

# Gravity and Ground Reaction Forces



# Mass and Momentum



# Motion


# Reaction

# Proprioceptors

Used a Y-excursion style workout but used sagittal, frontal plane AND transverse plane.
I would teach the Y-excursion as going in straight directions, but they used looping movements in order to target rotation at the ankle and not just DF/PF and INV/EV.


# Muscles

Actor (nonfunctional) or Reactor (Functional).

Dr. Gray proposed that EMG activity is <i>misinterpreted</i> and increased EMG activity is not a good sign of muscle activation, but rather unnatural muscle isolation and overuse.

- Asking a patient to manually activate a muscle is defined by the Gray Institute as an <i>actor</i> and is nonfunctional
- Instead we should be recreating the environment and motion which loads the body and muscle and its synergists to co-contract 
- Gray suggests that when a muscle is <i>inactive</i> that it is due to lack of motion at the wrong joint and the wrong time.

Gray suggests that muscles always want to activate eccentrically first.
Muscles eccentrically decelerate a motion, which builds elastic potential energy and the muscle uses that to make the concentric aspect of the movement more efficient.

"econcentric" is how the gray institute describes a muscle's motion.
"Econcentric" refers to the fact that a muscle uses eccentric movement in a plane or joint while also creating concentric motion at a different joint/motion.


Biceps and Triceps matrices

- Biceps Matrix: Biceps are traditionally known for shoulder and elbow flexion.
    - GrayInstitute suggest looking into the frontal and transverse planes
    - When doing a bicep flex, move the wrist from pronation to supination and you should see the bicep muscle "pop" or seemingly get larger
- Triceps matrix: Triceps are traditionally known for acting in the sagittal plane to create shoulder and elbow extension
    - We can incorporate the transverse plane with shoulder and wrist rotation
    - We can incorporate the frontal plane using shoulder abduction/adduction

Hip flexor muscles primarily work in the sagittal plane, but we should also considering lengthening and shortening in the transverse and frontal plane

- Sagittal plane stretch: split squat position
- Frontal plane: 
    - Trunk sidebend contralaterally and ipsilaterally to impact frontal plane
    - Place lead foot more abducted (wider stances)
    - place lead foot more adducted (narrower stance) 
- Transverse plane:
    - Trunk rotation ipsilaterally and contralaterally
    - Internally or externally rotate rear foot


# Joints

- Nonfunctional: Isolated
    - Isolated refers to seeing the joint in a vacuum and not considering the joints distal and proximal
- Functional: Integrated


# Task

# Specificity


# Mobility & Stability

# Encouragement, Empowerment, Engagement

