---
title: Functional Techniques Continued education Notes
subtitle: Continued education by the Gray Institute
description: "This is a summary of my notes from the Gray Institute courses as well as alternative opinions"
---

# Functional Techniques Certification

## Chain reaction

Refers to the interplay between the joints and muscles when someone moves.



## Muscle function

Dr. Gray states that when he was studying in PT school, they were taught to perform assessments on the table in a "nonfunctional" and "context-dependent" position.

Gray states that in reality (based on studies they have read), the muscles do not have isolated functions in single planes or on select joints @grayinstituteFunctionalTechniques.
Rather, the muscles work on all 3 planes of motion and on multiple joints @grayinstituteFunctionalTechniques.



## PST Process

- P - Principles
- S - Strategies
- T - Techniques



## Functional movement spectrum

The functional movement spectrum has 3 purposes:

1. Identify principles to guide movement @grayinstituteFunctionalTechniques.
1. Simplify complexity to define function @grayinstituteFunctionalTechniques.
1. To guide development and utilization of functional movement @grayinstituteFunctionalTechniques.




::: {#tbl-functional-movement-spectrum}


<style>
  .basic-table tbody td:first-child {
    font-weight: bold;
  }
</style>
<table class="basic-table">
  <thead>
    <tr>
      <th></th>
      <th>Non-functional</th>
      <th>Functional</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Environment</td>
      <td>Unnatural</td>
      <td>Natural</td>
    </tr>
    <tr>
      <td>Gravity & GRF</td>
      <td>Confused</td>
      <td>Used</td>
    </tr>
    <tr>
      <td>Mass & Momentum</td>
      <td>Neglected</td>
      <td>Leveraged</td>
    </tr>
    <tr>
      <td>Motion</td>
      <td>1-D</td>
      <td>3-D</td>
    </tr>
    <tr>
      <td>Reaction</td>
      <td>Link</td>
      <td>Chain</td>
    </tr>
    <tr>
      <td>Proprioceptors</td>
      <td>Inhibited</td>
      <td>Facilitated</td>
    </tr>
    <tr>
      <td>Muscles</td>
      <td>Actor</td>
      <td>Reactor</td>
    </tr>
    <tr>
      <td>Joints</td>
      <td>Isolated</td>
      <td>Integrated</td>
    </tr>
    <tr>
      <td>Task</td>
      <td>Conscious reaction</td>
      <td>Subconscious reaction</td>
    </tr>
    <tr>
      <td>Specificity</td>
      <td>Stagnation</td>
      <td>Transformation</td>
    </tr>
    <tr>
      <td>Mobility / Stability</td>
      <td>Segregated</td>
      <td>Combined</td>
    </tr>
    <tr>
      <td>Encouragement</td>
      <td>Failure</td>
      <td>Success</td>
    </tr>
    <tr>
      <td>Empowerment</td>
      <td>External locus of control</td>
      <td>Internal locus of control</td>
    </tr>
    <tr>
      <td>Engagement</td>
      <td>Irrelevant</td>
      <td>Relevant</td>
    </tr>
  </tbody>
</table>

Functional movement spectrum @grayinstituteFunctionalTechniques

:::


::: {.columns}
::: {.column}
### Physical principles

- [Environment](#environment-fms)
- [Gravity & Ground reaction forces](#gravity-grf-fms)
- [Mass & momentum](#mass-momentum-fms)

:::
::: {.column}
### Biological principles

- [Motion](#motion-fms)
- [Reaction](#reaction-fms)
- [Proprioceptors](#proprioceptors)
- [Muscles](#muscles-fms)
- [Joints](#joints-fms)
- [Task](#task-fms)
- [Specificity](#specificity-fms)
- [Mobility/stability](#mobility-stability-fms)

:::
::: {.column}
### Behavioral principles

- Encouragement
- Empowerment
- Engagement

:::
:::

## Environment {#environment-fms}

Environment is one of the 3 physical principles.
You should be constantly asking yourself, "is this environmental functional for the goal?"



## Gravity & GRF {#gravity-grf-fms}




## Mass & Momentum {#mass-momentum-fms}

## Motion {#motion-fms}

## Reaction {#reaction-fms}

## Proprioceptors {#proprioceptors-fms}
## Muscles {#muscles-fms}
## Joints {#joints-fms}

## Task {#task-fms}

## Specificity {#specificity-fms}

Specificity is a way to change how functional a movement is.
Movements that have "Stagnation" of positions, are considered non-functional.
Whereas, movements with "Transformation" (changing position and momentum) are considered more functional.

Stagnation refers to when many of the movements that are specific to the functional goal, are being *inhibited*.

An example of a movement with transformation is walking/running, where the body alternates between force production and force absorption.

## Mobility/stability {#mobility-stability-fms}

## Encouragement {#encouragement-fms}

## Empowerment {#empowerment-fms}

## Engagement {#engagement-fms}


# Foundations Certificate

In module 1, we took a deep dive into the *functional movement spectrum* and how it relates exercise prescription.
It is not necessarily a bad thing to be on the non-functional side of the spectrum, as long as you know that you are choosing nonfunctional movements and *why*.


In module 2, I learned about the importance of terminology and nomenclature.
The Gray Institute applies the "SFT Syntax": Sagittal Frontal Transverse.





# Alternative viewpoints


- Gray institute's AFS focuses on performing movements, rather than working on specific cues to correct the improper movements.