---
title: Abdominal wall muscles
---





- Anterior
    - Rectus abdominis
    - Pyramidalis
- Anterolateral
    - External oblique
    - Internal oblique
    - Transversus abdominis
- Posterior
    - Psoas major
    - Iliacus
    - Quadratus lumborum (QL)
    - Psoas minor @jonesProjectFoundations2025


::: {.callout-note}
Brad Jones @jonesProjectFoundations2025 separated the abdominal wall into 2 sections:

- Anterolateral
    - External oblique
    - Internal oblique
    - Transversus abdominis
    - Rectus abdominis
    - Pyramidalis
- Posterior
    - Psoas major
    - Iliacus
    - Quadratus lumborum (QL)
    - Psoas minor @jonesProjectFoundations2025
:::


```{python tbl-abdominal-wall-oian}
#| label: tbl-glute-ed-oian
#| warning: false
#| message: false
#| echo: false

from pathlib import Path
import pandas as pd
from pyprojroot import here
from IPython.core.display import display, HTML

# Set the path for the script file
script_file_path = here("scripts/process_oian_table.py")

# Check if the script file exists
if script_file_path.exists():
    import sys
    sys.path.append(str(script_file_path.parent))  # Add the directory of the script to the system path

    from process_oian_table import process_oian_table  # Import the specific function

    # Define the column to filter by and the identifiers to include
    filter_column = 'group_identifier'  # Choose the column you want to filter by
    filter_identifiers = ['abdominal_wall_muscles']  # Replace with actual identifiers you want to include

    # Call the function to get the HTML table with filtering
    html_table = process_oian_table(filter_column=filter_column, filter_identifiers=filter_identifiers)

    if html_table:
        # Render the HTML table for display
        display(HTML(html_table))  # Use display to render the HTML properly
else:
    print("Script file does not exist. Please check the path.")

```


# Anterolateral abdominal wall

The 5 paired muscles of the anterolateral abdominal wall can be divided into 2 groups @jonesProjectFoundations2025:

::: {.columns}
::: {.column}
### Anterior vertical muscles

- Rectus abdominis @jonesProjectFoundations2025
- Pyramidalis @jonesProjectFoundations2025

:::
::: {.column}

### Lateral flat muscles

- Transverse abdominis
- Internal oblique
- External oblique

:::
:::




# Hollowing

All of these muscles are important for flexion and "hollowing" @jonesProjectFoundations2025.
Each part of the abdominal wall draws in a different part of the body towards the midline of the (linea alba).
The external obliques draw in the ribcage infero-medially.
The internal obliques draw the ilium superior medially.
the transverse abdominis draws the sides of the body medially.
The rectus abdominis pulls the ribcage inferiorly and pelvis superiorly.


# Trunk Flexion

2 levers:

1. Pubic symphysis to the sacral promontory
1. Xiphoid to thoracic spine

